# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import enum
import typing
import typing_extensions
import pydantic

if typing.TYPE_CHECKING:
    from ... import ai
    from ... import baml
    from ...baml import UNSET as UNSET


class Text(pydantic.BaseModel):
    text: str


class Reasoning(pydantic.BaseModel):
    summary: str


class ToolUse(pydantic.BaseModel):
    id: str
    name: str
    args: typing.Dict[str, typing.Any]


class Media(pydantic.BaseModel):
    media: ai.MediaPart
    provider_id: typing.Optional[str] = None
    revised_prompt: typing.Optional[str] = None
    @staticmethod
    def new(value: typing.Union[baml.media.Image, baml.media.Audio, baml.media.Video, baml.media.Pdf], *, provider_id: typing.Union[str, None, UNSET] = None, revised_prompt: typing.Union[str, None, UNSET] = None) -> Media:
        """Wrap a media value a client just built from a provider payload.
        `baml.media.Image.from_base64` and its siblings return the `image` /
        `audio` / `video` / `pdf` primitives, and `baml.media.Image` is the
        declaration that carries `image`'s members rather than a second
        nominal type, so the value already is a `MediaPart` member."""
    @staticmethod
    async def new_async(value: typing.Union[baml.media.Image, baml.media.Audio, baml.media.Video, baml.media.Pdf], *, provider_id: typing.Union[str, None, UNSET] = None, revised_prompt: typing.Union[str, None, UNSET] = None) -> Media:
        """Wrap a media value a client just built from a provider payload.
        `baml.media.Image.from_base64` and its siblings return the `image` /
        `audio` / `video` / `pdf` primitives, and `baml.media.Image` is the
        declaration that carries `image`'s members rather than a second
        nominal type, so the value already is a `MediaPart` member."""
    def kind(self) -> str:
        """The payload's media kind: "image", "audio", "video", or "pdf"."""
    async def kind_async(self) -> str:
        """The payload's media kind: "image", "audio", "video", or "pdf"."""


def blocks(items: typing.List[typing.Union[str, baml.media.Image, baml.media.Audio, baml.media.Video, baml.media.Pdf, Text, Media]]) -> typing.List[Block]:
    """Content blocks from ordinary values: a bare `string` becomes `Text`, a bare
    `image` / `audio` / `video` / `pdf` becomes `Media` with null provenance, and
    a block already built passes through. The one constructor behind
    `root.events.UserMessage.of` and `root.events.ToolCompleted.of`."""
async def blocks_async(items: typing.List[typing.Union[str, baml.media.Image, baml.media.Audio, baml.media.Video, baml.media.Pdf, Text, Media]]) -> typing.List[Block]:
    """Content blocks from ordinary values: a bare `string` becomes `Text`, a bare
    `image` / `audio` / `video` / `pdf` becomes `Media` with null provenance, and
    a block already built passes through. The one constructor behind
    `root.events.UserMessage.of` and `root.events.ToolCompleted.of`."""


def text(content: typing.List[Block]) -> str:
    """The readable projection of a block list: `Text` blocks as written, each
    `Media` block as a `[image]`-style placeholder, joined in order."""
async def text_async(content: typing.List[Block]) -> str:
    """The readable projection of a block list: `Text` blocks as written, each
    `Media` block as a `[image]`-style placeholder, joined in order."""


class StopReason(str, enum.Enum):
    Complete = "Complete"
    ToolUse = "ToolUse"
    MaxTokens = "MaxTokens"
    Refused = "Refused"


Block: typing.TypeAlias = typing.Union[Text, Media]


ModelBlock: typing.TypeAlias = typing.Union[Block, Reasoning, ToolUse]


__all__ = [
    "Text",
    "Reasoning",
    "ToolUse",
    "Media",
    "blocks",
    "blocks_async",
    "text",
    "text_async",
    "StopReason",
    "Block",
    "ModelBlock",
]
