# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

_LAZY_CHILDREN = frozenset({
    "crypto",
    "csv",
    "env",
    "errors",
    "fs",
    "future",
    "glob",
    "host",
    "http",
    "id",
    "io",
    "iter",
    "json",
    "media",
    "net",
    "ops",
    "panics",
    "random",
    "sap",
    "spawn",
    "sys",
    "time",
    "toml",
    "ws",
    "yaml",
})

def __getattr__(name):
    if name in _LAZY_CHILDREN:
        import importlib
        return importlib.import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

import typing
import typing_extensions
import pydantic

if typing.TYPE_CHECKING:
    from .. import baml

from baml_bridge import define_function as _define_function

from baml_bridge import BamlError as BamlError, BamlPanic as BamlPanic, UNSET as UNSET


A = typing.TypeVar("A")
E = typing.TypeVar("E")
K = typing.TypeVar("K")
T = typing.TypeVar("T")
U = typing.TypeVar("U")
V = typing.TypeVar("V")


class Bigint(pydantic.BaseModel):
    """
    An arbitrary-precision signed integer, like Python's `int` or JavaScript's
    `BigInt`. Where `int` panics on overflow, `bigint` grows.

    Literals carry a trailing `n` and may be decimal (`42n`), hex (`0xFFn`),
    octal (`0o755n`), or binary (`0b1010n`), with `_` digit separators allowed
    (`1_000_000n`).

    `&`, `|`, and `^` treat a bigint as an infinite sign-extended two's
    complement bit string, matching JavaScript `BigInt` and Python `int`:
    `(-1n) & 1n` is `1n`, `(-1n) | 0n` is `-1n`, `(-1n) ^ 0n` is `-1n`.

    # Panics

    Bigint operators and methods raise the panics below. They are not declared
    via `throws` because they signal that the program tried to do something
    invalid, rather than a recoverable runtime condition.

    - `baml.panics.DivisionByZero` — `a / 0n` or `a % 0n`.
    - `baml.panics.NegativeBitShift` — `a << -1n` or `a >> -1n`. The shift
      count must be non-negative.
    - `baml.panics.AllocFailure` — an operand or result would need more than
      about 268M bits, `bigint`'s workspace cap. Raised by `a * b`, `a << n`,
      and `a.pow(n)` when the predicted result exceeds the cap, and by
      `bigint.parse(s)` when `s` carries more decimal digits than the cap
      permits.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    parse       = staticmethod(_define_function("baml.Bigint.parse", "sync",  ["text"], binding_name="parse", binding_qualname="Bigint.parse", binding_module=__name__))
    parse_async = staticmethod(_define_function("baml.Bigint.parse", "async", ["text"], binding_name="parse_async", binding_qualname="Bigint.parse_async", binding_module=__name__))
    random       = staticmethod(_define_function("baml.Bigint.random", "sync",  ["lower", "upper"], ["rng"], binding_name="random", binding_qualname="Bigint.random", binding_module=__name__))
    random_async = staticmethod(_define_function("baml.Bigint.random", "async", ["lower", "upper"], ["rng"], binding_name="random_async", binding_qualname="Bigint.random_async", binding_module=__name__))
    _random_byte_count_       = staticmethod(_define_function("baml.Bigint._random_byte_count", "sync",  ["lower", "upper"], binding_name="_random_byte_count_", binding_qualname="Bigint._random_byte_count_", binding_module=__name__))
    _random_byte_count__async = staticmethod(_define_function("baml.Bigint._random_byte_count", "async", ["lower", "upper"], binding_name="_random_byte_count__async", binding_qualname="Bigint._random_byte_count__async", binding_module=__name__))
    _random_in_range_       = staticmethod(_define_function("baml.Bigint._random_in_range", "sync",  ["draw", "lower", "upper"], binding_name="_random_in_range_", binding_qualname="Bigint._random_in_range_", binding_module=__name__))
    _random_in_range__async = staticmethod(_define_function("baml.Bigint._random_in_range", "async", ["draw", "lower", "upper"], binding_name="_random_in_range__async", binding_qualname="Bigint._random_in_range__async", binding_module=__name__))
    abs       = _define_function("baml.Bigint.abs", "sync",  ["self"], binding_name="abs", binding_qualname="Bigint.abs", binding_module=__name__)
    abs_async = _define_function("baml.Bigint.abs", "async", ["self"], binding_name="abs_async", binding_qualname="Bigint.abs_async", binding_module=__name__)
    isqrt       = _define_function("baml.Bigint.isqrt", "sync",  ["self"], binding_name="isqrt", binding_qualname="Bigint.isqrt", binding_module=__name__)
    isqrt_async = _define_function("baml.Bigint.isqrt", "async", ["self"], binding_name="isqrt_async", binding_qualname="Bigint.isqrt_async", binding_module=__name__)
    pow       = _define_function("baml.Bigint.pow", "sync",  ["self", "exp"], binding_name="pow", binding_qualname="Bigint.pow", binding_module=__name__)
    pow_async = _define_function("baml.Bigint.pow", "async", ["self", "exp"], binding_name="pow_async", binding_qualname="Bigint.pow_async", binding_module=__name__)
    ilog       = _define_function("baml.Bigint.ilog", "sync",  ["self", "base"], binding_name="ilog", binding_qualname="Bigint.ilog", binding_module=__name__)
    ilog_async = _define_function("baml.Bigint.ilog", "async", ["self", "base"], binding_name="ilog_async", binding_qualname="Bigint.ilog_async", binding_module=__name__)
    to_int       = _define_function("baml.Bigint.to_int", "sync",  ["self"], binding_name="to_int", binding_qualname="Bigint.to_int", binding_module=__name__)
    to_int_async = _define_function("baml.Bigint.to_int", "async", ["self"], binding_name="to_int_async", binding_qualname="Bigint.to_int_async", binding_module=__name__)


class Bool(pydantic.BaseModel):
    """A boolean value — either `true` or `false`."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    random       = staticmethod(_define_function("baml.Bool.random", "sync",  [], ["rng"], binding_name="random", binding_qualname="Bool.random", binding_module=__name__))
    random_async = staticmethod(_define_function("baml.Bool.random", "async", [], ["rng"], binding_name="random_async", binding_qualname="Bool.random_async", binding_module=__name__))


class Array(pydantic.BaseModel, typing.Generic[T]):
    """
    An ordered, growable sequence of `T`.

    `Array<T>` and the `T[]` shorthand are the same type. Values come from an
    array literal (`[1, 2, 3]`) or from the `Array.filled` / `Array.generate`
    constructors below.

    Arrays are heap objects with reference semantics: binding one to a second
    name, passing it to a function, or storing it inside another container
    shares the one array, so every mutating method (`push`, `pop`, `sort_by`,
    `clear`, …) is visible through every reference to it. The methods that
    return a `T[]` instead — `concat`, `slice`, `reverse`, `map`, `filter`, … —
    build a fresh array, but they copy only one level deep: the elements are the
    same values, so a nested array, map, or class instance stays shared.

    `arr[i]` reads and `arr[i] = v` writes through the array. Both accept a
    negative index, counting back from the end (`-1` is the last element), and
    both raise `baml.panics.IndexOutOfBounds` for an index that still lands
    outside the array; `at` is the non-panicking read. Where JavaScript answers
    a failed lookup or search with `undefined` or `-1`, the methods here answer
    `null`.

    Every method that takes a callback walks a snapshot of the array taken
    before the first call, so a callback may mutate `self` without changing
    which elements are visited. An error thrown by a callback propagates
    immediately, stopping the walk and discarding any partial result.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    filled       = staticmethod(_define_function("baml.Array.filled", "sync",  ["length", "value"], binding_name="filled", binding_qualname="Array.filled", binding_module=__name__))
    filled_async = staticmethod(_define_function("baml.Array.filled", "async", ["length", "value"], binding_name="filled_async", binding_qualname="Array.filled_async", binding_module=__name__))
    generate       = staticmethod(_define_function("baml.Array.generate", "sync",  ["length", "f"], binding_name="generate", binding_qualname="Array.generate", binding_module=__name__, type_params=["E"]))
    generate_async = staticmethod(_define_function("baml.Array.generate", "async", ["length", "f"], binding_name="generate_async", binding_qualname="Array.generate_async", binding_module=__name__, type_params=["E"]))
    length       = _define_function("baml.Array.length", "sync",  ["self"], binding_name="length", binding_qualname="Array.length", binding_module=__name__, class_type_params=["T"])
    length_async = _define_function("baml.Array.length", "async", ["self"], binding_name="length_async", binding_qualname="Array.length_async", binding_module=__name__, class_type_params=["T"])
    at       = _define_function("baml.Array.at", "sync",  ["self", "index"], binding_name="at", binding_qualname="Array.at", binding_module=__name__, class_type_params=["T"])
    at_async = _define_function("baml.Array.at", "async", ["self", "index"], binding_name="at_async", binding_qualname="Array.at_async", binding_module=__name__, class_type_params=["T"])
    push       = _define_function("baml.Array.push", "sync",  ["self", "item"], binding_name="push", binding_qualname="Array.push", binding_module=__name__, class_type_params=["T"])
    push_async = _define_function("baml.Array.push", "async", ["self", "item"], binding_name="push_async", binding_qualname="Array.push_async", binding_module=__name__, class_type_params=["T"])
    pop       = _define_function("baml.Array.pop", "sync",  ["self"], binding_name="pop", binding_qualname="Array.pop", binding_module=__name__, class_type_params=["T"])
    pop_async = _define_function("baml.Array.pop", "async", ["self"], binding_name="pop_async", binding_qualname="Array.pop_async", binding_module=__name__, class_type_params=["T"])
    remove_at       = _define_function("baml.Array.remove_at", "sync",  ["self", "index"], binding_name="remove_at", binding_qualname="Array.remove_at", binding_module=__name__, class_type_params=["T"])
    remove_at_async = _define_function("baml.Array.remove_at", "async", ["self", "index"], binding_name="remove_at_async", binding_qualname="Array.remove_at_async", binding_module=__name__, class_type_params=["T"])
    concat       = _define_function("baml.Array.concat", "sync",  ["self", "other"], binding_name="concat", binding_qualname="Array.concat", binding_module=__name__, class_type_params=["T"])
    concat_async = _define_function("baml.Array.concat", "async", ["self", "other"], binding_name="concat_async", binding_qualname="Array.concat_async", binding_module=__name__, class_type_params=["T"])
    for_each       = _define_function("baml.Array.for_each", "sync",  ["self", "fn"], binding_name="for_each", binding_qualname="Array.for_each", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    for_each_async = _define_function("baml.Array.for_each", "async", ["self", "fn"], binding_name="for_each_async", binding_qualname="Array.for_each_async", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    filter       = _define_function("baml.Array.filter", "sync",  ["self", "predicate"], binding_name="filter", binding_qualname="Array.filter", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    filter_async = _define_function("baml.Array.filter", "async", ["self", "predicate"], binding_name="filter_async", binding_qualname="Array.filter_async", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    filter_map       = _define_function("baml.Array.filter_map", "sync",  ["self", "fn"], binding_name="filter_map", binding_qualname="Array.filter_map", binding_module=__name__, type_params=["U", "E"], class_type_params=["T"])
    filter_map_async = _define_function("baml.Array.filter_map", "async", ["self", "fn"], binding_name="filter_map_async", binding_qualname="Array.filter_map_async", binding_module=__name__, type_params=["U", "E"], class_type_params=["T"])
    reverse       = _define_function("baml.Array.reverse", "sync",  ["self"], binding_name="reverse", binding_qualname="Array.reverse", binding_module=__name__, class_type_params=["T"])
    reverse_async = _define_function("baml.Array.reverse", "async", ["self"], binding_name="reverse_async", binding_qualname="Array.reverse_async", binding_module=__name__, class_type_params=["T"])
    sort_by       = _define_function("baml.Array.sort_by", "sync",  ["self", "compare"], binding_name="sort_by", binding_qualname="Array.sort_by", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    sort_by_async = _define_function("baml.Array.sort_by", "async", ["self", "compare"], binding_name="sort_by_async", binding_qualname="Array.sort_by_async", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    sort_by_key       = _define_function("baml.Array.sort_by_key", "sync",  ["self", "key"], binding_name="sort_by_key", binding_qualname="Array.sort_by_key", binding_module=__name__, type_params=["U", "E"], class_type_params=["T"])
    sort_by_key_async = _define_function("baml.Array.sort_by_key", "async", ["self", "key"], binding_name="sort_by_key_async", binding_qualname="Array.sort_by_key_async", binding_module=__name__, type_params=["U", "E"], class_type_params=["T"])
    slice       = _define_function("baml.Array.slice", "sync",  ["self", "start", "end"], binding_name="slice", binding_qualname="Array.slice", binding_module=__name__, class_type_params=["T"])
    slice_async = _define_function("baml.Array.slice", "async", ["self", "start", "end"], binding_name="slice_async", binding_qualname="Array.slice_async", binding_module=__name__, class_type_params=["T"])
    join       = _define_function("baml.Array.join", "sync",  ["self", "separator"], binding_name="join", binding_qualname="Array.join", binding_module=__name__, class_type_params=["T"])
    join_async = _define_function("baml.Array.join", "async", ["self", "separator"], binding_name="join_async", binding_qualname="Array.join_async", binding_module=__name__, class_type_params=["T"])
    map       = _define_function("baml.Array.map", "sync",  ["self", "f"], binding_name="map", binding_qualname="Array.map", binding_module=__name__, type_params=["U", "E"], class_type_params=["T"])
    map_async = _define_function("baml.Array.map", "async", ["self", "f"], binding_name="map_async", binding_qualname="Array.map_async", binding_module=__name__, type_params=["U", "E"], class_type_params=["T"])
    some       = _define_function("baml.Array.some", "sync",  ["self", "predicate"], binding_name="some", binding_qualname="Array.some", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    some_async = _define_function("baml.Array.some", "async", ["self", "predicate"], binding_name="some_async", binding_qualname="Array.some_async", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    every       = _define_function("baml.Array.every", "sync",  ["self", "predicate"], binding_name="every", binding_qualname="Array.every", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    every_async = _define_function("baml.Array.every", "async", ["self", "predicate"], binding_name="every_async", binding_qualname="Array.every_async", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    find       = _define_function("baml.Array.find", "sync",  ["self", "predicate"], binding_name="find", binding_qualname="Array.find", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    find_async = _define_function("baml.Array.find", "async", ["self", "predicate"], binding_name="find_async", binding_qualname="Array.find_async", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    find_index       = _define_function("baml.Array.find_index", "sync",  ["self", "predicate"], binding_name="find_index", binding_qualname="Array.find_index", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    find_index_async = _define_function("baml.Array.find_index", "async", ["self", "predicate"], binding_name="find_index_async", binding_qualname="Array.find_index_async", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    find_last       = _define_function("baml.Array.find_last", "sync",  ["self", "predicate"], binding_name="find_last", binding_qualname="Array.find_last", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    find_last_async = _define_function("baml.Array.find_last", "async", ["self", "predicate"], binding_name="find_last_async", binding_qualname="Array.find_last_async", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    find_last_index       = _define_function("baml.Array.find_last_index", "sync",  ["self", "predicate"], binding_name="find_last_index", binding_qualname="Array.find_last_index", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    find_last_index_async = _define_function("baml.Array.find_last_index", "async", ["self", "predicate"], binding_name="find_last_index_async", binding_qualname="Array.find_last_index_async", binding_module=__name__, type_params=["E"], class_type_params=["T"])
    includes       = _define_function("baml.Array.includes", "sync",  ["self", "item"], binding_name="includes", binding_qualname="Array.includes", binding_module=__name__, class_type_params=["T"])
    includes_async = _define_function("baml.Array.includes", "async", ["self", "item"], binding_name="includes_async", binding_qualname="Array.includes_async", binding_module=__name__, class_type_params=["T"])
    index_of       = _define_function("baml.Array.index_of", "sync",  ["self", "item"], binding_name="index_of", binding_qualname="Array.index_of", binding_module=__name__, class_type_params=["T"])
    index_of_async = _define_function("baml.Array.index_of", "async", ["self", "item"], binding_name="index_of_async", binding_qualname="Array.index_of_async", binding_module=__name__, class_type_params=["T"])
    last_index_of       = _define_function("baml.Array.last_index_of", "sync",  ["self", "item"], binding_name="last_index_of", binding_qualname="Array.last_index_of", binding_module=__name__, class_type_params=["T"])
    last_index_of_async = _define_function("baml.Array.last_index_of", "async", ["self", "item"], binding_name="last_index_of_async", binding_qualname="Array.last_index_of_async", binding_module=__name__, class_type_params=["T"])
    reduce       = _define_function("baml.Array.reduce", "sync",  ["self", "reducer", "initial"], binding_name="reduce", binding_qualname="Array.reduce", binding_module=__name__, type_params=["A", "E"], class_type_params=["T"])
    reduce_async = _define_function("baml.Array.reduce", "async", ["self", "reducer", "initial"], binding_name="reduce_async", binding_qualname="Array.reduce_async", binding_module=__name__, type_params=["A", "E"], class_type_params=["T"])
    flat_map       = _define_function("baml.Array.flat_map", "sync",  ["self", "f"], binding_name="flat_map", binding_qualname="Array.flat_map", binding_module=__name__, type_params=["U", "E"], class_type_params=["T"])
    flat_map_async = _define_function("baml.Array.flat_map", "async", ["self", "f"], binding_name="flat_map_async", binding_qualname="Array.flat_map_async", binding_module=__name__, type_params=["U", "E"], class_type_params=["T"])
    clear       = _define_function("baml.Array.clear", "sync",  ["self"], binding_name="clear", binding_qualname="Array.clear", binding_module=__name__, class_type_params=["T"])
    clear_async = _define_function("baml.Array.clear", "async", ["self"], binding_name="clear_async", binding_qualname="Array.clear_async", binding_module=__name__, class_type_params=["T"])
    shift       = _define_function("baml.Array.shift", "sync",  ["self"], binding_name="shift", binding_qualname="Array.shift", binding_module=__name__, class_type_params=["T"])
    shift_async = _define_function("baml.Array.shift", "async", ["self"], binding_name="shift_async", binding_qualname="Array.shift_async", binding_module=__name__, class_type_params=["T"])
    unshift       = _define_function("baml.Array.unshift", "sync",  ["self", "item"], binding_name="unshift", binding_qualname="Array.unshift", binding_module=__name__, class_type_params=["T"])
    unshift_async = _define_function("baml.Array.unshift", "async", ["self", "item"], binding_name="unshift_async", binding_qualname="Array.unshift_async", binding_module=__name__, class_type_params=["T"])
    insert       = _define_function("baml.Array.insert", "sync",  ["self", "item", "idx"], binding_name="insert", binding_qualname="Array.insert", binding_module=__name__, class_type_params=["T"])
    insert_async = _define_function("baml.Array.insert", "async", ["self", "item", "idx"], binding_name="insert_async", binding_qualname="Array.insert_async", binding_module=__name__, class_type_params=["T"])
    splice       = _define_function("baml.Array.splice", "sync",  ["self", "start", "count", "replace"], binding_name="splice", binding_qualname="Array.splice", binding_module=__name__, class_type_params=["T"])
    splice_async = _define_function("baml.Array.splice", "async", ["self", "start", "count", "replace"], binding_name="splice_async", binding_qualname="Array.splice_async", binding_module=__name__, class_type_params=["T"])


class Map(pydantic.BaseModel, typing.Generic[K, V]):
    """
    An insertion-ordered collection of key-value pairs.

    `Map<K, V>` is spelled `map<K, V>` in type position. `K` must be `string` —
    the compiler rejects any other key type — so the type parameter exists for
    uniformity rather than choice; convert other keys with `.to_string()` first.

    Iteration order is the order in which keys were *first* inserted: `keys()`
    and `values()` follow it, `set` on an existing key keeps that key's original
    position, and `delete` preserves the order of the entries that remain. This
    is how JavaScript's
    [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
    and Python's `dict` behave — not the arbitrary order of a hash map.

    Like arrays, maps are heap objects with reference semantics: a map passed to
    a function or stored in another container is shared, and every mutating
    method (`set`, `delete`, `clear`, …) is visible through every reference.

    `m[key]` reads and `m[key] = v` writes through the map. Reading a key that
    is not present raises `baml.panics.MapKeyNotFound`; writing one inserts it
    at the end. `get` is the non-panicking read.

    When `V` is nullable, a `null` returned by `get`, `set` or `delete` is
    ambiguous between "no such key" and "the key's value is `null`". `has` is
    the way to tell the two apart.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    length       = _define_function("baml.Map.length", "sync",  ["self"], binding_name="length", binding_qualname="Map.length", binding_module=__name__, class_type_params=["K", "V"])
    length_async = _define_function("baml.Map.length", "async", ["self"], binding_name="length_async", binding_qualname="Map.length_async", binding_module=__name__, class_type_params=["K", "V"])
    has       = _define_function("baml.Map.has", "sync",  ["self", "key"], binding_name="has", binding_qualname="Map.has", binding_module=__name__, class_type_params=["K", "V"])
    has_async = _define_function("baml.Map.has", "async", ["self", "key"], binding_name="has_async", binding_qualname="Map.has_async", binding_module=__name__, class_type_params=["K", "V"])
    keys       = _define_function("baml.Map.keys", "sync",  ["self"], binding_name="keys", binding_qualname="Map.keys", binding_module=__name__, class_type_params=["K", "V"])
    keys_async = _define_function("baml.Map.keys", "async", ["self"], binding_name="keys_async", binding_qualname="Map.keys_async", binding_module=__name__, class_type_params=["K", "V"])
    values       = _define_function("baml.Map.values", "sync",  ["self"], binding_name="values", binding_qualname="Map.values", binding_module=__name__, class_type_params=["K", "V"])
    values_async = _define_function("baml.Map.values", "async", ["self"], binding_name="values_async", binding_qualname="Map.values_async", binding_module=__name__, class_type_params=["K", "V"])
    set       = _define_function("baml.Map.set", "sync",  ["self", "key", "value"], binding_name="set", binding_qualname="Map.set", binding_module=__name__, class_type_params=["K", "V"])
    set_async = _define_function("baml.Map.set", "async", ["self", "key", "value"], binding_name="set_async", binding_qualname="Map.set_async", binding_module=__name__, class_type_params=["K", "V"])
    get       = _define_function("baml.Map.get", "sync",  ["self", "key"], binding_name="get", binding_qualname="Map.get", binding_module=__name__, class_type_params=["K", "V"])
    get_async = _define_function("baml.Map.get", "async", ["self", "key"], binding_name="get_async", binding_qualname="Map.get_async", binding_module=__name__, class_type_params=["K", "V"])
    delete       = _define_function("baml.Map.delete", "sync",  ["self", "key"], binding_name="delete", binding_qualname="Map.delete", binding_module=__name__, class_type_params=["K", "V"])
    delete_async = _define_function("baml.Map.delete", "async", ["self", "key"], binding_name="delete_async", binding_qualname="Map.delete_async", binding_module=__name__, class_type_params=["K", "V"])
    get_or_insert       = _define_function("baml.Map.get_or_insert", "sync",  ["self", "key", "default"], binding_name="get_or_insert", binding_qualname="Map.get_or_insert", binding_module=__name__, class_type_params=["K", "V"])
    get_or_insert_async = _define_function("baml.Map.get_or_insert", "async", ["self", "key", "default"], binding_name="get_or_insert_async", binding_qualname="Map.get_or_insert_async", binding_module=__name__, class_type_params=["K", "V"])
    clear       = _define_function("baml.Map.clear", "sync",  ["self"], binding_name="clear", binding_qualname="Map.clear", binding_module=__name__, class_type_params=["K", "V"])
    clear_async = _define_function("baml.Map.clear", "async", ["self"], binding_name="clear_async", binding_qualname="Map.clear_async", binding_module=__name__, class_type_params=["K", "V"])


_sum_int       = _define_function("baml._sum_int", "sync",  ["values"], binding_name="_sum_int", binding_qualname="_sum_int", binding_module=__name__)
_sum_int_async = _define_function("baml._sum_int", "async", ["values"], binding_name="_sum_int_async", binding_qualname="_sum_int_async", binding_module=__name__)


_sum_float       = _define_function("baml._sum_float", "sync",  ["values"], binding_name="_sum_float", binding_qualname="_sum_float", binding_module=__name__)
_sum_float_async = _define_function("baml._sum_float", "async", ["values"], binding_name="_sum_float_async", binding_qualname="_sum_float_async", binding_module=__name__)


_median_float       = _define_function("baml._median_float", "sync",  ["values"], binding_name="_median_float", binding_qualname="_median_float", binding_module=__name__)
_median_float.__doc__ = """Raises:
    InvalidArgument"""
_median_float_async = _define_function("baml._median_float", "async", ["values"], binding_name="_median_float_async", binding_qualname="_median_float_async", binding_module=__name__)
_median_float_async.__doc__ = """Raises:
    InvalidArgument"""


_to_string_default       = _define_function("baml._to_string_default", "sync",  ["value"], binding_name="_to_string_default", binding_qualname="_to_string_default", binding_module=__name__, type_params=["T"])
_to_string_default_async = _define_function("baml._to_string_default", "async", ["value"], binding_name="_to_string_default_async", binding_qualname="_to_string_default_async", binding_module=__name__, type_params=["T"])


_cleanup_begin       = _define_function("baml._cleanup_begin", "sync",  ["value"], binding_name="_cleanup_begin", binding_qualname="_cleanup_begin", binding_module=__name__, type_params=["T"])
_cleanup_begin_async = _define_function("baml._cleanup_begin", "async", ["value"], binding_name="_cleanup_begin_async", binding_qualname="_cleanup_begin_async", binding_module=__name__, type_params=["T"])


_to_json_default       = _define_function("baml._to_json_default", "sync",  ["value"], binding_name="_to_json_default", binding_qualname="_to_json_default", binding_module=__name__, type_params=["T"])
_to_json_default.__doc__ = """Raises:
    SerializationError"""
_to_json_default_async = _define_function("baml._to_json_default", "async", ["value"], binding_name="_to_json_default_async", binding_qualname="_to_json_default_async", binding_module=__name__, type_params=["T"])
_to_json_default_async.__doc__ = """Raises:
    SerializationError"""


_to_json_shim       = _define_function("baml._to_json_shim", "sync",  ["value"], binding_name="_to_json_shim", binding_qualname="_to_json_shim", binding_module=__name__, type_params=["T"])
_to_json_shim.__doc__ = """Raises:
    SerializationError"""
_to_json_shim_async = _define_function("baml._to_json_shim", "async", ["value"], binding_name="_to_json_shim_async", binding_qualname="_to_json_shim_async", binding_module=__name__, type_params=["T"])
_to_json_shim_async.__doc__ = """Raises:
    SerializationError"""


_from_json_shim       = _define_function("baml._from_json_shim", "sync",  ["j"], binding_name="_from_json_shim", binding_qualname="_from_json_shim", binding_module=__name__, type_params=["T"])
_from_json_shim.__doc__ = """Raises:
    DecodeError"""
_from_json_shim_async = _define_function("baml._from_json_shim", "async", ["j"], binding_name="_from_json_shim_async", binding_qualname="_from_json_shim_async", binding_module=__name__, type_params=["T"])
_from_json_shim_async.__doc__ = """Raises:
    DecodeError"""


deep_copy       = _define_function("baml.deep_copy", "sync",  ["value"], binding_name="deep_copy", binding_qualname="deep_copy", binding_module=__name__, type_params=["T"])
deep_copy_async = _define_function("baml.deep_copy", "async", ["value"], binding_name="deep_copy_async", binding_qualname="deep_copy_async", binding_module=__name__, type_params=["T"])


class TaggedString(pydantic.BaseModel):
    """
    The structured value a tagged template literal produces.

    A tagged call site `` tag`…` `` lowers to
    `tag(body = () -> TaggedString { … })`; running `body()` returns this
    struct. Literals and values alternate, beginning and ending with a literal,
    so `parts.length == values.length + 1` — an empty string fills the leading
    or trailing slot when the template starts or ends with an interpolation.
    See BEP-049 §10.

    Attributes:
        parts: Literal text segments between interpolations, in source order.
        values: Interpolated values, in source order. Each entry has the type of its
            `${expr}` site, so the array is heterogeneous; tags inspect element
            types at runtime.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    parts: typing.List[str]
    values: typing.List[typing.Any]


class Float(pydantic.BaseModel):
    """
    A 64-bit IEEE-754 floating-point number.

    Arithmetic follows IEEE-754 throughout, so `float` never panics. Division
    by zero has an answer: `1.0 / 0.0` is `inf` and `0.0 / 0.0` is `NaN`, as in
    JavaScript. `int` and `bigint` have no value to give and panic instead.

    `inf` and `NaN` also come from `float.inf()` and `float.nan()`, from
    overflow (`1e308 * 10.0` is `inf`), and from other invalid operations
    (`(-1.0).sqrt()` is `NaN`).

    Neither has a JSON representation, so `baml.json.from` renders NaN and both
    infinities as `null`.

    Comparison departs from raw IEEE: `==` is reflexive and `<`/`<=`/`>`/`>=`
    are a *total* order, with NaN a single value ordered above every number
    (`-inf < …reals… < +inf < NaN`) — see `baml.ops.Compare for float`.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    parse       = staticmethod(_define_function("baml.Float.parse", "sync",  ["text"], binding_name="parse", binding_qualname="Float.parse", binding_module=__name__))
    parse_async = staticmethod(_define_function("baml.Float.parse", "async", ["text"], binding_name="parse_async", binding_qualname="Float.parse_async", binding_module=__name__))
    random       = staticmethod(_define_function("baml.Float.random", "sync",  [], ["rng"], binding_name="random", binding_qualname="Float.random", binding_module=__name__))
    random_async = staticmethod(_define_function("baml.Float.random", "async", [], ["rng"], binding_name="random_async", binding_qualname="Float.random_async", binding_module=__name__))
    _unit_from_draw_       = staticmethod(_define_function("baml.Float._unit_from_draw", "sync",  ["draw"], binding_name="_unit_from_draw_", binding_qualname="Float._unit_from_draw_", binding_module=__name__))
    _unit_from_draw__async = staticmethod(_define_function("baml.Float._unit_from_draw", "async", ["draw"], binding_name="_unit_from_draw__async", binding_qualname="Float._unit_from_draw__async", binding_module=__name__))
    pi       = staticmethod(_define_function("baml.Float.pi", "sync",  [], binding_name="pi", binding_qualname="Float.pi", binding_module=__name__))
    pi_async = staticmethod(_define_function("baml.Float.pi", "async", [], binding_name="pi_async", binding_qualname="Float.pi_async", binding_module=__name__))
    e       = staticmethod(_define_function("baml.Float.e", "sync",  [], binding_name="e", binding_qualname="Float.e", binding_module=__name__))
    e_async = staticmethod(_define_function("baml.Float.e", "async", [], binding_name="e_async", binding_qualname="Float.e_async", binding_module=__name__))
    golden_ratio       = staticmethod(_define_function("baml.Float.golden_ratio", "sync",  [], binding_name="golden_ratio", binding_qualname="Float.golden_ratio", binding_module=__name__))
    golden_ratio_async = staticmethod(_define_function("baml.Float.golden_ratio", "async", [], binding_name="golden_ratio_async", binding_qualname="Float.golden_ratio_async", binding_module=__name__))
    nan       = staticmethod(_define_function("baml.Float.nan", "sync",  [], binding_name="nan", binding_qualname="Float.nan", binding_module=__name__))
    nan_async = staticmethod(_define_function("baml.Float.nan", "async", [], binding_name="nan_async", binding_qualname="Float.nan_async", binding_module=__name__))
    inf       = staticmethod(_define_function("baml.Float.inf", "sync",  [], binding_name="inf", binding_qualname="Float.inf", binding_module=__name__))
    inf_async = staticmethod(_define_function("baml.Float.inf", "async", [], binding_name="inf_async", binding_qualname="Float.inf_async", binding_module=__name__))
    max_finite       = staticmethod(_define_function("baml.Float.max_finite", "sync",  [], binding_name="max_finite", binding_qualname="Float.max_finite", binding_module=__name__))
    max_finite_async = staticmethod(_define_function("baml.Float.max_finite", "async", [], binding_name="max_finite_async", binding_qualname="Float.max_finite_async", binding_module=__name__))
    min_finite       = staticmethod(_define_function("baml.Float.min_finite", "sync",  [], binding_name="min_finite", binding_qualname="Float.min_finite", binding_module=__name__))
    min_finite_async = staticmethod(_define_function("baml.Float.min_finite", "async", [], binding_name="min_finite_async", binding_qualname="Float.min_finite_async", binding_module=__name__))
    epsilon       = staticmethod(_define_function("baml.Float.epsilon", "sync",  [], binding_name="epsilon", binding_qualname="Float.epsilon", binding_module=__name__))
    epsilon_async = staticmethod(_define_function("baml.Float.epsilon", "async", [], binding_name="epsilon_async", binding_qualname="Float.epsilon_async", binding_module=__name__))
    is_nan       = _define_function("baml.Float.is_nan", "sync",  ["self"], binding_name="is_nan", binding_qualname="Float.is_nan", binding_module=__name__)
    is_nan_async = _define_function("baml.Float.is_nan", "async", ["self"], binding_name="is_nan_async", binding_qualname="Float.is_nan_async", binding_module=__name__)
    is_infinite       = _define_function("baml.Float.is_infinite", "sync",  ["self"], binding_name="is_infinite", binding_qualname="Float.is_infinite", binding_module=__name__)
    is_infinite_async = _define_function("baml.Float.is_infinite", "async", ["self"], binding_name="is_infinite_async", binding_qualname="Float.is_infinite_async", binding_module=__name__)
    is_finite       = _define_function("baml.Float.is_finite", "sync",  ["self"], binding_name="is_finite", binding_qualname="Float.is_finite", binding_module=__name__)
    is_finite_async = _define_function("baml.Float.is_finite", "async", ["self"], binding_name="is_finite_async", binding_qualname="Float.is_finite_async", binding_module=__name__)
    abs       = _define_function("baml.Float.abs", "sync",  ["self"], binding_name="abs", binding_qualname="Float.abs", binding_module=__name__)
    abs_async = _define_function("baml.Float.abs", "async", ["self"], binding_name="abs_async", binding_qualname="Float.abs_async", binding_module=__name__)
    signum       = _define_function("baml.Float.signum", "sync",  ["self"], binding_name="signum", binding_qualname="Float.signum", binding_module=__name__)
    signum_async = _define_function("baml.Float.signum", "async", ["self"], binding_name="signum_async", binding_qualname="Float.signum_async", binding_module=__name__)
    floor       = _define_function("baml.Float.floor", "sync",  ["self"], binding_name="floor", binding_qualname="Float.floor", binding_module=__name__)
    floor_async = _define_function("baml.Float.floor", "async", ["self"], binding_name="floor_async", binding_qualname="Float.floor_async", binding_module=__name__)
    ceil       = _define_function("baml.Float.ceil", "sync",  ["self"], binding_name="ceil", binding_qualname="Float.ceil", binding_module=__name__)
    ceil_async = _define_function("baml.Float.ceil", "async", ["self"], binding_name="ceil_async", binding_qualname="Float.ceil_async", binding_module=__name__)
    round       = _define_function("baml.Float.round", "sync",  ["self"], binding_name="round", binding_qualname="Float.round", binding_module=__name__)
    round_async = _define_function("baml.Float.round", "async", ["self"], binding_name="round_async", binding_qualname="Float.round_async", binding_module=__name__)
    trunc       = _define_function("baml.Float.trunc", "sync",  ["self"], binding_name="trunc", binding_qualname="Float.trunc", binding_module=__name__)
    trunc_async = _define_function("baml.Float.trunc", "async", ["self"], binding_name="trunc_async", binding_qualname="Float.trunc_async", binding_module=__name__)
    fract       = _define_function("baml.Float.fract", "sync",  ["self"], binding_name="fract", binding_qualname="Float.fract", binding_module=__name__)
    fract_async = _define_function("baml.Float.fract", "async", ["self"], binding_name="fract_async", binding_qualname="Float.fract_async", binding_module=__name__)
    ifloor       = _define_function("baml.Float.ifloor", "sync",  ["self"], binding_name="ifloor", binding_qualname="Float.ifloor", binding_module=__name__)
    ifloor_async = _define_function("baml.Float.ifloor", "async", ["self"], binding_name="ifloor_async", binding_qualname="Float.ifloor_async", binding_module=__name__)
    iceil       = _define_function("baml.Float.iceil", "sync",  ["self"], binding_name="iceil", binding_qualname="Float.iceil", binding_module=__name__)
    iceil_async = _define_function("baml.Float.iceil", "async", ["self"], binding_name="iceil_async", binding_qualname="Float.iceil_async", binding_module=__name__)
    iround       = _define_function("baml.Float.iround", "sync",  ["self"], binding_name="iround", binding_qualname="Float.iround", binding_module=__name__)
    iround_async = _define_function("baml.Float.iround", "async", ["self"], binding_name="iround_async", binding_qualname="Float.iround_async", binding_module=__name__)
    itrunc       = _define_function("baml.Float.itrunc", "sync",  ["self"], binding_name="itrunc", binding_qualname="Float.itrunc", binding_module=__name__)
    itrunc_async = _define_function("baml.Float.itrunc", "async", ["self"], binding_name="itrunc_async", binding_qualname="Float.itrunc_async", binding_module=__name__)
    sqrt       = _define_function("baml.Float.sqrt", "sync",  ["self"], binding_name="sqrt", binding_qualname="Float.sqrt", binding_module=__name__)
    sqrt_async = _define_function("baml.Float.sqrt", "async", ["self"], binding_name="sqrt_async", binding_qualname="Float.sqrt_async", binding_module=__name__)
    pow       = _define_function("baml.Float.pow", "sync",  ["self", "exp"], binding_name="pow", binding_qualname="Float.pow", binding_module=__name__)
    pow_async = _define_function("baml.Float.pow", "async", ["self", "exp"], binding_name="pow_async", binding_qualname="Float.pow_async", binding_module=__name__)
    log       = _define_function("baml.Float.log", "sync",  ["self", "base"], binding_name="log", binding_qualname="Float.log", binding_module=__name__)
    log_async = _define_function("baml.Float.log", "async", ["self", "base"], binding_name="log_async", binding_qualname="Float.log_async", binding_module=__name__)
    exp       = _define_function("baml.Float.exp", "sync",  ["self"], binding_name="exp", binding_qualname="Float.exp", binding_module=__name__)
    exp_async = _define_function("baml.Float.exp", "async", ["self"], binding_name="exp_async", binding_qualname="Float.exp_async", binding_module=__name__)
    ln       = _define_function("baml.Float.ln", "sync",  ["self"], binding_name="ln", binding_qualname="Float.ln", binding_module=__name__)
    ln_async = _define_function("baml.Float.ln", "async", ["self"], binding_name="ln_async", binding_qualname="Float.ln_async", binding_module=__name__)
    log2       = _define_function("baml.Float.log2", "sync",  ["self"], binding_name="log2", binding_qualname="Float.log2", binding_module=__name__)
    log2_async = _define_function("baml.Float.log2", "async", ["self"], binding_name="log2_async", binding_qualname="Float.log2_async", binding_module=__name__)
    log10       = _define_function("baml.Float.log10", "sync",  ["self"], binding_name="log10", binding_qualname="Float.log10", binding_module=__name__)
    log10_async = _define_function("baml.Float.log10", "async", ["self"], binding_name="log10_async", binding_qualname="Float.log10_async", binding_module=__name__)
    cbrt       = _define_function("baml.Float.cbrt", "sync",  ["self"], binding_name="cbrt", binding_qualname="Float.cbrt", binding_module=__name__)
    cbrt_async = _define_function("baml.Float.cbrt", "async", ["self"], binding_name="cbrt_async", binding_qualname="Float.cbrt_async", binding_module=__name__)
    hypot       = _define_function("baml.Float.hypot", "sync",  ["self", "other"], binding_name="hypot", binding_qualname="Float.hypot", binding_module=__name__)
    hypot_async = _define_function("baml.Float.hypot", "async", ["self", "other"], binding_name="hypot_async", binding_qualname="Float.hypot_async", binding_module=__name__)
    sin       = _define_function("baml.Float.sin", "sync",  ["self"], binding_name="sin", binding_qualname="Float.sin", binding_module=__name__)
    sin_async = _define_function("baml.Float.sin", "async", ["self"], binding_name="sin_async", binding_qualname="Float.sin_async", binding_module=__name__)
    cos       = _define_function("baml.Float.cos", "sync",  ["self"], binding_name="cos", binding_qualname="Float.cos", binding_module=__name__)
    cos_async = _define_function("baml.Float.cos", "async", ["self"], binding_name="cos_async", binding_qualname="Float.cos_async", binding_module=__name__)
    tan       = _define_function("baml.Float.tan", "sync",  ["self"], binding_name="tan", binding_qualname="Float.tan", binding_module=__name__)
    tan_async = _define_function("baml.Float.tan", "async", ["self"], binding_name="tan_async", binding_qualname="Float.tan_async", binding_module=__name__)
    asin       = _define_function("baml.Float.asin", "sync",  ["self"], binding_name="asin", binding_qualname="Float.asin", binding_module=__name__)
    asin_async = _define_function("baml.Float.asin", "async", ["self"], binding_name="asin_async", binding_qualname="Float.asin_async", binding_module=__name__)
    acos       = _define_function("baml.Float.acos", "sync",  ["self"], binding_name="acos", binding_qualname="Float.acos", binding_module=__name__)
    acos_async = _define_function("baml.Float.acos", "async", ["self"], binding_name="acos_async", binding_qualname="Float.acos_async", binding_module=__name__)
    atan       = _define_function("baml.Float.atan", "sync",  ["self"], binding_name="atan", binding_qualname="Float.atan", binding_module=__name__)
    atan_async = _define_function("baml.Float.atan", "async", ["self"], binding_name="atan_async", binding_qualname="Float.atan_async", binding_module=__name__)
    atan2       = _define_function("baml.Float.atan2", "sync",  ["self", "other"], binding_name="atan2", binding_qualname="Float.atan2", binding_module=__name__)
    atan2_async = _define_function("baml.Float.atan2", "async", ["self", "other"], binding_name="atan2_async", binding_qualname="Float.atan2_async", binding_module=__name__)
    sinh       = _define_function("baml.Float.sinh", "sync",  ["self"], binding_name="sinh", binding_qualname="Float.sinh", binding_module=__name__)
    sinh_async = _define_function("baml.Float.sinh", "async", ["self"], binding_name="sinh_async", binding_qualname="Float.sinh_async", binding_module=__name__)
    cosh       = _define_function("baml.Float.cosh", "sync",  ["self"], binding_name="cosh", binding_qualname="Float.cosh", binding_module=__name__)
    cosh_async = _define_function("baml.Float.cosh", "async", ["self"], binding_name="cosh_async", binding_qualname="Float.cosh_async", binding_module=__name__)
    tanh       = _define_function("baml.Float.tanh", "sync",  ["self"], binding_name="tanh", binding_qualname="Float.tanh", binding_module=__name__)
    tanh_async = _define_function("baml.Float.tanh", "async", ["self"], binding_name="tanh_async", binding_qualname="Float.tanh_async", binding_module=__name__)
    asinh       = _define_function("baml.Float.asinh", "sync",  ["self"], binding_name="asinh", binding_qualname="Float.asinh", binding_module=__name__)
    asinh_async = _define_function("baml.Float.asinh", "async", ["self"], binding_name="asinh_async", binding_qualname="Float.asinh_async", binding_module=__name__)
    acosh       = _define_function("baml.Float.acosh", "sync",  ["self"], binding_name="acosh", binding_qualname="Float.acosh", binding_module=__name__)
    acosh_async = _define_function("baml.Float.acosh", "async", ["self"], binding_name="acosh_async", binding_qualname="Float.acosh_async", binding_module=__name__)
    atanh       = _define_function("baml.Float.atanh", "sync",  ["self"], binding_name="atanh", binding_qualname="Float.atanh", binding_module=__name__)
    atanh_async = _define_function("baml.Float.atanh", "async", ["self"], binding_name="atanh_async", binding_qualname="Float.atanh_async", binding_module=__name__)
    to_radians       = _define_function("baml.Float.to_radians", "sync",  ["self"], binding_name="to_radians", binding_qualname="Float.to_radians", binding_module=__name__)
    to_radians_async = _define_function("baml.Float.to_radians", "async", ["self"], binding_name="to_radians_async", binding_qualname="Float.to_radians_async", binding_module=__name__)
    to_degrees       = _define_function("baml.Float.to_degrees", "sync",  ["self"], binding_name="to_degrees", binding_qualname="Float.to_degrees", binding_module=__name__)
    to_degrees_async = _define_function("baml.Float.to_degrees", "async", ["self"], binding_name="to_degrees_async", binding_qualname="Float.to_degrees_async", binding_module=__name__)


_trunc_to_int       = _define_function("baml._trunc_to_int", "sync",  ["value"], binding_name="_trunc_to_int", binding_qualname="_trunc_to_int", binding_module=__name__)
_trunc_to_int_async = _define_function("baml._trunc_to_int", "async", ["value"], binding_name="_trunc_to_int_async", binding_qualname="_trunc_to_int_async", binding_module=__name__)


class Int(pydantic.BaseModel):
    """
    A 63-bit signed integer, from `-2^62` (`-4_611_686_018_427_387_904`) to
    `2^62 - 1` (`4_611_686_018_427_387_903`).

    The runtime reserves one bit of a 64-bit machine word for its pointer/value
    tag, so the usable width is 63 bits rather than 64. Unlike Python's `int`,
    an `int` does not grow to fit; use `bigint` for arbitrary precision.

    Literals may be decimal (`42`), hex (`0xFF`), octal (`0o755`), or binary
    (`0b1010`), with `_` digit separators allowed (`1_000_000`).

    Bit operations such as `leading_zeros` and `count_ones` read `self` as a
    64-bit two's-complement word. The value is stored sign-extended, so those
    counts include the high sign/tag bits: `(1).leading_zeros()` is `63`, not
    `62`.

    # Panics

    Arithmetic panics rather than wrapping. These panics are catchable, but are
    not declared in `throws` clauses.

    - `baml.panics.IntegerOverflow` if `+`, `-`, `*`, `/`, or unary `-` leaves
      the `int` range.
    - `baml.panics.DivisionByZero` if the right operand of `/` or `%` is zero.
    - `baml.panics.NegativeBitShift` if the count given to `<<` or `>>` is
      negative.

    `<<` is the exception to the overflow rule: it truncates, discarding
    whatever is shifted past the 63-bit width. `1 << 62` is `int.min_value()`
    (bit 62 is the sign bit) and `1 << 63` is `0`. `>>` cannot overflow either;
    a count of 63 or more saturates to the sign, giving `0` for a non-negative
    `self` and `-1` for a negative one.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    parse       = staticmethod(_define_function("baml.Int.parse", "sync",  ["text"], binding_name="parse", binding_qualname="Int.parse", binding_module=__name__))
    parse_async = staticmethod(_define_function("baml.Int.parse", "async", ["text"], binding_name="parse_async", binding_qualname="Int.parse_async", binding_module=__name__))
    random       = staticmethod(_define_function("baml.Int.random", "sync",  ["lower", "upper"], ["rng"], binding_name="random", binding_qualname="Int.random", binding_module=__name__))
    random_async = staticmethod(_define_function("baml.Int.random", "async", ["lower", "upper"], ["rng"], binding_name="random_async", binding_qualname="Int.random_async", binding_module=__name__))
    _random_in_range_       = staticmethod(_define_function("baml.Int._random_in_range", "sync",  ["draw", "lower", "upper"], binding_name="_random_in_range_", binding_qualname="Int._random_in_range_", binding_module=__name__))
    _random_in_range__async = staticmethod(_define_function("baml.Int._random_in_range", "async", ["draw", "lower", "upper"], binding_name="_random_in_range__async", binding_qualname="Int._random_in_range__async", binding_module=__name__))
    max_value       = staticmethod(_define_function("baml.Int.max_value", "sync",  [], binding_name="max_value", binding_qualname="Int.max_value", binding_module=__name__))
    max_value_async = staticmethod(_define_function("baml.Int.max_value", "async", [], binding_name="max_value_async", binding_qualname="Int.max_value_async", binding_module=__name__))
    min_value       = staticmethod(_define_function("baml.Int.min_value", "sync",  [], binding_name="min_value", binding_qualname="Int.min_value", binding_module=__name__))
    min_value_async = staticmethod(_define_function("baml.Int.min_value", "async", [], binding_name="min_value_async", binding_qualname="Int.min_value_async", binding_module=__name__))
    abs       = _define_function("baml.Int.abs", "sync",  ["self"], binding_name="abs", binding_qualname="Int.abs", binding_module=__name__)
    abs_async = _define_function("baml.Int.abs", "async", ["self"], binding_name="abs_async", binding_qualname="Int.abs_async", binding_module=__name__)
    isqrt       = _define_function("baml.Int.isqrt", "sync",  ["self"], binding_name="isqrt", binding_qualname="Int.isqrt", binding_module=__name__)
    isqrt_async = _define_function("baml.Int.isqrt", "async", ["self"], binding_name="isqrt_async", binding_qualname="Int.isqrt_async", binding_module=__name__)
    pow       = _define_function("baml.Int.pow", "sync",  ["self", "exp"], binding_name="pow", binding_qualname="Int.pow", binding_module=__name__)
    pow_async = _define_function("baml.Int.pow", "async", ["self", "exp"], binding_name="pow_async", binding_qualname="Int.pow_async", binding_module=__name__)
    ilog       = _define_function("baml.Int.ilog", "sync",  ["self", "base"], binding_name="ilog", binding_qualname="Int.ilog", binding_module=__name__)
    ilog_async = _define_function("baml.Int.ilog", "async", ["self", "base"], binding_name="ilog_async", binding_qualname="Int.ilog_async", binding_module=__name__)
    leading_zeros       = _define_function("baml.Int.leading_zeros", "sync",  ["self"], binding_name="leading_zeros", binding_qualname="Int.leading_zeros", binding_module=__name__)
    leading_zeros_async = _define_function("baml.Int.leading_zeros", "async", ["self"], binding_name="leading_zeros_async", binding_qualname="Int.leading_zeros_async", binding_module=__name__)
    leading_ones       = _define_function("baml.Int.leading_ones", "sync",  ["self"], binding_name="leading_ones", binding_qualname="Int.leading_ones", binding_module=__name__)
    leading_ones_async = _define_function("baml.Int.leading_ones", "async", ["self"], binding_name="leading_ones_async", binding_qualname="Int.leading_ones_async", binding_module=__name__)
    trailing_zeros       = _define_function("baml.Int.trailing_zeros", "sync",  ["self"], binding_name="trailing_zeros", binding_qualname="Int.trailing_zeros", binding_module=__name__)
    trailing_zeros_async = _define_function("baml.Int.trailing_zeros", "async", ["self"], binding_name="trailing_zeros_async", binding_qualname="Int.trailing_zeros_async", binding_module=__name__)
    trailing_ones       = _define_function("baml.Int.trailing_ones", "sync",  ["self"], binding_name="trailing_ones", binding_qualname="Int.trailing_ones", binding_module=__name__)
    trailing_ones_async = _define_function("baml.Int.trailing_ones", "async", ["self"], binding_name="trailing_ones_async", binding_qualname="Int.trailing_ones_async", binding_module=__name__)
    count_zeros       = _define_function("baml.Int.count_zeros", "sync",  ["self"], binding_name="count_zeros", binding_qualname="Int.count_zeros", binding_module=__name__)
    count_zeros_async = _define_function("baml.Int.count_zeros", "async", ["self"], binding_name="count_zeros_async", binding_qualname="Int.count_zeros_async", binding_module=__name__)
    count_ones       = _define_function("baml.Int.count_ones", "sync",  ["self"], binding_name="count_ones", binding_qualname="Int.count_ones", binding_module=__name__)
    count_ones_async = _define_function("baml.Int.count_ones", "async", ["self"], binding_name="count_ones_async", binding_qualname="Int.count_ones_async", binding_module=__name__)


class Null(pydantic.BaseModel):
    """The type of `null`, representing the absence of a value."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )


_is_primitive_array       = _define_function("baml._is_primitive_array", "sync",  ["arr"], binding_name="_is_primitive_array", binding_qualname="_is_primitive_array", binding_module=__name__, type_params=["T"])
_is_primitive_array_async = _define_function("baml._is_primitive_array", "async", ["arr"], binding_name="_is_primitive_array_async", binding_qualname="_is_primitive_array_async", binding_module=__name__, type_params=["T"])


_rust_sort       = _define_function("baml._rust_sort", "sync",  ["arr"], binding_name="_rust_sort", binding_qualname="_rust_sort", binding_module=__name__, type_params=["A"])
_rust_sort_async = _define_function("baml._rust_sort", "async", ["arr"], binding_name="_rust_sort_async", binding_qualname="_rust_sort_async", binding_module=__name__, type_params=["A"])


class String(pydantic.BaseModel):
    """
    A UTF-8 encoded string.

    Strings are immutable: every method here returns a new string rather than
    modifying `self`. Quoted strings may span multiple lines; backtick strings
    interpolate.

    Positions are **character** (Unicode code point) offsets, never byte offsets.
    `length`, `at`, `code_point_at`, `slice`, `index_of`, and `last_index_of` all
    agree with each other, and all disagree with `byte_length` as soon as one
    character takes more than one UTF-8 byte. A method taking a position also
    accepts a negative one, counting from the end. Python's `str` indexes the same
    way; JavaScript indexes by UTF-16 unit and so can cut an emoji in half.

    The `is_*` predicates ask whether **every** character has the property, so all
    of them are true on the empty string. The `is_ascii_*` family is false for any
    character at or above U+0080.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    from_       = staticmethod(_define_function("baml.String.from", "sync",  ["value"], binding_name="from_", binding_qualname="String.from_", binding_module=__name__, type_params=["T"]))
    from__async = staticmethod(_define_function("baml.String.from", "async", ["value"], binding_name="from__async", binding_qualname="String.from__async", binding_module=__name__, type_params=["T"]))
    from_utf8       = staticmethod(_define_function("baml.String.from_utf8", "sync",  ["utf8"], binding_name="from_utf8", binding_qualname="String.from_utf8", binding_module=__name__))
    from_utf8_async = staticmethod(_define_function("baml.String.from_utf8", "async", ["utf8"], binding_name="from_utf8_async", binding_qualname="String.from_utf8_async", binding_module=__name__))
    from_code_points       = staticmethod(_define_function("baml.String.from_code_points", "sync",  ["unicode"], binding_name="from_code_points", binding_qualname="String.from_code_points", binding_module=__name__))
    from_code_points_async = staticmethod(_define_function("baml.String.from_code_points", "async", ["unicode"], binding_name="from_code_points_async", binding_qualname="String.from_code_points_async", binding_module=__name__))
    length       = _define_function("baml.String.length", "sync",  ["self"], binding_name="length", binding_qualname="String.length", binding_module=__name__)
    length_async = _define_function("baml.String.length", "async", ["self"], binding_name="length_async", binding_qualname="String.length_async", binding_module=__name__)
    char_count       = _define_function("baml.String.char_count", "sync",  ["self"], binding_name="char_count", binding_qualname="String.char_count", binding_module=__name__)
    char_count_async = _define_function("baml.String.char_count", "async", ["self"], binding_name="char_count_async", binding_qualname="String.char_count_async", binding_module=__name__)
    is_empty       = _define_function("baml.String.is_empty", "sync",  ["self"], binding_name="is_empty", binding_qualname="String.is_empty", binding_module=__name__)
    is_empty_async = _define_function("baml.String.is_empty", "async", ["self"], binding_name="is_empty_async", binding_qualname="String.is_empty_async", binding_module=__name__)
    byte_length       = _define_function("baml.String.byte_length", "sync",  ["self"], binding_name="byte_length", binding_qualname="String.byte_length", binding_module=__name__)
    byte_length_async = _define_function("baml.String.byte_length", "async", ["self"], binding_name="byte_length_async", binding_qualname="String.byte_length_async", binding_module=__name__)
    to_lower_case       = _define_function("baml.String.to_lower_case", "sync",  ["self"], binding_name="to_lower_case", binding_qualname="String.to_lower_case", binding_module=__name__)
    to_lower_case_async = _define_function("baml.String.to_lower_case", "async", ["self"], binding_name="to_lower_case_async", binding_qualname="String.to_lower_case_async", binding_module=__name__)
    to_upper_case       = _define_function("baml.String.to_upper_case", "sync",  ["self"], binding_name="to_upper_case", binding_qualname="String.to_upper_case", binding_module=__name__)
    to_upper_case_async = _define_function("baml.String.to_upper_case", "async", ["self"], binding_name="to_upper_case_async", binding_qualname="String.to_upper_case_async", binding_module=__name__)
    trim       = _define_function("baml.String.trim", "sync",  ["self"], binding_name="trim", binding_qualname="String.trim", binding_module=__name__)
    trim_async = _define_function("baml.String.trim", "async", ["self"], binding_name="trim_async", binding_qualname="String.trim_async", binding_module=__name__)
    trim_start       = _define_function("baml.String.trim_start", "sync",  ["self"], binding_name="trim_start", binding_qualname="String.trim_start", binding_module=__name__)
    trim_start_async = _define_function("baml.String.trim_start", "async", ["self"], binding_name="trim_start_async", binding_qualname="String.trim_start_async", binding_module=__name__)
    trim_end       = _define_function("baml.String.trim_end", "sync",  ["self"], binding_name="trim_end", binding_qualname="String.trim_end", binding_module=__name__)
    trim_end_async = _define_function("baml.String.trim_end", "async", ["self"], binding_name="trim_end_async", binding_qualname="String.trim_end_async", binding_module=__name__)
    includes       = _define_function("baml.String.includes", "sync",  ["self", "search"], binding_name="includes", binding_qualname="String.includes", binding_module=__name__)
    includes_async = _define_function("baml.String.includes", "async", ["self", "search"], binding_name="includes_async", binding_qualname="String.includes_async", binding_module=__name__)
    starts_with       = _define_function("baml.String.starts_with", "sync",  ["self", "prefix"], binding_name="starts_with", binding_qualname="String.starts_with", binding_module=__name__)
    starts_with_async = _define_function("baml.String.starts_with", "async", ["self", "prefix"], binding_name="starts_with_async", binding_qualname="String.starts_with_async", binding_module=__name__)
    ends_with       = _define_function("baml.String.ends_with", "sync",  ["self", "suffix"], binding_name="ends_with", binding_qualname="String.ends_with", binding_module=__name__)
    ends_with_async = _define_function("baml.String.ends_with", "async", ["self", "suffix"], binding_name="ends_with_async", binding_qualname="String.ends_with_async", binding_module=__name__)
    split       = _define_function("baml.String.split", "sync",  ["self", "delimiter"], binding_name="split", binding_qualname="String.split", binding_module=__name__)
    split_async = _define_function("baml.String.split", "async", ["self", "delimiter"], binding_name="split_async", binding_qualname="String.split_async", binding_module=__name__)
    chars       = _define_function("baml.String.chars", "sync",  ["self"], binding_name="chars", binding_qualname="String.chars", binding_module=__name__)
    chars_async = _define_function("baml.String.chars", "async", ["self"], binding_name="chars_async", binding_qualname="String.chars_async", binding_module=__name__)
    lines       = _define_function("baml.String.lines", "sync",  ["self"], binding_name="lines", binding_qualname="String.lines", binding_module=__name__)
    lines_async = _define_function("baml.String.lines", "async", ["self"], binding_name="lines_async", binding_qualname="String.lines_async", binding_module=__name__)
    slice       = _define_function("baml.String.slice", "sync",  ["self", "start", "end"], binding_name="slice", binding_qualname="String.slice", binding_module=__name__)
    slice_async = _define_function("baml.String.slice", "async", ["self", "start", "end"], binding_name="slice_async", binding_qualname="String.slice_async", binding_module=__name__)
    replace       = _define_function("baml.String.replace", "sync",  ["self", "search", "replacement"], binding_name="replace", binding_qualname="String.replace", binding_module=__name__)
    replace_async = _define_function("baml.String.replace", "async", ["self", "search", "replacement"], binding_name="replace_async", binding_qualname="String.replace_async", binding_module=__name__)
    index_of       = _define_function("baml.String.index_of", "sync",  ["self", "search"], binding_name="index_of", binding_qualname="String.index_of", binding_module=__name__)
    index_of_async = _define_function("baml.String.index_of", "async", ["self", "search"], binding_name="index_of_async", binding_qualname="String.index_of_async", binding_module=__name__)
    last_index_of       = _define_function("baml.String.last_index_of", "sync",  ["self", "search"], binding_name="last_index_of", binding_qualname="String.last_index_of", binding_module=__name__)
    last_index_of_async = _define_function("baml.String.last_index_of", "async", ["self", "search"], binding_name="last_index_of_async", binding_qualname="String.last_index_of_async", binding_module=__name__)
    at       = _define_function("baml.String.at", "sync",  ["self", "index"], binding_name="at", binding_qualname="String.at", binding_module=__name__)
    at_async = _define_function("baml.String.at", "async", ["self", "index"], binding_name="at_async", binding_qualname="String.at_async", binding_module=__name__)
    code_point_at       = _define_function("baml.String.code_point_at", "sync",  ["self", "index"], binding_name="code_point_at", binding_qualname="String.code_point_at", binding_module=__name__)
    code_point_at_async = _define_function("baml.String.code_point_at", "async", ["self", "index"], binding_name="code_point_at_async", binding_qualname="String.code_point_at_async", binding_module=__name__)
    repeat       = _define_function("baml.String.repeat", "sync",  ["self", "count"], binding_name="repeat", binding_qualname="String.repeat", binding_module=__name__)
    repeat_async = _define_function("baml.String.repeat", "async", ["self", "count"], binding_name="repeat_async", binding_qualname="String.repeat_async", binding_module=__name__)
    replace_all       = _define_function("baml.String.replace_all", "sync",  ["self", "search", "replacement"], binding_name="replace_all", binding_qualname="String.replace_all", binding_module=__name__)
    replace_all_async = _define_function("baml.String.replace_all", "async", ["self", "search", "replacement"], binding_name="replace_all_async", binding_qualname="String.replace_all_async", binding_module=__name__)
    is_numeric       = _define_function("baml.String.is_numeric", "sync",  ["self"], binding_name="is_numeric", binding_qualname="String.is_numeric", binding_module=__name__)
    is_numeric_async = _define_function("baml.String.is_numeric", "async", ["self"], binding_name="is_numeric_async", binding_qualname="String.is_numeric_async", binding_module=__name__)
    is_alphabetic       = _define_function("baml.String.is_alphabetic", "sync",  ["self"], binding_name="is_alphabetic", binding_qualname="String.is_alphabetic", binding_module=__name__)
    is_alphabetic_async = _define_function("baml.String.is_alphabetic", "async", ["self"], binding_name="is_alphabetic_async", binding_qualname="String.is_alphabetic_async", binding_module=__name__)
    is_alphanumeric       = _define_function("baml.String.is_alphanumeric", "sync",  ["self"], binding_name="is_alphanumeric", binding_qualname="String.is_alphanumeric", binding_module=__name__)
    is_alphanumeric_async = _define_function("baml.String.is_alphanumeric", "async", ["self"], binding_name="is_alphanumeric_async", binding_qualname="String.is_alphanumeric_async", binding_module=__name__)
    is_uppercase       = _define_function("baml.String.is_uppercase", "sync",  ["self"], binding_name="is_uppercase", binding_qualname="String.is_uppercase", binding_module=__name__)
    is_uppercase_async = _define_function("baml.String.is_uppercase", "async", ["self"], binding_name="is_uppercase_async", binding_qualname="String.is_uppercase_async", binding_module=__name__)
    is_lowercase       = _define_function("baml.String.is_lowercase", "sync",  ["self"], binding_name="is_lowercase", binding_qualname="String.is_lowercase", binding_module=__name__)
    is_lowercase_async = _define_function("baml.String.is_lowercase", "async", ["self"], binding_name="is_lowercase_async", binding_qualname="String.is_lowercase_async", binding_module=__name__)
    is_whitespace       = _define_function("baml.String.is_whitespace", "sync",  ["self"], binding_name="is_whitespace", binding_qualname="String.is_whitespace", binding_module=__name__)
    is_whitespace_async = _define_function("baml.String.is_whitespace", "async", ["self"], binding_name="is_whitespace_async", binding_qualname="String.is_whitespace_async", binding_module=__name__)
    is_control       = _define_function("baml.String.is_control", "sync",  ["self"], binding_name="is_control", binding_qualname="String.is_control", binding_module=__name__)
    is_control_async = _define_function("baml.String.is_control", "async", ["self"], binding_name="is_control_async", binding_qualname="String.is_control_async", binding_module=__name__)
    is_graphic       = _define_function("baml.String.is_graphic", "sync",  ["self"], binding_name="is_graphic", binding_qualname="String.is_graphic", binding_module=__name__)
    is_graphic_async = _define_function("baml.String.is_graphic", "async", ["self"], binding_name="is_graphic_async", binding_qualname="String.is_graphic_async", binding_module=__name__)
    is_ascii       = _define_function("baml.String.is_ascii", "sync",  ["self"], binding_name="is_ascii", binding_qualname="String.is_ascii", binding_module=__name__)
    is_ascii_async = _define_function("baml.String.is_ascii", "async", ["self"], binding_name="is_ascii_async", binding_qualname="String.is_ascii_async", binding_module=__name__)
    is_ascii_numeric       = _define_function("baml.String.is_ascii_numeric", "sync",  ["self"], binding_name="is_ascii_numeric", binding_qualname="String.is_ascii_numeric", binding_module=__name__)
    is_ascii_numeric_async = _define_function("baml.String.is_ascii_numeric", "async", ["self"], binding_name="is_ascii_numeric_async", binding_qualname="String.is_ascii_numeric_async", binding_module=__name__)
    is_ascii_alphabetic       = _define_function("baml.String.is_ascii_alphabetic", "sync",  ["self"], binding_name="is_ascii_alphabetic", binding_qualname="String.is_ascii_alphabetic", binding_module=__name__)
    is_ascii_alphabetic_async = _define_function("baml.String.is_ascii_alphabetic", "async", ["self"], binding_name="is_ascii_alphabetic_async", binding_qualname="String.is_ascii_alphabetic_async", binding_module=__name__)
    is_ascii_alphanumeric       = _define_function("baml.String.is_ascii_alphanumeric", "sync",  ["self"], binding_name="is_ascii_alphanumeric", binding_qualname="String.is_ascii_alphanumeric", binding_module=__name__)
    is_ascii_alphanumeric_async = _define_function("baml.String.is_ascii_alphanumeric", "async", ["self"], binding_name="is_ascii_alphanumeric_async", binding_qualname="String.is_ascii_alphanumeric_async", binding_module=__name__)
    is_ascii_uppercase       = _define_function("baml.String.is_ascii_uppercase", "sync",  ["self"], binding_name="is_ascii_uppercase", binding_qualname="String.is_ascii_uppercase", binding_module=__name__)
    is_ascii_uppercase_async = _define_function("baml.String.is_ascii_uppercase", "async", ["self"], binding_name="is_ascii_uppercase_async", binding_qualname="String.is_ascii_uppercase_async", binding_module=__name__)
    is_ascii_lowercase       = _define_function("baml.String.is_ascii_lowercase", "sync",  ["self"], binding_name="is_ascii_lowercase", binding_qualname="String.is_ascii_lowercase", binding_module=__name__)
    is_ascii_lowercase_async = _define_function("baml.String.is_ascii_lowercase", "async", ["self"], binding_name="is_ascii_lowercase_async", binding_qualname="String.is_ascii_lowercase_async", binding_module=__name__)
    is_ascii_whitespace       = _define_function("baml.String.is_ascii_whitespace", "sync",  ["self"], binding_name="is_ascii_whitespace", binding_qualname="String.is_ascii_whitespace", binding_module=__name__)
    is_ascii_whitespace_async = _define_function("baml.String.is_ascii_whitespace", "async", ["self"], binding_name="is_ascii_whitespace_async", binding_qualname="String.is_ascii_whitespace_async", binding_module=__name__)
    is_ascii_control       = _define_function("baml.String.is_ascii_control", "sync",  ["self"], binding_name="is_ascii_control", binding_qualname="String.is_ascii_control", binding_module=__name__)
    is_ascii_control_async = _define_function("baml.String.is_ascii_control", "async", ["self"], binding_name="is_ascii_control_async", binding_qualname="String.is_ascii_control_async", binding_module=__name__)
    is_ascii_graphic       = _define_function("baml.String.is_ascii_graphic", "sync",  ["self"], binding_name="is_ascii_graphic", binding_qualname="String.is_ascii_graphic", binding_module=__name__)
    is_ascii_graphic_async = _define_function("baml.String.is_ascii_graphic", "async", ["self"], binding_name="is_ascii_graphic_async", binding_qualname="String.is_ascii_graphic_async", binding_module=__name__)
    is_ascii_hex       = _define_function("baml.String.is_ascii_hex", "sync",  ["self"], binding_name="is_ascii_hex", binding_qualname="String.is_ascii_hex", binding_module=__name__)
    is_ascii_hex_async = _define_function("baml.String.is_ascii_hex", "async", ["self"], binding_name="is_ascii_hex_async", binding_qualname="String.is_ascii_hex_async", binding_module=__name__)
    to_utf8       = _define_function("baml.String.to_utf8", "sync",  ["self"], binding_name="to_utf8", binding_qualname="String.to_utf8", binding_module=__name__)
    to_utf8_async = _define_function("baml.String.to_utf8", "async", ["self"], binding_name="to_utf8_async", binding_qualname="String.to_utf8_async", binding_module=__name__)
    to_code_points       = _define_function("baml.String.to_code_points", "sync",  ["self"], binding_name="to_code_points", binding_qualname="String.to_code_points", binding_module=__name__)
    to_code_points_async = _define_function("baml.String.to_code_points", "async", ["self"], binding_name="to_code_points_async", binding_qualname="String.to_code_points_async", binding_module=__name__)


class Uint8Array(pydantic.BaseModel):
    """
    A mutable, growable array of bytes, each in the range 0–255.

    The type for binary data: file contents, network payloads, encoded strings.
    `push`, `pop`, and `sort` modify the array in place; every other method here
    returns a new one.

    The two ways of turning an `int` into a byte disagree deliberately. `push`
    silently masks its argument to the low 8 bits, as assigning into a JavaScript
    typed array does, while `from_array` throws `baml.errors.InvalidArgument` on
    anything outside 0–255.

    JavaScript's [`Uint8Array`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array),
    Python's [`bytearray`](https://docs.python.org/3/library/stdtypes.html#bytearray).
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    zeroes       = staticmethod(_define_function("baml.Uint8Array.zeroes", "sync",  ["size"], binding_name="zeroes", binding_qualname="Uint8Array.zeroes", binding_module=__name__))
    zeroes_async = staticmethod(_define_function("baml.Uint8Array.zeroes", "async", ["size"], binding_name="zeroes_async", binding_qualname="Uint8Array.zeroes_async", binding_module=__name__))
    from_array       = staticmethod(_define_function("baml.Uint8Array.from_array", "sync",  ["array"], binding_name="from_array", binding_qualname="Uint8Array.from_array", binding_module=__name__))
    from_array_async = staticmethod(_define_function("baml.Uint8Array.from_array", "async", ["array"], binding_name="from_array_async", binding_qualname="Uint8Array.from_array_async", binding_module=__name__))
    from_hex       = staticmethod(_define_function("baml.Uint8Array.from_hex", "sync",  ["hex"], binding_name="from_hex", binding_qualname="Uint8Array.from_hex", binding_module=__name__))
    from_hex_async = staticmethod(_define_function("baml.Uint8Array.from_hex", "async", ["hex"], binding_name="from_hex_async", binding_qualname="Uint8Array.from_hex_async", binding_module=__name__))
    from_base64       = staticmethod(_define_function("baml.Uint8Array.from_base64", "sync",  ["base64"], binding_name="from_base64", binding_qualname="Uint8Array.from_base64", binding_module=__name__))
    from_base64_async = staticmethod(_define_function("baml.Uint8Array.from_base64", "async", ["base64"], binding_name="from_base64_async", binding_qualname="Uint8Array.from_base64_async", binding_module=__name__))
    length       = _define_function("baml.Uint8Array.length", "sync",  ["self"], binding_name="length", binding_qualname="Uint8Array.length", binding_module=__name__)
    length_async = _define_function("baml.Uint8Array.length", "async", ["self"], binding_name="length_async", binding_qualname="Uint8Array.length_async", binding_module=__name__)
    at       = _define_function("baml.Uint8Array.at", "sync",  ["self", "index"], binding_name="at", binding_qualname="Uint8Array.at", binding_module=__name__)
    at_async = _define_function("baml.Uint8Array.at", "async", ["self", "index"], binding_name="at_async", binding_qualname="Uint8Array.at_async", binding_module=__name__)
    push       = _define_function("baml.Uint8Array.push", "sync",  ["self", "item"], binding_name="push", binding_qualname="Uint8Array.push", binding_module=__name__)
    push_async = _define_function("baml.Uint8Array.push", "async", ["self", "item"], binding_name="push_async", binding_qualname="Uint8Array.push_async", binding_module=__name__)
    pop       = _define_function("baml.Uint8Array.pop", "sync",  ["self"], binding_name="pop", binding_qualname="Uint8Array.pop", binding_module=__name__)
    pop_async = _define_function("baml.Uint8Array.pop", "async", ["self"], binding_name="pop_async", binding_qualname="Uint8Array.pop_async", binding_module=__name__)
    concat       = _define_function("baml.Uint8Array.concat", "sync",  ["self", "other"], binding_name="concat", binding_qualname="Uint8Array.concat", binding_module=__name__)
    concat_async = _define_function("baml.Uint8Array.concat", "async", ["self", "other"], binding_name="concat_async", binding_qualname="Uint8Array.concat_async", binding_module=__name__)
    includes       = _define_function("baml.Uint8Array.includes", "sync",  ["self", "item"], binding_name="includes", binding_qualname="Uint8Array.includes", binding_module=__name__)
    includes_async = _define_function("baml.Uint8Array.includes", "async", ["self", "item"], binding_name="includes_async", binding_qualname="Uint8Array.includes_async", binding_module=__name__)
    index_of       = _define_function("baml.Uint8Array.index_of", "sync",  ["self", "item"], binding_name="index_of", binding_qualname="Uint8Array.index_of", binding_module=__name__)
    index_of_async = _define_function("baml.Uint8Array.index_of", "async", ["self", "item"], binding_name="index_of_async", binding_qualname="Uint8Array.index_of_async", binding_module=__name__)
    reverse       = _define_function("baml.Uint8Array.reverse", "sync",  ["self"], binding_name="reverse", binding_qualname="Uint8Array.reverse", binding_module=__name__)
    reverse_async = _define_function("baml.Uint8Array.reverse", "async", ["self"], binding_name="reverse_async", binding_qualname="Uint8Array.reverse_async", binding_module=__name__)
    slice       = _define_function("baml.Uint8Array.slice", "sync",  ["self", "start", "end"], binding_name="slice", binding_qualname="Uint8Array.slice", binding_module=__name__)
    slice_async = _define_function("baml.Uint8Array.slice", "async", ["self", "start", "end"], binding_name="slice_async", binding_qualname="Uint8Array.slice_async", binding_module=__name__)
    to_array       = _define_function("baml.Uint8Array.to_array", "sync",  ["self"], binding_name="to_array", binding_qualname="Uint8Array.to_array", binding_module=__name__)
    to_array_async = _define_function("baml.Uint8Array.to_array", "async", ["self"], binding_name="to_array_async", binding_qualname="Uint8Array.to_array_async", binding_module=__name__)
    to_hex       = _define_function("baml.Uint8Array.to_hex", "sync",  ["self"], binding_name="to_hex", binding_qualname="Uint8Array.to_hex", binding_module=__name__)
    to_hex_async = _define_function("baml.Uint8Array.to_hex", "async", ["self"], binding_name="to_hex_async", binding_qualname="Uint8Array.to_hex_async", binding_module=__name__)
    to_base64       = _define_function("baml.Uint8Array.to_base64", "sync",  ["self"], binding_name="to_base64", binding_qualname="Uint8Array.to_base64", binding_module=__name__)
    to_base64_async = _define_function("baml.Uint8Array.to_base64", "async", ["self"], binding_name="to_base64_async", binding_qualname="Uint8Array.to_base64_async", binding_module=__name__)
    _to_string_impl_       = _define_function("baml.Uint8Array._to_string_impl", "sync",  ["self"], binding_name="_to_string_impl_", binding_qualname="Uint8Array._to_string_impl_", binding_module=__name__)
    _to_string_impl__async = _define_function("baml.Uint8Array._to_string_impl", "async", ["self"], binding_name="_to_string_impl__async", binding_qualname="Uint8Array._to_string_impl__async", binding_module=__name__)
    sort       = _define_function("baml.Uint8Array.sort", "sync",  ["self"], binding_name="sort", binding_qualname="Uint8Array.sort", binding_module=__name__)
    sort_async = _define_function("baml.Uint8Array.sort", "async", ["self"], binding_name="sort_async", binding_qualname="Uint8Array.sort_async", binding_module=__name__)


__all__ = [
    "Bigint",
    "Bool",
    "Array",
    "Map",
    "deep_copy",
    "deep_copy_async",
    "TaggedString",
    "Float",
    "Int",
    "Null",
    "String",
    "Uint8Array",
    "BamlError",
    "BamlPanic",
    "UNSET",
]
