# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from baml_bridge import BamlPyHandle as _BamlPyHandle


class ScanOptions(pydantic.BaseModel):
    cwd: typing.Optional[str] = None
    dot: typing.Optional[bool] = None
    absolute: typing.Optional[bool] = None
    follow_symlinks: typing.Optional[bool] = None
    throw_error_on_broken_symlink: typing.Optional[bool] = None
    only_files: typing.Optional[bool] = None


class Glob(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    def scan(self, root: typing.Union[str, ScanOptions]) -> typing.List[str]:
        """Scans the filesystem and returns all paths matching this glob pattern.
        Pass a `string` root path or a `ScanOptions` object for more control.

        Raises:
            Io"""
    async def scan_async(self, root: typing.Union[str, ScanOptions]) -> typing.List[str]:
        """Scans the filesystem and returns all paths matching this glob pattern.
        Pass a `string` root path or a `ScanOptions` object for more control.

        Raises:
            Io"""
    def matches(self, path: str) -> bool:
        """Returns `true` if `path` matches this glob pattern.

        Pure pattern matching against the already-compiled pattern — it touches
        no filesystem, so there is nothing for it to throw."""
    async def matches_async(self, path: str) -> bool:
        """Returns `true` if `path` matches this glob pattern.

        Pure pattern matching against the already-compiled pattern — it touches
        no filesystem, so there is nothing for it to throw."""


def new(pattern: str) -> Glob:
    """Compiles a glob `pattern` and returns a `Glob` object for scanning or matching.

    # Throws

    - `ParseError` if `pattern` is not a well-formed glob.

    Raises:
        ParseError"""
async def new_async(pattern: str) -> Glob:
    """Compiles a glob `pattern` and returns a `Glob` object for scanning or matching.

    # Throws

    - `ParseError` if `pattern` is not a well-formed glob.

    Raises:
        ParseError"""


__all__ = [
    "ScanOptions",
    "Glob",
    "new",
    "new_async",
]
