# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

if typing.TYPE_CHECKING:
    from ... import ai
    from ... import baml
    from ...baml import UNSET as UNSET


T = typing.TypeVar("T")


def resolve_credential(cred: typing.Optional[ai.Credential], env_fallback: typing.Optional[str]) -> typing.Optional[str]:
    """Collapse a client's `ai.Credential?` option to the value to put on the
    wire, reading the environment at REQUEST time (never at construction).

      * a literal string resolves to itself, unless it is blank — a
        whitespace-only credential is treated as "not configured" so the rest of
        the chain can supply one;
      * a `baml.env.Ref` resolves to `ref.get()` — `null` when the named
        variable is unset, which lets the caller continue down its own chain (or
        raise the same error it raises for an unconfigured option);
      * `null` falls back to `env_fallback`, the provider's canonical variable
        name, looked up with `baml.env.get`. A `null` `env_fallback` means the
        provider has no canonical variable and the result is `null`.

    A BLANK value is "not configured" at EVERY rung, not just the literal one:
    `export OPENAI_API_KEY=` otherwise resolved to `""` and every client built
    `Authorization: Bearer ` — a provider 401 in place of the local "no
    credential configured" error the same client raises when the variable is
    absent entirely. The two spellings of "I did not set this" now behave alike.

    This IS the whole chain a client needs: explicit credential (a literal or an
    `env.NAME` ref) → the provider's canonical variable (`env_fallback`).

    Raises:
        Io, ParseError"""
async def resolve_credential_async(cred: typing.Optional[ai.Credential], env_fallback: typing.Optional[str]) -> typing.Optional[str]:
    """Collapse a client's `ai.Credential?` option to the value to put on the
    wire, reading the environment at REQUEST time (never at construction).

      * a literal string resolves to itself, unless it is blank — a
        whitespace-only credential is treated as "not configured" so the rest of
        the chain can supply one;
      * a `baml.env.Ref` resolves to `ref.get()` — `null` when the named
        variable is unset, which lets the caller continue down its own chain (or
        raise the same error it raises for an unconfigured option);
      * `null` falls back to `env_fallback`, the provider's canonical variable
        name, looked up with `baml.env.get`. A `null` `env_fallback` means the
        provider has no canonical variable and the result is `null`.

    A BLANK value is "not configured" at EVERY rung, not just the literal one:
    `export OPENAI_API_KEY=` otherwise resolved to `""` and every client built
    `Authorization: Bearer ` — a provider 401 in place of the local "no
    credential configured" error the same client raises when the variable is
    absent entirely. The two spellings of "I did not set this" now behave alike.

    This IS the whole chain a client needs: explicit credential (a literal or an
    `env.NAME` ref) → the provider's canonical variable (`env_fallback`).

    Raises:
        Io, ParseError"""


def redact_url_secrets(text: str) -> str:
    """Scrub credential-bearing query parameters out of free text before it becomes
    an `ai.errors.Failure.detail`.

    Providers that authenticate through the URL — Vertex AI express mode puts
    the key in `?key=…` — would otherwise leak it: the native HTTP layer renders
    `reqwest::Error`, whose `Display` embeds the request URL, straight into the
    transport-failure message."""
async def redact_url_secrets_async(text: str) -> str:
    """Scrub credential-bearing query parameters out of free text before it becomes
    an `ai.errors.Failure.detail`.

    Providers that authenticate through the URL — Vertex AI express mode puts
    the key in `?key=…` — would otherwise leak it: the native HTTP layer renders
    `reqwest::Error`, whose `Display` embeds the request URL, straight into the
    transport-failure message."""


def redact_request_headers(headers: typing.Dict[str, str]) -> typing.Dict[str, str]:
    """Replace credential-bearing request headers with "REDACTED" before a
    request snapshot rides an `ai.events.LLMCall`. Unlike previews, the
    request `invoke` actually sends DOES carry auth headers (`x-api-key`,
    `authorization`, Azure's `api-key`, ...), so captured requests must be
    scrubbed. Matching is case-insensitive; values are replaced, names kept."""
async def redact_request_headers_async(headers: typing.Dict[str, str]) -> typing.Dict[str, str]:
    """Replace credential-bearing request headers with "REDACTED" before a
    request snapshot rides an `ai.events.LLMCall`. Unlike previews, the
    request `invoke` actually sends DOES carry auth headers (`x-api-key`,
    `authorization`, Azure's `api-key`, ...), so captured requests must be
    scrubbed. Matching is case-insensitive; values are replaced, names kept."""


def credential_sources(cred: typing.Optional[ai.Credential], canonical_env: typing.Optional[str]) -> str:
    """The environment variables a credential chain consulted, as a readable list,
    for the "no credential configured" error a client raises when the whole
    chain came back empty.

    The point is the `Ref` arm: `api_key = env.MY_KEY` pointing at an UNSET
    variable resolves to `null` and falls through to the rest of the chain, so
    without this the error would name only the provider's canonical variable and
    never mention the one the caller actually asked for. Values are never
    included — only names."""
async def credential_sources_async(cred: typing.Optional[ai.Credential], canonical_env: typing.Optional[str]) -> str:
    """The environment variables a credential chain consulted, as a readable list,
    for the "no credential configured" error a client raises when the whole
    chain came back empty.

    The point is the `Ref` arm: `api_key = env.MY_KEY` pointing at an UNSET
    variable resolves to `null` and falls through to the rest of the chain, so
    without this the error would name only the provider's canonical variable and
    never mention the one the caller actually asked for. Values are never
    included — only names."""


def send_as(req: baml.http.Request, provider: str, *, request_timeout_ms: typing.Union[int, None, UNSET] = None, _types: dict[str, typing.Any]) -> T:
    """Send, classify non-2xx via `ai.errors.classify_http`, decode the body as T.
    T = json-shaped envelope class; unknown fields are ignored by the decoder.
    A null or non-positive timeout preserves the transport's unbounded default.

    Raises:
        Timeout"""
async def send_as_async(req: baml.http.Request, provider: str, *, request_timeout_ms: typing.Union[int, None, UNSET] = None, _types: dict[str, typing.Any]) -> T:
    """Send, classify non-2xx via `ai.errors.classify_http`, decode the body as T.
    T = json-shaped envelope class; unknown fields are ignored by the decoder.
    A null or non-positive timeout preserves the transport's unbounded default.

    Raises:
        Timeout"""


class SentAs(pydantic.BaseModel, typing.Generic[T]):
    value: T
    call: ai.events.LLMCall


def send_as_with_wire(req: baml.http.Request, provider: str, client_name: str, *, capture_wire: typing.Union[bool, UNSET] = True, request_timeout_ms: typing.Union[int, None, UNSET] = None, _types: dict[str, typing.Any]) -> SentAs[T]:
    """Same contract as `send_as`, plus the LLMCall wire record. On a non-2xx or
    transport failure this still throws the same classified error `send_as`
    throws — composite clients build failed-leg records from the error itself
    (`_failed_leg_call`), so no record accompanies a throw. `capture_wire`
    gates the request/response bodies; status, headers, and timing are always
    recorded. The request URL and captured response body are redacted with
    `redact_url_secrets` before storing.

    Raises:
        Timeout"""
async def send_as_with_wire_async(req: baml.http.Request, provider: str, client_name: str, *, capture_wire: typing.Union[bool, UNSET] = True, request_timeout_ms: typing.Union[int, None, UNSET] = None, _types: dict[str, typing.Any]) -> SentAs[T]:
    """Same contract as `send_as`, plus the LLMCall wire record. On a non-2xx or
    transport failure this still throws the same classified error `send_as`
    throws — composite clients build failed-leg records from the error itself
    (`_failed_leg_call`), so no record accompanies a throw. `capture_wire`
    gates the request/response bodies; status, headers, and timing are always
    recorded. The request URL and captured response body are redacted with
    `redact_url_secrets` before storing.

    Raises:
        Timeout"""


def render_output_format(t: typing.Any) -> str:
    """The return type's schema as prompt text, in the standard dialect —
    exactly what ${ctx.output_format()} renders in an LLM function block.

    Raises:
        CompilationError"""
async def render_output_format_async(t: typing.Any) -> str:
    """The return type's schema as prompt text, in the standard dialect —
    exactly what ${ctx.output_format()} renders in an LLM function block.

    Raises:
        CompilationError"""


class ResolvedMedia(pydantic.BaseModel):
    url: typing.Optional[str] = None
    base64: typing.Optional[str] = None
    mime_type: str


def resolve_media(media: ai.MediaPart, fetch_url: bool) -> ResolvedMedia:
    """Resolve BAML media for provider request lowering. This mirrors the media
    resolution pass in `sys_llm`: local files become base64, existing base64 is
    retained, and URL fetching is selected by the provider.

    Raises:
        InvalidArgument, Io, Timeout, NetworkFailure"""
async def resolve_media_async(media: ai.MediaPart, fetch_url: bool) -> ResolvedMedia:
    """Resolve BAML media for provider request lowering. This mirrors the media
    resolution pass in `sys_llm`: local files become base64, existing base64 is
    retained, and URL fetching is selected by the provider.

    Raises:
        InvalidArgument, Io, Timeout, NetworkFailure"""


def resolve_media_preview(media: ai.MediaPart) -> ResolvedMedia:
    """Resolve media for a request preview without reading a file or fetching a
    URL. Existing base64 and `data:` payloads are preserved; provider-specific
    renderers decide whether an ordinary URL is supported on their wire form.

    Raises:
        PreviewUnsupported"""
async def resolve_media_preview_async(media: ai.MediaPart) -> ResolvedMedia:
    """Resolve media for a request preview without reading a file or fetching a
    URL. Existing base64 and `data:` payloads are preserved; provider-specific
    renderers decide whether an ordinary URL is supported on their wire form.

    Raises:
        PreviewUnsupported"""


def merge_request_body(base: baml.json.json, overrides: typing.Optional[baml.json.json]) -> baml.json.json:
    """Deep-merge a client's `request_body` passthrough into its serialized
    request. Call this as the LAST step of building the wire body:

        let body = baml.json.to_json(typed_request);
        let merged = ai.wire.merge_request_body(body, c.request_body);
        baml.json.stringify(merged)

    Maps merge recursively, a `null` override value DELETES that key (the
    engine's removal contract — `{"max_tokens": null}` removes the default the
    client injected), and every other value replaces wholesale. A `null`
    `overrides` means "no passthrough configured" and returns `base` unchanged;
    it never deletes the whole body."""
async def merge_request_body_async(base: baml.json.json, overrides: typing.Optional[baml.json.json]) -> baml.json.json:
    """Deep-merge a client's `request_body` passthrough into its serialized
    request. Call this as the LAST step of building the wire body:

        let body = baml.json.to_json(typed_request);
        let merged = ai.wire.merge_request_body(body, c.request_body);
        baml.json.stringify(merged)

    Maps merge recursively, a `null` override value DELETES that key (the
    engine's removal contract — `{"max_tokens": null}` removes the default the
    client injected), and every other value replaces wholesale. A `null`
    `overrides` means "no passthrough configured" and returns `base` unchanged;
    it never deletes the whole body."""


def prompt_blocks(message: ai.PromptMessage) -> typing.List[ai.content.Block]:
    """A rendered prompt message's parts as content blocks: a `string` part is
    `Text`, a media part is `Media` with null provenance. The rendered prompt
    then lowers through the same path as the journal's turns."""
async def prompt_blocks_async(message: ai.PromptMessage) -> typing.List[ai.content.Block]:
    """A rendered prompt message's parts as content blocks: a `string` part is
    `Text`, a media part is `Media` with null provenance. The rendered prompt
    then lowers through the same path as the journal's turns."""


def tool_name(j: ai.Journal, id: str) -> typing.Optional[str]:
    """The name of the tool a journal call id belongs to: the `ToolUse` block in
    the assistant turn that issued it. Null for an id no assistant turn issued."""
async def tool_name_async(j: ai.Journal, id: str) -> typing.Optional[str]:
    """The name of the tool a journal call id belongs to: the `ToolUse` block in
    the assistant turn that issued it. Null for an id no assistant turn issued."""


def degrade_tool_media(j: ai.Journal, carries: typing.List[str]) -> ai.Journal:
    """Degrade, as a journal rewrite. A client that carries only some media
    kinds inside a tool result (`carries`, by `kind()`) lowers the copy of `j`
    this returns: every other media block has left its result and, behind a
    one-line note naming the tool, forms ONE `user` turn after the LAST result
    of the same assistant turn. The results of one turn stay contiguous (Chat
    Completions, Converse and Responses all reject a `user` message between
    two of them), `Text` stays where it was, and a result left with no text
    keeps the `[audio]`-style placeholder so no client sends an empty result.
    Lowering stays pure: the caller's journal is untouched and the trace still
    shows the original events."""
async def degrade_tool_media_async(j: ai.Journal, carries: typing.List[str]) -> ai.Journal:
    """Degrade, as a journal rewrite. A client that carries only some media
    kinds inside a tool result (`carries`, by `kind()`) lowers the copy of `j`
    this returns: every other media block has left its result and, behind a
    one-line note naming the tool, forms ONE `user` turn after the LAST result
    of the same assistant turn. The results of one turn stay contiguous (Chat
    Completions, Converse and Responses all reject a `user` message between
    two of them), `Text` stays where it was, and a result left with no text
    keeps the `[audio]`-style placeholder so no client sends an empty result.
    Lowering stays pure: the caller's journal is untouched and the trace still
    shows the original events."""


def sanitize_for_client(j: ai.Journal, client_id: str) -> ai.Journal:
    """Make one run's journal safe to replay to `client_id`, and return the
    sanitized copy. Every client should lower
    `ai.wire.sanitize_for_client(input.journal, self.id())` instead of
    `input.journal`. The rules, in the order they apply per event:

     1. An assistant turn from a DIFFERENT `client_id` loses its
        `ai.content.Reasoning` blocks: one model's thinking is not replayable
        to another (and providers that check reasoning signatures reject it).
     2. Empty and whitespace-only `ai.content.Text` blocks are dropped from
        assistant turns.
     3. An assistant turn left with no blocks at all is dropped entirely —
        the reasoning-only turn that lowers to `content: []` and makes
        Anthropic 400, and the same shape an aborted turn leaves behind.
        Such a turn never has tool calls, so nothing is orphaned by dropping it.
     4. A tool call with no `ToolCompleted`/`ToolFailed` before the next
        assistant or user message (or before the end of the journal) gets a
        synthesized `ToolFailed { message: "No result provided" }`, because
        most APIs reject a tool call that was never answered.

    Journal-only events (`RunStarted`, `ToolRequested`, `Usage`,
    `FinalProduced`) pass through untouched — clients skip them anyway — and,
    like the clients' own lowering, they never close an open tool-result group.
    Nothing here mutates the journal it is given."""
async def sanitize_for_client_async(j: ai.Journal, client_id: str) -> ai.Journal:
    """Make one run's journal safe to replay to `client_id`, and return the
    sanitized copy. Every client should lower
    `ai.wire.sanitize_for_client(input.journal, self.id())` instead of
    `input.journal`. The rules, in the order they apply per event:

     1. An assistant turn from a DIFFERENT `client_id` loses its
        `ai.content.Reasoning` blocks: one model's thinking is not replayable
        to another (and providers that check reasoning signatures reject it).
     2. Empty and whitespace-only `ai.content.Text` blocks are dropped from
        assistant turns.
     3. An assistant turn left with no blocks at all is dropped entirely —
        the reasoning-only turn that lowers to `content: []` and makes
        Anthropic 400, and the same shape an aborted turn leaves behind.
        Such a turn never has tool calls, so nothing is orphaned by dropping it.
     4. A tool call with no `ToolCompleted`/`ToolFailed` before the next
        assistant or user message (or before the end of the journal) gets a
        synthesized `ToolFailed { message: "No result provided" }`, because
        most APIs reject a tool call that was never answered.

    Journal-only events (`RunStarted`, `ToolRequested`, `Usage`,
    `FinalProduced`) pass through untouched — clients skip them anyway — and,
    like the clients' own lowering, they never close an open tool-result group.
    Nothing here mutates the journal it is given."""


__all__ = [
    "resolve_credential",
    "resolve_credential_async",
    "redact_url_secrets",
    "redact_url_secrets_async",
    "redact_request_headers",
    "redact_request_headers_async",
    "credential_sources",
    "credential_sources_async",
    "send_as",
    "send_as_async",
    "SentAs",
    "send_as_with_wire",
    "send_as_with_wire_async",
    "render_output_format",
    "render_output_format_async",
    "ResolvedMedia",
    "resolve_media",
    "resolve_media_async",
    "resolve_media_preview",
    "resolve_media_preview_async",
    "merge_request_body",
    "merge_request_body_async",
    "prompt_blocks",
    "prompt_blocks_async",
    "tool_name",
    "tool_name_async",
    "degrade_tool_media",
    "degrade_tool_media_async",
    "sanitize_for_client",
    "sanitize_for_client_async",
]
