# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

from baml_bridge import define_function as _define_function


current       = _define_function("baml.id.current", "sync",  [], binding_name="current", binding_qualname="current", binding_module=__name__)
current_async = _define_function("baml.id.current", "async", [], binding_name="current_async", binding_qualname="current_async", binding_module=__name__)


new       = _define_function("baml.id.new", "sync",  [], binding_name="new", binding_qualname="new", binding_module=__name__)
new_async = _define_function("baml.id.new", "async", [], binding_name="new_async", binding_qualname="new_async", binding_module=__name__)


set       = _define_function("baml.id.set", "sync",  ["id"], binding_name="set", binding_qualname="set", binding_module=__name__)
set.__doc__ = """Raises:
    InvalidArgument"""
set_async = _define_function("baml.id.set", "async", ["id"], binding_name="set_async", binding_qualname="set_async", binding_module=__name__)
set_async.__doc__ = """Raises:
    InvalidArgument"""


__all__ = [
    "current",
    "current_async",
    "new",
    "new_async",
    "set",
    "set_async",
]
