# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic


def get(key: str) -> typing.Optional[str]:
    """Returns the value of the environment variable `key`, or `null` if not set.

    # Throws

    - `baml.errors.Io` if environment variable access is not available.
    - `baml.errors.ParseError` if the variable is set but its value is not valid UTF-8.

    Raises:
        Io, ParseError"""
async def get_async(key: str) -> typing.Optional[str]:
    """Returns the value of the environment variable `key`, or `null` if not set.

    # Throws

    - `baml.errors.Io` if environment variable access is not available.
    - `baml.errors.ParseError` if the variable is set but its value is not valid UTF-8.

    Raises:
        Io, ParseError"""


def get_or_panic(key: str) -> str:
    """Returns the value of the environment variable `key`. Panics if not set.

    Raises:
        Io, ParseError"""
async def get_or_panic_async(key: str) -> str:
    """Returns the value of the environment variable `key`. Panics if not set.

    Raises:
        Io, ParseError"""


class Ref(pydantic.BaseModel):
    name: str
    def get(self) -> typing.Optional[str]:
        """Read the variable now, or `null` when it is not set.

        Raises:
            Io, ParseError"""
    async def get_async(self) -> typing.Optional[str]:
        """Read the variable now, or `null` when it is not set.

        Raises:
            Io, ParseError"""
    def get_or_panic(self) -> str:
        """Read the variable now. Panics, naming the variable, when it is not set.

        Raises:
            Io, ParseError"""
    async def get_or_panic_async(self) -> str:
        """Read the variable now. Panics, naming the variable, when it is not set.

        Raises:
            Io, ParseError"""
    def or_(self, fallback: str) -> str:
        """Read the variable now, falling back to `fallback` when it is not set.

        Raises:
            Io, ParseError"""
    async def or__async(self, fallback: str) -> str:
        """Read the variable now, falling back to `fallback` when it is not set.

        Raises:
            Io, ParseError"""


def ref(name: str) -> Ref:
    """Construct a late-bound reference to the environment variable `name`.

    This is what `env.NAME` sugar desugars to. It performs no io: the variable
    is read when the returned `Ref` is used, not here."""
async def ref_async(name: str) -> Ref:
    """Construct a late-bound reference to the environment variable `name`.

    This is what `env.NAME` sugar desugars to. It performs no io: the variable
    is read when the returned `Ref` is used, not here."""


def get_or_panic_lenient(key: str, lenient: bool) -> str:
    """Like `get_or_panic`, but tolerant of a missing variable when `lenient` is
    true: a missing variable yields the empty string instead of panicking.

    Used by generated client constructors so that offline spec prompt rendering
    can build a client for its provider/role metadata without requiring
    credentials. The direct network call constructs with `lenient = false`, so a
    missing `api_key` env var still panics for it, exactly as before.

    Raises:
        Io, ParseError"""
async def get_or_panic_lenient_async(key: str, lenient: bool) -> str:
    """Like `get_or_panic`, but tolerant of a missing variable when `lenient` is
    true: a missing variable yields the empty string instead of panicking.

    Used by generated client constructors so that offline spec prompt rendering
    can build a client for its provider/role metadata without requiring
    credentials. The direct network call constructs with `lenient = false`, so a
    missing `api_key` env var still panics for it, exactly as before.

    Raises:
        Io, ParseError"""


__all__ = [
    "get",
    "get_async",
    "get_or_panic",
    "get_or_panic_async",
    "Ref",
    "ref",
    "ref_async",
    "get_or_panic_lenient",
    "get_or_panic_lenient_async",
]
