# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import enum
import typing
import typing_extensions
import pydantic

if typing.TYPE_CHECKING:
    from ... import baml

from baml_bridge import BamlPyHandle as _BamlPyHandle


class ProcessOptions(pydantic.BaseModel):
    cwd: typing.Optional[str] = None
    env: typing.Optional[typing.Dict[str, str]] = None
    timeout_ms: typing.Optional[int] = None
    stdin: typing.Optional[str] = None
    stderr: typing.Optional[StderrMode] = None


class StderrMode(str, enum.Enum):
    Inherit = "Inherit"
    Pipe = "Pipe"
    Discard = "Discard"


class ShellOutput(pydantic.BaseModel):
    stdout: bytes
    stderr: bytes
    exit_code: int
    def ok(self) -> bool:
        """Returns `true` if the process exited with code `0`."""
    async def ok_async(self) -> bool:
        """Returns `true` if the process exited with code `0`."""


class ProcessExit(pydantic.BaseModel):
    exit_code: int
    signal: typing.Optional[str] = None
    def ok(self) -> bool:
        """Returns `true` if the process exited normally with code `0`."""
    async def ok_async(self) -> bool:
        """Returns `true` if the process exited normally with code `0`."""


class ReadPipeLines(pydantic.BaseModel):
    pipe: ReadPipe
    field_pending: bytes = pydantic.Field(alias="_pending")


def _strip_carriage_return(line: bytes) -> bytes:
    """(internal) Drop one trailing carriage return so CRLF input produces clean lines."""
async def _strip_carriage_return_async(line: bytes) -> bytes:
    """(internal) Drop one trailing carriage return so CRLF input produces clean lines."""


class Process(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    stdin: WritePipe
    stdout: ReadPipe
    stderr: typing.Optional[ReadPipe] = None
    def wait(self) -> ProcessExit:
        """Wait for the child to exit.

        Raises:
            Io, Timeout"""
    async def wait_async(self) -> ProcessExit:
        """Wait for the child to exit.

        Raises:
            Io, Timeout"""
    def kill(self) -> None:
        """Request that the child terminate.

        Raises:
            Io"""
    async def kill_async(self) -> None:
        """Request that the child terminate.

        Raises:
            Io"""
    def close(self) -> None:
        """Terminate an un-waited child and close its stdin, stdout, and stderr pipes.

        Safe to use with `defer { process.close() }`."""
    async def close_async(self) -> None:
        """Terminate an un-waited child and close its stdin, stdout, and stderr pipes.

        Safe to use with `defer { process.close() }`."""


class ReadPipe(pydantic.BaseModel):
    field_pipe: _BamlPyHandle = pydantic.Field(alias="_pipe")
    def close(self) -> None:
        """Close the read pipe, releasing any resources.

        Raises:
            Io"""
    async def close_async(self) -> None:
        """Close the read pipe, releasing any resources.

        Raises:
            Io"""
    def lines(self) -> ReadPipeLines:
        """Return a line-oriented view over this pipe."""
    async def lines_async(self) -> ReadPipeLines:
        """Return a line-oriented view over this pipe."""


class WritePipe(pydantic.BaseModel):
    field_pipe: _BamlPyHandle = pydantic.Field(alias="_pipe")
    def close(self) -> None:
        """Close the write pipe, flushing pending data and delivering EOF.

        Raises:
            Io"""
    async def close_async(self) -> None:
        """Close the write pipe, flushing pending data and delivering EOF.

        Raises:
            Io"""


def exec(program: str, args: typing.Optional[typing.List[str]], options: typing.Optional[ProcessOptions]) -> ShellOutput:
    """Runs `program` with the given `args` and returns its output. Throws on I/O failure or timeout.

    Raises:
        Io, Timeout"""
async def exec_async(program: str, args: typing.Optional[typing.List[str]], options: typing.Optional[ProcessOptions]) -> ShellOutput:
    """Runs `program` with the given `args` and returns its output. Throws on I/O failure or timeout.

    Raises:
        Io, Timeout"""


def start_process(program: str, args: typing.Optional[typing.List[str]], options: typing.Optional[ProcessOptions]) -> Process:
    """Starts `program` and returns a live process with caller-owned pipes.

    Unlike `exec`, output is not buffered until process exit. Reading
    `process.stdout` suspends only the current BAML green thread. If
    `ProcessOptions.stdin` is set, this call writes that input and waits for the
    child to consume it, bounded by `ProcessOptions.timeout_ms`.

    Raises:
        Io"""
async def start_process_async(program: str, args: typing.Optional[typing.List[str]], options: typing.Optional[ProcessOptions]) -> Process:
    """Starts `program` and returns a live process with caller-owned pipes.

    Unlike `exec`, output is not buffered until process exit. Reading
    `process.stdout` suspends only the current BAML green thread. If
    `ProcessOptions.stdin` is set, this call writes that input and waits for the
    child to consume it, bounded by `ProcessOptions.timeout_ms`.

    Raises:
        Io"""


def shell(command: str, options: typing.Optional[ProcessOptions]) -> ShellOutput:
    """Runs a shell `command` string (passed to `/bin/sh -c`) and returns its output.

    Raises:
        Io, Timeout"""
async def shell_async(command: str, options: typing.Optional[ProcessOptions]) -> ShellOutput:
    """Runs a shell `command` string (passed to `/bin/sh -c`) and returns its output.

    Raises:
        Io, Timeout"""


def sleep(delay: baml.time.Duration) -> None:
    """Suspends the current thread for `delay`.

    Raises:
        Io"""
async def sleep_async(delay: baml.time.Duration) -> None:
    """Suspends the current thread for `delay`.

    Raises:
        Io"""


def collect_garbage() -> None:
    """Forces a full garbage collection and runs queued `cleanup()` finalizers before returning.
    Intended for deterministic tests and runtime diagnostics; production code should normally
    let the runtime schedule collections automatically."""
async def collect_garbage_async() -> None:
    """Forces a full garbage collection and runs queued `cleanup()` finalizers before returning.
    Intended for deterministic tests and runtime diagnostics; production code should normally
    let the runtime schedule collections automatically."""


def panic(message: str) -> None: ...
async def panic_async(message: str) -> None: ...


def exit(code: int) -> None: ...
async def exit_async(code: int) -> None: ...


def argv() -> typing.List[str]:
    """Returns the command-line arguments passed to the BAML program, as an array of strings."""
async def argv_async() -> typing.List[str]:
    """Returns the command-line arguments passed to the BAML program, as an array of strings."""


def pid() -> int:
    """Returns the process ID of the current process.

    # Panics

    - `baml.panics.HostUnavailable` if the environment does not support process IDs (e.g. in a browser)."""
async def pid_async() -> int:
    """Returns the process ID of the current process.

    # Panics

    - `baml.panics.HostUnavailable` if the environment does not support process IDs (e.g. in a browser)."""


__all__ = [
    "ProcessOptions",
    "StderrMode",
    "ShellOutput",
    "ProcessExit",
    "ReadPipeLines",
    "Process",
    "ReadPipe",
    "WritePipe",
    "exec",
    "exec_async",
    "start_process",
    "start_process_async",
    "shell",
    "shell_async",
    "sleep",
    "sleep_async",
    "collect_garbage",
    "collect_garbage_async",
    "panic",
    "panic_async",
    "exit",
    "exit_async",
    "argv",
    "argv_async",
    "pid",
    "pid_async",
]
