# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

_LAZY_CHILDREN = frozenset({
    "clients",
    "content",
    "errors",
    "events",
    "internal",
    "mcp",
    "stream",
    "tools",
    "wire",
})

def __getattr__(name):
    if name in _LAZY_CHILDREN:
        import importlib
        return importlib.import_module(f".{name}", __name__)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

import typing
import typing_extensions
import pydantic

from .. import ai
from .. import baml

from baml_bridge import (
    BamlPyHandle as _BamlPyHandle,
    define_function as _define_function,
)

from baml_bridge import BamlFunctionSpec as FunctionSpec


Out = typing.TypeVar("Out")


Credential: typing.TypeAlias = typing.Union[str, baml.env.Ref]


MediaPart: typing.TypeAlias = typing.Union[baml.media.Image, baml.media.Audio, baml.media.Video, baml.media.Pdf]


PromptPart: typing.TypeAlias = typing.Union[str, MediaPart]


class OutputFormat(pydantic.BaseModel):
    """
    Opaque handle to a prebuilt output-format schema. This supports the
    standalone `prompt` tag's parameterized output-format rendering.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_data: _BamlPyHandle = pydantic.Field(alias="_data")
    _render_       = _define_function("ai.OutputFormat._render", "sync",  ["self"], ["prefix", "or_splitter", "enum_value_prefix", "hoisted_class_prefix", "always_hoist_enums", "quote_class_fields", "hoist_classes", "map_style", "render_null_as"], binding_name="_render_", binding_qualname="OutputFormat._render_", binding_module=__name__)
    _render__async = _define_function("ai.OutputFormat._render", "async", ["self"], ["prefix", "or_splitter", "enum_value_prefix", "hoisted_class_prefix", "always_hoist_enums", "quote_class_fields", "hoist_classes", "map_style", "render_null_as"], binding_name="_render__async", binding_qualname="OutputFormat._render__async", binding_module=__name__)


class Role(pydantic.BaseModel):
    """
    A typed chat-role marker produced by `${role("system")}` in a prompt.

    Attributes:
        name
        metadata: Provider-specific per-message metadata such as cache control.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    name: str
    metadata: typing.Dict[str, typing.Any]


class ContextClient(pydantic.BaseModel):
    """Client metadata available to a standalone `prompt` tag body."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    name: str
    provider: str
    default_role: str
    allowed_roles: typing.List[str]


class Context(pydantic.BaseModel):
    """Render context accepted by a standalone `prompt` tag closure."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    client: ContextClient
    tags: typing.Dict[str, typing.Any]
    field_output_format: OutputFormat = pydantic.Field(alias="_output_format")
    output_format       = _define_function("ai.Context.output_format", "sync",  ["self"], ["prefix", "or_splitter", "enum_value_prefix", "hoisted_class_prefix", "always_hoist_enums", "quote_class_fields", "hoist_classes", "map_style", "render_null_as"], binding_name="output_format", binding_qualname="Context.output_format", binding_module=__name__)
    output_format_async = _define_function("ai.Context.output_format", "async", ["self"], ["prefix", "or_splitter", "enum_value_prefix", "hoisted_class_prefix", "always_hoist_enums", "quote_class_fields", "hoist_classes", "map_style", "render_null_as"], binding_name="output_format_async", binding_qualname="Context.output_format_async", binding_module=__name__)


class Journal(pydantic.BaseModel):
    """
    The COMPLETE record. Repair attempts, feedback, failures — everything that
    happened is an event.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    log: typing.List[ai.events.Event]
    new       = staticmethod(_define_function("ai.Journal.new", "sync",  ["spec"], binding_name="new", binding_qualname="Journal.new", binding_module=__name__, type_params=["Out"]))
    new_async = staticmethod(_define_function("ai.Journal.new", "async", ["spec"], binding_name="new_async", binding_qualname="Journal.new_async", binding_module=__name__, type_params=["Out"]))
    entries       = _define_function("ai.Journal.entries", "sync",  ["self"], binding_name="entries", binding_qualname="Journal.entries", binding_module=__name__)
    entries_async = _define_function("ai.Journal.entries", "async", ["self"], binding_name="entries_async", binding_qualname="Journal.entries_async", binding_module=__name__)
    append_all       = _define_function("ai.Journal.append_all", "sync",  ["self", "events"], binding_name="append_all", binding_qualname="Journal.append_all", binding_module=__name__)
    append_all_async = _define_function("ai.Journal.append_all", "async", ["self", "events"], binding_name="append_all_async", binding_qualname="Journal.append_all_async", binding_module=__name__)


class RunResult(pydantic.BaseModel, typing.Generic[Out]):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    value: Out
    journal: Journal
    usage: ai.events.Usage


class Agent(pydantic.BaseModel):
    """
    The default runner. A spec-mode LLM function's direct call runs
    `Agent.new(client = client).run(Fn@spec(...)).value`; construct it
    yourself to set the other fields (`$` call-site parameters are a future
    phase).

    The class itself is not generic: none of its configuration involves the
    output type. `Out` lives on `run`, where it is inferred from the spec
    argument, so no call site needs to name it.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    max_steps: int
    schema_attempts: int
    client: typing.Optional[typing.Any] = None
    tool_errors: ai.tools.ErrorMode
    on_event: typing.Optional[typing.Callable[[ai.events.Event], None]] = None
    new       = staticmethod(_define_function("ai.Agent.new", "sync",  [], ["max_steps", "schema_attempts", "client", "tool_errors", "on_event"], binding_name="new", binding_qualname="Agent.new", binding_module=__name__))
    new_async = staticmethod(_define_function("ai.Agent.new", "async", [], ["max_steps", "schema_attempts", "client", "tool_errors", "on_event"], binding_name="new_async", binding_qualname="Agent.new_async", binding_module=__name__))
    _validated_schema_attempts_       = _define_function("ai.Agent._validated_schema_attempts", "sync",  ["self"], binding_name="_validated_schema_attempts_", binding_qualname="Agent._validated_schema_attempts_", binding_module=__name__)
    _validated_schema_attempts__async = _define_function("ai.Agent._validated_schema_attempts", "async", ["self"], binding_name="_validated_schema_attempts__async", binding_qualname="Agent._validated_schema_attempts__async", binding_module=__name__)
    _run_one_tool_       = _define_function("ai.Agent._run_one_tool", "sync",  ["self", "tb", "call", "j"], binding_name="_run_one_tool_", binding_qualname="Agent._run_one_tool_", binding_module=__name__)
    _run_one_tool__async = _define_function("ai.Agent._run_one_tool", "async", ["self", "tb", "call", "j"], binding_name="_run_one_tool__async", binding_qualname="Agent._run_one_tool__async", binding_module=__name__)
    _has_media_output_       = _define_function("ai.Agent._has_media_output", "sync",  ["self", "turn"], binding_name="_has_media_output_", binding_qualname="Agent._has_media_output_", binding_module=__name__, type_params=["Out"])
    _has_media_output__async = _define_function("ai.Agent._has_media_output", "async", ["self", "turn"], binding_name="_has_media_output__async", binding_qualname="Agent._has_media_output__async", binding_module=__name__, type_params=["Out"])
    _media_value_       = _define_function("ai.Agent._media_value", "sync",  ["self", "turn", "provider"], binding_name="_media_value_", binding_qualname="Agent._media_value_", binding_module=__name__, type_params=["Out"])
    _media_value__async = _define_function("ai.Agent._media_value", "async", ["self", "turn", "provider"], binding_name="_media_value__async", binding_qualname="Agent._media_value__async", binding_module=__name__, type_params=["Out"])
    _parses_       = _define_function("ai.Agent._parses", "sync",  ["self", "turn", "candidate"], binding_name="_parses_", binding_qualname="Agent._parses_", binding_module=__name__, type_params=["Out"])
    _parses__async = _define_function("ai.Agent._parses", "async", ["self", "turn", "candidate"], binding_name="_parses__async", binding_qualname="Agent._parses__async", binding_module=__name__, type_params=["Out"])
    _attempt_turn_       = _define_function("ai.Agent._attempt_turn", "sync",  ["self", "c", "spec", "j", "total", "attempts_left"], binding_name="_attempt_turn_", binding_qualname="Agent._attempt_turn_", binding_module=__name__, type_params=["Out"])
    _attempt_turn__async = _define_function("ai.Agent._attempt_turn", "async", ["self", "c", "spec", "j", "total", "attempts_left"], binding_name="_attempt_turn__async", binding_qualname="Agent._attempt_turn__async", binding_module=__name__, type_params=["Out"])
    _emit_from_       = _define_function("ai.Agent._emit_from", "sync",  ["self", "j", "seen"], binding_name="_emit_from_", binding_qualname="Agent._emit_from_", binding_module=__name__)
    _emit_from__async = _define_function("ai.Agent._emit_from", "async", ["self", "j", "seen"], binding_name="_emit_from__async", binding_qualname="Agent._emit_from__async", binding_module=__name__)


class PromptMessage(pydantic.BaseModel):
    """
    A single chat message in a rendered prompt.

    Attributes:
        role: The chat role, e.g. "system", "user", or "assistant". Empty for
            role-less content.
        content: The message's rendered text. Media parts use a readable placeholder.
        parts: Ordered structural content. Provider clients use this instead of the
            readable `content` projection so media survives prompt rendering.
        metadata: Per-message provider directives, carried verbatim from the
            `ai.Role.metadata` of the `${role(...)}` marker that opened
            this message — Anthropic `cache_control`, for example. Empty when the
            message carried none.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    role: str
    content: str
    parts: typing.List[PromptPart]
    metadata: typing.Dict[str, baml.json.json]


class Prompt(pydantic.BaseModel):
    """
    The rendered, provider-neutral prompt passed to clients. Roles split the
    prompt into messages and media remains structural until a provider lowers
    it to its wire format.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_data: _BamlPyHandle = pydantic.Field(alias="_data")
    text       = _define_function("ai.Prompt.text", "sync",  ["self"], binding_name="text", binding_qualname="Prompt.text", binding_module=__name__)
    text_async = _define_function("ai.Prompt.text", "async", ["self"], binding_name="text_async", binding_qualname="Prompt.text_async", binding_module=__name__)
    messages       = _define_function("ai.Prompt.messages", "sync",  ["self"], binding_name="messages", binding_qualname="Prompt.messages", binding_module=__name__)
    messages_async = _define_function("ai.Prompt.messages", "async", ["self"], binding_name="messages_async", binding_qualname="Prompt.messages_async", binding_module=__name__)


prompt       = _define_function("ai.prompt", "sync",  ["body"], binding_name="prompt", binding_qualname="prompt", binding_module=__name__)
prompt_async = _define_function("ai.prompt", "async", ["body"], binding_name="prompt_async", binding_qualname="prompt_async", binding_module=__name__)


class ModelTurnInput(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    prompt: typing.Callable[[OutputFormat], Prompt]
    journal: Journal
    toolbox: ai.tools.Toolbox
    output_type: typing.Any


class ParsedOutput(pydantic.BaseModel):
    """
    A provider-decoded output. The wrapper distinguishes a decoded null from
    absence. Runners check its runtime type before returning it to callers.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    value: typing.Any


class ModelTurn(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    parsed_output: typing.Optional[ParsedOutput] = None
    content: typing.List[ai.content.ModelBlock]
    stop_reason: ai.content.StopReason
    usage: typing.Optional[ai.events.Usage] = None
    calls: typing.List[ai.events.LLMCall]
    terminal_text       = _define_function("ai.ModelTurn.terminal_text", "sync",  ["self"], binding_name="terminal_text", binding_qualname="ModelTurn.terminal_text", binding_module=__name__)
    terminal_text_async = _define_function("ai.ModelTurn.terminal_text", "async", ["self"], binding_name="terminal_text_async", binding_qualname="ModelTurn.terminal_text_async", binding_module=__name__)
    media       = _define_function("ai.ModelTurn.media", "sync",  ["self"], binding_name="media", binding_qualname="ModelTurn.media", binding_module=__name__)
    media_async = _define_function("ai.ModelTurn.media", "async", ["self"], binding_name="media_async", binding_qualname="ModelTurn.media_async", binding_module=__name__)
    tool_uses       = _define_function("ai.ModelTurn.tool_uses", "sync",  ["self"], binding_name="tool_uses", binding_qualname="ModelTurn.tool_uses", binding_module=__name__)
    tool_uses_async = _define_function("ai.ModelTurn.tool_uses", "async", ["self"], binding_name="tool_uses_async", binding_qualname="ModelTurn.tool_uses_async", binding_module=__name__)


Selector: typing.TypeAlias = ai.clients.Selector


__all__ = [
    "Credential",
    "MediaPart",
    "PromptPart",
    "OutputFormat",
    "Role",
    "ContextClient",
    "Context",
    "Journal",
    "RunResult",
    "Agent",
    "PromptMessage",
    "Prompt",
    "prompt",
    "prompt_async",
    "FunctionSpec",
    "ModelTurnInput",
    "ParsedOutput",
    "ModelTurn",
    "Selector",
]

class Client:
    """Erased runtime token for BAML interface `ai.Client`."""
    __baml_interface_fqn__ = "ai.Client"

    def __new__(cls, *args, **kwargs):
        raise TypeError("BAML interface tokens cannot be instantiated")

    @classmethod
    def __class_getitem__(cls, args):
        import types
        return types.GenericAlias(cls, args)


try:
    __all__.extend(["Client"])
except NameError:
    __all__ = ["Client"]
