# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic


def new(value: typing.Union[str, int, int, bool]) -> Type: ...
async def new_async(value: typing.Union[str, int, int, bool]) -> Type: ...


class Type(pydantic.BaseModel):
    field_ty: typing.Any = pydantic.Field(alias="_ty")
    def value(self) -> typing.Any: ...
    async def value_async(self) -> typing.Any: ...


__all__ = [
    "new",
    "new_async",
    "Type",
]
