# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from baml_bridge import define_function as _define_function


Disambiguation: typing.TypeAlias = typing.Union[typing.Literal["compatible"], typing.Literal["earlier"], typing.Literal["later"], typing.Literal["reject"]]


class Duration(pydantic.BaseModel):
    """
    An exact, signed timespan: a count of nanoseconds, with no calendar
    attached.

    Where an `Instant` names an absolute point on the timeline, a `Duration` is
    the gap between two of them, so it may be negative — `a - b` is negative
    exactly when `a` precedes `b`. The count is a `bigint`, so every `from_*`
    constructor scales in exact arbitrary-precision arithmetic, accepts a
    negative argument, and cannot overflow.

    Deliberately narrower than `Temporal.Duration` (TC39): there are no
    year/month/week/day fields, only nanoseconds. Calendar units are the part of
    Temporal's duration model that cannot be interpreted without a reference
    point — a month is 28 to 31 days, and a day is not 24 hours on the dates a
    zone shifts. Omitting them keeps every `Duration` operation exact. The
    consequence: adding a 24-hour `Duration` to a `ZonedDateTime` advances the
    absolute time by exactly 24 hours, which is not "the same wall-clock time
    tomorrow" across a DST transition.

    Every `to_*` accessor below is lossy except `to_nanoseconds`. Each truncates
    toward zero rather than flooring, so a negative `Duration` rounds up: -1500
    nanoseconds reads back as -1 microsecond, not -2.

    Attributes:
        field_nanoseconds: (internal) The length of the timespan in nanoseconds. May be negative.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    from_nanoseconds       = staticmethod(_define_function("baml.time.Duration.from_nanoseconds", "sync",  ["ns"], binding_name="from_nanoseconds", binding_qualname="Duration.from_nanoseconds", binding_module=__name__))
    from_nanoseconds_async = staticmethod(_define_function("baml.time.Duration.from_nanoseconds", "async", ["ns"], binding_name="from_nanoseconds_async", binding_qualname="Duration.from_nanoseconds_async", binding_module=__name__))
    from_microseconds       = staticmethod(_define_function("baml.time.Duration.from_microseconds", "sync",  ["us"], binding_name="from_microseconds", binding_qualname="Duration.from_microseconds", binding_module=__name__))
    from_microseconds_async = staticmethod(_define_function("baml.time.Duration.from_microseconds", "async", ["us"], binding_name="from_microseconds_async", binding_qualname="Duration.from_microseconds_async", binding_module=__name__))
    from_milliseconds       = staticmethod(_define_function("baml.time.Duration.from_milliseconds", "sync",  ["ms"], binding_name="from_milliseconds", binding_qualname="Duration.from_milliseconds", binding_module=__name__))
    from_milliseconds_async = staticmethod(_define_function("baml.time.Duration.from_milliseconds", "async", ["ms"], binding_name="from_milliseconds_async", binding_qualname="Duration.from_milliseconds_async", binding_module=__name__))
    from_seconds       = staticmethod(_define_function("baml.time.Duration.from_seconds", "sync",  ["s"], binding_name="from_seconds", binding_qualname="Duration.from_seconds", binding_module=__name__))
    from_seconds_async = staticmethod(_define_function("baml.time.Duration.from_seconds", "async", ["s"], binding_name="from_seconds_async", binding_qualname="Duration.from_seconds_async", binding_module=__name__))
    from_minutes       = staticmethod(_define_function("baml.time.Duration.from_minutes", "sync",  ["m"], binding_name="from_minutes", binding_qualname="Duration.from_minutes", binding_module=__name__))
    from_minutes_async = staticmethod(_define_function("baml.time.Duration.from_minutes", "async", ["m"], binding_name="from_minutes_async", binding_qualname="Duration.from_minutes_async", binding_module=__name__))
    from_hours       = staticmethod(_define_function("baml.time.Duration.from_hours", "sync",  ["h"], binding_name="from_hours", binding_qualname="Duration.from_hours", binding_module=__name__))
    from_hours_async = staticmethod(_define_function("baml.time.Duration.from_hours", "async", ["h"], binding_name="from_hours_async", binding_qualname="Duration.from_hours_async", binding_module=__name__))
    abs       = _define_function("baml.time.Duration.abs", "sync",  ["self"], binding_name="abs", binding_qualname="Duration.abs", binding_module=__name__)
    abs_async = _define_function("baml.time.Duration.abs", "async", ["self"], binding_name="abs_async", binding_qualname="Duration.abs_async", binding_module=__name__)
    to_nanoseconds       = _define_function("baml.time.Duration.to_nanoseconds", "sync",  ["self"], binding_name="to_nanoseconds", binding_qualname="Duration.to_nanoseconds", binding_module=__name__)
    to_nanoseconds_async = _define_function("baml.time.Duration.to_nanoseconds", "async", ["self"], binding_name="to_nanoseconds_async", binding_qualname="Duration.to_nanoseconds_async", binding_module=__name__)
    to_microseconds       = _define_function("baml.time.Duration.to_microseconds", "sync",  ["self"], binding_name="to_microseconds", binding_qualname="Duration.to_microseconds", binding_module=__name__)
    to_microseconds_async = _define_function("baml.time.Duration.to_microseconds", "async", ["self"], binding_name="to_microseconds_async", binding_qualname="Duration.to_microseconds_async", binding_module=__name__)
    to_milliseconds       = _define_function("baml.time.Duration.to_milliseconds", "sync",  ["self"], binding_name="to_milliseconds", binding_qualname="Duration.to_milliseconds", binding_module=__name__)
    to_milliseconds_async = _define_function("baml.time.Duration.to_milliseconds", "async", ["self"], binding_name="to_milliseconds_async", binding_qualname="Duration.to_milliseconds_async", binding_module=__name__)
    to_seconds       = _define_function("baml.time.Duration.to_seconds", "sync",  ["self"], binding_name="to_seconds", binding_qualname="Duration.to_seconds", binding_module=__name__)
    to_seconds_async = _define_function("baml.time.Duration.to_seconds", "async", ["self"], binding_name="to_seconds_async", binding_qualname="Duration.to_seconds_async", binding_module=__name__)
    to_minutes       = _define_function("baml.time.Duration.to_minutes", "sync",  ["self"], binding_name="to_minutes", binding_qualname="Duration.to_minutes", binding_module=__name__)
    to_minutes_async = _define_function("baml.time.Duration.to_minutes", "async", ["self"], binding_name="to_minutes_async", binding_qualname="Duration.to_minutes_async", binding_module=__name__)
    to_hours       = _define_function("baml.time.Duration.to_hours", "sync",  ["self"], binding_name="to_hours", binding_qualname="Duration.to_hours", binding_module=__name__)
    to_hours_async = _define_function("baml.time.Duration.to_hours", "async", ["self"], binding_name="to_hours_async", binding_qualname="Duration.to_hours_async", binding_module=__name__)


class Instant(pydantic.BaseModel):
    """
    An absolute point on the global timeline, to nanosecond precision, with no
    timezone and no calendar attached.

    Equivalent to `Temporal.Instant` (TC39). `baml.time` splits absolute time
    (`Instant`, `ZonedDateTime`) from wall-clock time (`PlainDateTime` and the
    other `Plain` types) at the type level, where Python's `datetime` covers
    both and separates them only by whether a `tzinfo` happens to be attached.

    An `Instant` records *when*, never *where*: two observers in different
    timezones who agree on the moment hold equal `Instant`s. Pair it with a
    timezone via `ZonedDateTime.from_instant` to read date and time components
    off it.

    The epoch-nanosecond count is a `bigint` and is not range-checked, where
    Temporal caps `Instant` at ±10^8 days from the epoch. Constructing one and
    doing arithmetic on it therefore never fails; rendering one does, because
    RFC 3339 has only four year digits (see `to_string`).

    Every `from_timestamp_*` constructor takes a signed count, so a negative
    argument names an instant before the epoch. Every `to_timestamp_*` accessor
    but `to_timestamp_nanoseconds` is lossy, truncating toward zero rather than
    flooring — a pre-epoch instant therefore rounds *towards* the epoch, and 500
    nanoseconds before the epoch reads back as 0 microseconds.

    Attributes:
        field_nanoseconds: (internal) The number of nanoseconds since the UNIX epoch
            (1970-01-01T00:00:00Z); negative before it.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    now       = staticmethod(_define_function("baml.time.Instant.now", "sync",  [], binding_name="now", binding_qualname="Instant.now", binding_module=__name__))
    now_async = staticmethod(_define_function("baml.time.Instant.now", "async", [], binding_name="now_async", binding_qualname="Instant.now_async", binding_module=__name__))
    parse       = staticmethod(_define_function("baml.time.Instant.parse", "sync",  ["s"], binding_name="parse", binding_qualname="Instant.parse", binding_module=__name__))
    parse_async = staticmethod(_define_function("baml.time.Instant.parse", "async", ["s"], binding_name="parse_async", binding_qualname="Instant.parse_async", binding_module=__name__))
    from_timestamp_nanoseconds       = staticmethod(_define_function("baml.time.Instant.from_timestamp_nanoseconds", "sync",  ["ns"], binding_name="from_timestamp_nanoseconds", binding_qualname="Instant.from_timestamp_nanoseconds", binding_module=__name__))
    from_timestamp_nanoseconds_async = staticmethod(_define_function("baml.time.Instant.from_timestamp_nanoseconds", "async", ["ns"], binding_name="from_timestamp_nanoseconds_async", binding_qualname="Instant.from_timestamp_nanoseconds_async", binding_module=__name__))
    from_timestamp_microseconds       = staticmethod(_define_function("baml.time.Instant.from_timestamp_microseconds", "sync",  ["us"], binding_name="from_timestamp_microseconds", binding_qualname="Instant.from_timestamp_microseconds", binding_module=__name__))
    from_timestamp_microseconds_async = staticmethod(_define_function("baml.time.Instant.from_timestamp_microseconds", "async", ["us"], binding_name="from_timestamp_microseconds_async", binding_qualname="Instant.from_timestamp_microseconds_async", binding_module=__name__))
    from_timestamp_milliseconds       = staticmethod(_define_function("baml.time.Instant.from_timestamp_milliseconds", "sync",  ["ms"], binding_name="from_timestamp_milliseconds", binding_qualname="Instant.from_timestamp_milliseconds", binding_module=__name__))
    from_timestamp_milliseconds_async = staticmethod(_define_function("baml.time.Instant.from_timestamp_milliseconds", "async", ["ms"], binding_name="from_timestamp_milliseconds_async", binding_qualname="Instant.from_timestamp_milliseconds_async", binding_module=__name__))
    from_timestamp_seconds       = staticmethod(_define_function("baml.time.Instant.from_timestamp_seconds", "sync",  ["s"], binding_name="from_timestamp_seconds", binding_qualname="Instant.from_timestamp_seconds", binding_module=__name__))
    from_timestamp_seconds_async = staticmethod(_define_function("baml.time.Instant.from_timestamp_seconds", "async", ["s"], binding_name="from_timestamp_seconds_async", binding_qualname="Instant.from_timestamp_seconds_async", binding_module=__name__))
    epoch       = staticmethod(_define_function("baml.time.Instant.epoch", "sync",  [], binding_name="epoch", binding_qualname="Instant.epoch", binding_module=__name__))
    epoch_async = staticmethod(_define_function("baml.time.Instant.epoch", "async", [], binding_name="epoch_async", binding_qualname="Instant.epoch_async", binding_module=__name__))
    elapsed       = _define_function("baml.time.Instant.elapsed", "sync",  ["self"], binding_name="elapsed", binding_qualname="Instant.elapsed", binding_module=__name__)
    elapsed_async = _define_function("baml.time.Instant.elapsed", "async", ["self"], binding_name="elapsed_async", binding_qualname="Instant.elapsed_async", binding_module=__name__)
    _to_string_impl_       = _define_function("baml.time.Instant._to_string_impl", "sync",  ["self"], binding_name="_to_string_impl_", binding_qualname="Instant._to_string_impl_", binding_module=__name__)
    _to_string_impl__async = _define_function("baml.time.Instant._to_string_impl", "async", ["self"], binding_name="_to_string_impl__async", binding_qualname="Instant._to_string_impl__async", binding_module=__name__)
    max       = _define_function("baml.time.Instant.max", "sync",  ["self", "other"], binding_name="max", binding_qualname="Instant.max", binding_module=__name__)
    max_async = _define_function("baml.time.Instant.max", "async", ["self", "other"], binding_name="max_async", binding_qualname="Instant.max_async", binding_module=__name__)
    min       = _define_function("baml.time.Instant.min", "sync",  ["self", "other"], binding_name="min", binding_qualname="Instant.min", binding_module=__name__)
    min_async = _define_function("baml.time.Instant.min", "async", ["self", "other"], binding_name="min_async", binding_qualname="Instant.min_async", binding_module=__name__)
    abs_diff       = _define_function("baml.time.Instant.abs_diff", "sync",  ["self", "other"], binding_name="abs_diff", binding_qualname="Instant.abs_diff", binding_module=__name__)
    abs_diff_async = _define_function("baml.time.Instant.abs_diff", "async", ["self", "other"], binding_name="abs_diff_async", binding_qualname="Instant.abs_diff_async", binding_module=__name__)
    to_timestamp_nanoseconds       = _define_function("baml.time.Instant.to_timestamp_nanoseconds", "sync",  ["self"], binding_name="to_timestamp_nanoseconds", binding_qualname="Instant.to_timestamp_nanoseconds", binding_module=__name__)
    to_timestamp_nanoseconds_async = _define_function("baml.time.Instant.to_timestamp_nanoseconds", "async", ["self"], binding_name="to_timestamp_nanoseconds_async", binding_qualname="Instant.to_timestamp_nanoseconds_async", binding_module=__name__)
    to_timestamp_microseconds       = _define_function("baml.time.Instant.to_timestamp_microseconds", "sync",  ["self"], binding_name="to_timestamp_microseconds", binding_qualname="Instant.to_timestamp_microseconds", binding_module=__name__)
    to_timestamp_microseconds_async = _define_function("baml.time.Instant.to_timestamp_microseconds", "async", ["self"], binding_name="to_timestamp_microseconds_async", binding_qualname="Instant.to_timestamp_microseconds_async", binding_module=__name__)
    to_timestamp_milliseconds       = _define_function("baml.time.Instant.to_timestamp_milliseconds", "sync",  ["self"], binding_name="to_timestamp_milliseconds", binding_qualname="Instant.to_timestamp_milliseconds", binding_module=__name__)
    to_timestamp_milliseconds_async = _define_function("baml.time.Instant.to_timestamp_milliseconds", "async", ["self"], binding_name="to_timestamp_milliseconds_async", binding_qualname="Instant.to_timestamp_milliseconds_async", binding_module=__name__)
    to_timestamp_seconds       = _define_function("baml.time.Instant.to_timestamp_seconds", "sync",  ["self"], binding_name="to_timestamp_seconds", binding_qualname="Instant.to_timestamp_seconds", binding_module=__name__)
    to_timestamp_seconds_async = _define_function("baml.time.Instant.to_timestamp_seconds", "async", ["self"], binding_name="to_timestamp_seconds_async", binding_qualname="Instant.to_timestamp_seconds_async", binding_module=__name__)


class PlainDate(pydantic.BaseModel):
    """
    A civil date with no time and no timezone, on the proleptic Gregorian
    calendar: `1979-05-27`.

    Equivalent to `Temporal.PlainDate` (TC39). Like every `Plain` type it is a
    wall-clock quantity, not a point on the global timeline: "27 May 1979"
    begins at a different absolute moment in every timezone, so a `PlainDate`
    cannot be converted to an `Instant` without one being supplied. Give it a
    time-of-day with `to_plain_datetime`, then a timezone with
    `PlainDateTime.to_zoned`.

    The supported range is year ±9999. `from_components` and `parse` enforce it,
    but `PlainDateTime.to_plain_date` checks only that the day count fits, so it
    can hand back a `PlainDate` whose `year`, `month`, `day` and `to_string`
    then fail.
    TODO: tighten that check so those accessors cannot throw.

    Attributes:
        field_days: (internal) Days since 1970-01-01 on the proleptic Gregorian calendar;
            negative before it.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_days: int = pydantic.Field(alias="_days")
    from_components       = staticmethod(_define_function("baml.time.PlainDate.from_components", "sync",  ["year", "month", "day"], binding_name="from_components", binding_qualname="PlainDate.from_components", binding_module=__name__))
    from_components_async = staticmethod(_define_function("baml.time.PlainDate.from_components", "async", ["year", "month", "day"], binding_name="from_components_async", binding_qualname="PlainDate.from_components_async", binding_module=__name__))
    parse       = staticmethod(_define_function("baml.time.PlainDate.parse", "sync",  ["s"], binding_name="parse", binding_qualname="PlainDate.parse", binding_module=__name__))
    parse_async = staticmethod(_define_function("baml.time.PlainDate.parse", "async", ["s"], binding_name="parse_async", binding_qualname="PlainDate.parse_async", binding_module=__name__))
    _to_string_impl_       = _define_function("baml.time.PlainDate._to_string_impl", "sync",  ["self"], binding_name="_to_string_impl_", binding_qualname="PlainDate._to_string_impl_", binding_module=__name__)
    _to_string_impl__async = _define_function("baml.time.PlainDate._to_string_impl", "async", ["self"], binding_name="_to_string_impl__async", binding_qualname="PlainDate._to_string_impl__async", binding_module=__name__)
    to_plain_datetime       = _define_function("baml.time.PlainDate.to_plain_datetime", "sync",  ["self"], ["time"], binding_name="to_plain_datetime", binding_qualname="PlainDate.to_plain_datetime", binding_module=__name__)
    to_plain_datetime_async = _define_function("baml.time.PlainDate.to_plain_datetime", "async", ["self"], ["time"], binding_name="to_plain_datetime_async", binding_qualname="PlainDate.to_plain_datetime_async", binding_module=__name__)
    _to_plain_datetime_       = _define_function("baml.time.PlainDate._to_plain_datetime", "sync",  ["self", "time"], binding_name="_to_plain_datetime_", binding_qualname="PlainDate._to_plain_datetime_", binding_module=__name__)
    _to_plain_datetime__async = _define_function("baml.time.PlainDate._to_plain_datetime", "async", ["self", "time"], binding_name="_to_plain_datetime__async", binding_qualname="PlainDate._to_plain_datetime__async", binding_module=__name__)
    year       = _define_function("baml.time.PlainDate.year", "sync",  ["self"], binding_name="year", binding_qualname="PlainDate.year", binding_module=__name__)
    year_async = _define_function("baml.time.PlainDate.year", "async", ["self"], binding_name="year_async", binding_qualname="PlainDate.year_async", binding_module=__name__)
    month       = _define_function("baml.time.PlainDate.month", "sync",  ["self"], binding_name="month", binding_qualname="PlainDate.month", binding_module=__name__)
    month_async = _define_function("baml.time.PlainDate.month", "async", ["self"], binding_name="month_async", binding_qualname="PlainDate.month_async", binding_module=__name__)
    day       = _define_function("baml.time.PlainDate.day", "sync",  ["self"], binding_name="day", binding_qualname="PlainDate.day", binding_module=__name__)
    day_async = _define_function("baml.time.PlainDate.day", "async", ["self"], binding_name="day_async", binding_qualname="PlainDate.day_async", binding_module=__name__)


class PlainDateTime(pydantic.BaseModel):
    """
    A civil ("wall-clock") date and time with no timezone, on the proleptic
    Gregorian calendar: `1979-05-27T07:32:00`. It cannot be located on the
    global timeline until a timezone is supplied via `to_zoned`.

    Equivalent to `Temporal.PlainDateTime` (TC39), whose `Plain` prefix marks
    anything without a timezone.

    The supported range is year ±9999. `from_components` and `parse` enforce it;
    `+ Duration` does not, and is what walks a value out of range. Past the
    boundary every component accessor below throws
    `baml.errors.InvalidArgument`, and `to_string` panics.

    Attributes:
        field_nanoseconds: (internal) The wall-clock reading encoded as nanoseconds since
            1970-01-01T00:00:00, interpreting the reading as if it were UTC.

            A civil quantity, not an absolute time: UTC is only the arithmetic frame
            the encoding borrows, and the same bit pattern in `Instant._nanoseconds`
            or `ZonedDateTime._nanoseconds` means a different thing. `to_zoned` is
            what converts between the two readings.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    from_components       = staticmethod(_define_function("baml.time.PlainDateTime.from_components", "sync",  ["year", "month", "day"], ["hour", "minute", "second", "millisecond", "microsecond", "nanosecond"], binding_name="from_components", binding_qualname="PlainDateTime.from_components", binding_module=__name__))
    from_components_async = staticmethod(_define_function("baml.time.PlainDateTime.from_components", "async", ["year", "month", "day"], ["hour", "minute", "second", "millisecond", "microsecond", "nanosecond"], binding_name="from_components_async", binding_qualname="PlainDateTime.from_components_async", binding_module=__name__))
    _from_components_       = staticmethod(_define_function("baml.time.PlainDateTime._from_components", "sync",  ["year", "month", "day", "hour", "minute", "second", "millisecond", "microsecond", "nanosecond"], binding_name="_from_components_", binding_qualname="PlainDateTime._from_components_", binding_module=__name__))
    _from_components__async = staticmethod(_define_function("baml.time.PlainDateTime._from_components", "async", ["year", "month", "day", "hour", "minute", "second", "millisecond", "microsecond", "nanosecond"], binding_name="_from_components__async", binding_qualname="PlainDateTime._from_components__async", binding_module=__name__))
    parse       = staticmethod(_define_function("baml.time.PlainDateTime.parse", "sync",  ["s"], binding_name="parse", binding_qualname="PlainDateTime.parse", binding_module=__name__))
    parse_async = staticmethod(_define_function("baml.time.PlainDateTime.parse", "async", ["s"], binding_name="parse_async", binding_qualname="PlainDateTime.parse_async", binding_module=__name__))
    _to_string_impl_       = _define_function("baml.time.PlainDateTime._to_string_impl", "sync",  ["self"], binding_name="_to_string_impl_", binding_qualname="PlainDateTime._to_string_impl_", binding_module=__name__)
    _to_string_impl__async = _define_function("baml.time.PlainDateTime._to_string_impl", "async", ["self"], binding_name="_to_string_impl__async", binding_qualname="PlainDateTime._to_string_impl__async", binding_module=__name__)
    to_zoned       = _define_function("baml.time.PlainDateTime.to_zoned", "sync",  ["self", "timezone"], ["disambiguation"], binding_name="to_zoned", binding_qualname="PlainDateTime.to_zoned", binding_module=__name__)
    to_zoned_async = _define_function("baml.time.PlainDateTime.to_zoned", "async", ["self", "timezone"], ["disambiguation"], binding_name="to_zoned_async", binding_qualname="PlainDateTime.to_zoned_async", binding_module=__name__)
    max       = _define_function("baml.time.PlainDateTime.max", "sync",  ["self", "other"], binding_name="max", binding_qualname="PlainDateTime.max", binding_module=__name__)
    max_async = _define_function("baml.time.PlainDateTime.max", "async", ["self", "other"], binding_name="max_async", binding_qualname="PlainDateTime.max_async", binding_module=__name__)
    min       = _define_function("baml.time.PlainDateTime.min", "sync",  ["self", "other"], binding_name="min", binding_qualname="PlainDateTime.min", binding_module=__name__)
    min_async = _define_function("baml.time.PlainDateTime.min", "async", ["self", "other"], binding_name="min_async", binding_qualname="PlainDateTime.min_async", binding_module=__name__)
    to_plain_date       = _define_function("baml.time.PlainDateTime.to_plain_date", "sync",  ["self"], binding_name="to_plain_date", binding_qualname="PlainDateTime.to_plain_date", binding_module=__name__)
    to_plain_date_async = _define_function("baml.time.PlainDateTime.to_plain_date", "async", ["self"], binding_name="to_plain_date_async", binding_qualname="PlainDateTime.to_plain_date_async", binding_module=__name__)
    to_plain_time       = _define_function("baml.time.PlainDateTime.to_plain_time", "sync",  ["self"], binding_name="to_plain_time", binding_qualname="PlainDateTime.to_plain_time", binding_module=__name__)
    to_plain_time_async = _define_function("baml.time.PlainDateTime.to_plain_time", "async", ["self"], binding_name="to_plain_time_async", binding_qualname="PlainDateTime.to_plain_time_async", binding_module=__name__)
    year       = _define_function("baml.time.PlainDateTime.year", "sync",  ["self"], binding_name="year", binding_qualname="PlainDateTime.year", binding_module=__name__)
    year_async = _define_function("baml.time.PlainDateTime.year", "async", ["self"], binding_name="year_async", binding_qualname="PlainDateTime.year_async", binding_module=__name__)
    month       = _define_function("baml.time.PlainDateTime.month", "sync",  ["self"], binding_name="month", binding_qualname="PlainDateTime.month", binding_module=__name__)
    month_async = _define_function("baml.time.PlainDateTime.month", "async", ["self"], binding_name="month_async", binding_qualname="PlainDateTime.month_async", binding_module=__name__)
    day       = _define_function("baml.time.PlainDateTime.day", "sync",  ["self"], binding_name="day", binding_qualname="PlainDateTime.day", binding_module=__name__)
    day_async = _define_function("baml.time.PlainDateTime.day", "async", ["self"], binding_name="day_async", binding_qualname="PlainDateTime.day_async", binding_module=__name__)
    hour       = _define_function("baml.time.PlainDateTime.hour", "sync",  ["self"], binding_name="hour", binding_qualname="PlainDateTime.hour", binding_module=__name__)
    hour_async = _define_function("baml.time.PlainDateTime.hour", "async", ["self"], binding_name="hour_async", binding_qualname="PlainDateTime.hour_async", binding_module=__name__)
    minute       = _define_function("baml.time.PlainDateTime.minute", "sync",  ["self"], binding_name="minute", binding_qualname="PlainDateTime.minute", binding_module=__name__)
    minute_async = _define_function("baml.time.PlainDateTime.minute", "async", ["self"], binding_name="minute_async", binding_qualname="PlainDateTime.minute_async", binding_module=__name__)
    second       = _define_function("baml.time.PlainDateTime.second", "sync",  ["self"], binding_name="second", binding_qualname="PlainDateTime.second", binding_module=__name__)
    second_async = _define_function("baml.time.PlainDateTime.second", "async", ["self"], binding_name="second_async", binding_qualname="PlainDateTime.second_async", binding_module=__name__)
    millisecond       = _define_function("baml.time.PlainDateTime.millisecond", "sync",  ["self"], binding_name="millisecond", binding_qualname="PlainDateTime.millisecond", binding_module=__name__)
    millisecond_async = _define_function("baml.time.PlainDateTime.millisecond", "async", ["self"], binding_name="millisecond_async", binding_qualname="PlainDateTime.millisecond_async", binding_module=__name__)


class PlainTime(pydantic.BaseModel):
    """
    A civil wall-clock time-of-day with no date and no timezone: `07:32:00.5`.

    Equivalent to `Temporal.PlainTime` (TC39). A wall-clock reading, not a point
    on the global timeline — attach a date with `to_plain_datetime` and then a
    timezone with `PlainDateTime.to_zoned` to locate it.

    The range is one 24-hour day, `[00:00:00, 24:00:00)`. Arithmetic wraps
    inside it rather than carrying into a date: `23:00:00` plus two hours is
    `01:00:00`, with nothing recording that a day boundary was crossed. Leap
    seconds are not representable, so `second` is `[0, 59]`.

    Attributes:
        field_nanoseconds: (internal) Nanoseconds since midnight.

            Invariant: in `[0, 24h)`. `_from_components` and `parse` validate it,
            and `_wrap_into_day` re-establishes it after arithmetic. Constructing
            the class field-by-field is the one way to break it, which is why
            `_to_string_impl` normalizes defensively.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    from_components       = staticmethod(_define_function("baml.time.PlainTime.from_components", "sync",  ["hour"], ["minute", "second", "millisecond", "microsecond", "nanosecond"], binding_name="from_components", binding_qualname="PlainTime.from_components", binding_module=__name__))
    from_components_async = staticmethod(_define_function("baml.time.PlainTime.from_components", "async", ["hour"], ["minute", "second", "millisecond", "microsecond", "nanosecond"], binding_name="from_components_async", binding_qualname="PlainTime.from_components_async", binding_module=__name__))
    _from_components_       = staticmethod(_define_function("baml.time.PlainTime._from_components", "sync",  ["hour", "minute", "second", "millisecond", "microsecond", "nanosecond"], binding_name="_from_components_", binding_qualname="PlainTime._from_components_", binding_module=__name__))
    _from_components__async = staticmethod(_define_function("baml.time.PlainTime._from_components", "async", ["hour", "minute", "second", "millisecond", "microsecond", "nanosecond"], binding_name="_from_components__async", binding_qualname="PlainTime._from_components__async", binding_module=__name__))
    parse       = staticmethod(_define_function("baml.time.PlainTime.parse", "sync",  ["s"], binding_name="parse", binding_qualname="PlainTime.parse", binding_module=__name__))
    parse_async = staticmethod(_define_function("baml.time.PlainTime.parse", "async", ["s"], binding_name="parse_async", binding_qualname="PlainTime.parse_async", binding_module=__name__))
    _to_string_impl_       = _define_function("baml.time.PlainTime._to_string_impl", "sync",  ["self"], binding_name="_to_string_impl_", binding_qualname="PlainTime._to_string_impl_", binding_module=__name__)
    _to_string_impl__async = _define_function("baml.time.PlainTime._to_string_impl", "async", ["self"], binding_name="_to_string_impl__async", binding_qualname="PlainTime._to_string_impl__async", binding_module=__name__)
    to_plain_datetime       = _define_function("baml.time.PlainTime.to_plain_datetime", "sync",  ["self", "date"], binding_name="to_plain_datetime", binding_qualname="PlainTime.to_plain_datetime", binding_module=__name__)
    to_plain_datetime_async = _define_function("baml.time.PlainTime.to_plain_datetime", "async", ["self", "date"], binding_name="to_plain_datetime_async", binding_qualname="PlainTime.to_plain_datetime_async", binding_module=__name__)
    hour       = _define_function("baml.time.PlainTime.hour", "sync",  ["self"], binding_name="hour", binding_qualname="PlainTime.hour", binding_module=__name__)
    hour_async = _define_function("baml.time.PlainTime.hour", "async", ["self"], binding_name="hour_async", binding_qualname="PlainTime.hour_async", binding_module=__name__)
    minute       = _define_function("baml.time.PlainTime.minute", "sync",  ["self"], binding_name="minute", binding_qualname="PlainTime.minute", binding_module=__name__)
    minute_async = _define_function("baml.time.PlainTime.minute", "async", ["self"], binding_name="minute_async", binding_qualname="PlainTime.minute_async", binding_module=__name__)
    second       = _define_function("baml.time.PlainTime.second", "sync",  ["self"], binding_name="second", binding_qualname="PlainTime.second", binding_module=__name__)
    second_async = _define_function("baml.time.PlainTime.second", "async", ["self"], binding_name="second_async", binding_qualname="PlainTime.second_async", binding_module=__name__)
    millisecond       = _define_function("baml.time.PlainTime.millisecond", "sync",  ["self"], binding_name="millisecond", binding_qualname="PlainTime.millisecond", binding_module=__name__)
    millisecond_async = _define_function("baml.time.PlainTime.millisecond", "async", ["self"], binding_name="millisecond_async", binding_qualname="PlainTime.millisecond_async", binding_module=__name__)


_wrap_into_day       = _define_function("baml.time._wrap_into_day", "sync",  ["total_ns"], binding_name="_wrap_into_day", binding_qualname="_wrap_into_day", binding_module=__name__)
_wrap_into_day_async = _define_function("baml.time._wrap_into_day", "async", ["total_ns"], binding_name="_wrap_into_day_async", binding_qualname="_wrap_into_day_async", binding_module=__name__)


class UnknownTimezoneError(pydantic.BaseModel):
    """
    Thrown when an IANA timezone identifier cannot be resolved against the
    host's timezone database.

    A property of the identifier, not of the host: a host with no timezone
    database at all panics with `baml.panics.HostUnavailable` instead, since no
    choice of identifier would have worked.

    Attributes:
        timezone: The identifier that could not be resolved, exactly as it was supplied.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    timezone: str


class AmbiguousTimeError(pydantic.BaseModel):
    """
    Thrown when a civil time cannot be unambiguously located in a timezone (it
    falls in a DST gap or overlap) and `disambiguation` is `"reject"`.

    Any other `Disambiguation` resolves such a reading instead of throwing.

    Attributes:
        message: Human-readable description naming the timezone involved. Not intended to
            be matched on.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class TimeZoneOffset(pydantic.BaseModel):
    """
    A fixed offset from UTC, permitted in the range ±24 hours (real timezones
    currently run from -12 to +14 hours).

    Unlike an IANA identifier, a `TimeZoneOffset` does not shift with daylight
    saving. That makes every civil-to-absolute conversion total and exact — no
    gaps, no overlaps, no `Disambiguation`, no timezone database — but it also
    pins a moment's offset forever, so a future date carried in one goes wrong
    as soon as that region's rules change. `ZonedDateTime` accepts either form:
    prefer an identifier for anything scheduled ahead, and an offset for a
    timestamp already stamped by someone else.

    Attributes:
        field_nanoseconds: (internal) The offset east of UTC in nanoseconds. Invariant: within ±24
            hours inclusive.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    utc       = staticmethod(_define_function("baml.time.TimeZoneOffset.utc", "sync",  [], binding_name="utc", binding_qualname="TimeZoneOffset.utc", binding_module=__name__))
    utc_async = staticmethod(_define_function("baml.time.TimeZoneOffset.utc", "async", [], binding_name="utc_async", binding_qualname="TimeZoneOffset.utc_async", binding_module=__name__))
    new       = staticmethod(_define_function("baml.time.TimeZoneOffset.new", "sync",  ["hours", "minutes"], binding_name="new", binding_qualname="TimeZoneOffset.new", binding_module=__name__))
    new_async = staticmethod(_define_function("baml.time.TimeZoneOffset.new", "async", ["hours", "minutes"], binding_name="new_async", binding_qualname="TimeZoneOffset.new_async", binding_module=__name__))
    from_timezone       = staticmethod(_define_function("baml.time.TimeZoneOffset.from_timezone", "sync",  ["timezone", "at"], binding_name="from_timezone", binding_qualname="TimeZoneOffset.from_timezone", binding_module=__name__))
    from_timezone_async = staticmethod(_define_function("baml.time.TimeZoneOffset.from_timezone", "async", ["timezone", "at"], binding_name="from_timezone_async", binding_qualname="TimeZoneOffset.from_timezone_async", binding_module=__name__))
    local       = staticmethod(_define_function("baml.time.TimeZoneOffset.local", "sync",  [], binding_name="local", binding_qualname="TimeZoneOffset.local", binding_module=__name__))
    local_async = staticmethod(_define_function("baml.time.TimeZoneOffset.local", "async", [], binding_name="local_async", binding_qualname="TimeZoneOffset.local_async", binding_module=__name__))
    from_duration       = staticmethod(_define_function("baml.time.TimeZoneOffset.from_duration", "sync",  ["duration"], binding_name="from_duration", binding_qualname="TimeZoneOffset.from_duration", binding_module=__name__))
    from_duration_async = staticmethod(_define_function("baml.time.TimeZoneOffset.from_duration", "async", ["duration"], binding_name="from_duration_async", binding_qualname="TimeZoneOffset.from_duration_async", binding_module=__name__))
    to_duration       = _define_function("baml.time.TimeZoneOffset.to_duration", "sync",  ["self"], binding_name="to_duration", binding_qualname="TimeZoneOffset.to_duration", binding_module=__name__)
    to_duration_async = _define_function("baml.time.TimeZoneOffset.to_duration", "async", ["self"], binding_name="to_duration_async", binding_qualname="TimeZoneOffset.to_duration_async", binding_module=__name__)
    hours       = _define_function("baml.time.TimeZoneOffset.hours", "sync",  ["self"], binding_name="hours", binding_qualname="TimeZoneOffset.hours", binding_module=__name__)
    hours_async = _define_function("baml.time.TimeZoneOffset.hours", "async", ["self"], binding_name="hours_async", binding_qualname="TimeZoneOffset.hours_async", binding_module=__name__)
    minutes       = _define_function("baml.time.TimeZoneOffset.minutes", "sync",  ["self"], binding_name="minutes", binding_qualname="TimeZoneOffset.minutes", binding_module=__name__)
    minutes_async = _define_function("baml.time.TimeZoneOffset.minutes", "async", ["self"], binding_name="minutes_async", binding_qualname="TimeZoneOffset.minutes_async", binding_module=__name__)


system_timezone       = _define_function("baml.time.system_timezone", "sync",  [], binding_name="system_timezone", binding_qualname="system_timezone", binding_module=__name__)
system_timezone.__doc__ = """The system's IANA timezone identifier, for example
`"America/Los_Angeles"`. Mirrors `Temporal.Now.timeZoneId()`.

An IO function, so hosts can swap the system-state source out.

# Throws

- `baml.errors.Io` if the host has a timezone database but cannot tell which
  zone it is configured for — an unset or unrecognized system setting, which
  a caller can reasonably fall back from (say, to UTC).

# Panics

- `baml.panics.HostUnavailable` if the host provides no timezone database at
  all. Nothing the caller could have done differently, so it takes the panic
  channel rather than the error one.

Raises:
    Io"""
system_timezone_async = _define_function("baml.time.system_timezone", "async", [], binding_name="system_timezone_async", binding_qualname="system_timezone_async", binding_module=__name__)
system_timezone_async.__doc__ = """The system's IANA timezone identifier, for example
`"America/Los_Angeles"`. Mirrors `Temporal.Now.timeZoneId()`.

An IO function, so hosts can swap the system-state source out.

# Throws

- `baml.errors.Io` if the host has a timezone database but cannot tell which
  zone it is configured for — an unset or unrecognized system setting, which
  a caller can reasonably fall back from (say, to UTC).

# Panics

- `baml.panics.HostUnavailable` if the host provides no timezone database at
  all. Nothing the caller could have done differently, so it takes the panic
  channel rather than the error one.

Raises:
    Io"""


_tz_offset_at       = _define_function("baml.time._tz_offset_at", "sync",  ["timezone", "at_ns"], binding_name="_tz_offset_at", binding_qualname="_tz_offset_at", binding_module=__name__)
_tz_offset_at_async = _define_function("baml.time._tz_offset_at", "async", ["timezone", "at_ns"], binding_name="_tz_offset_at_async", binding_qualname="_tz_offset_at_async", binding_module=__name__)


_tz_to_instant       = _define_function("baml.time._tz_to_instant", "sync",  ["timezone", "civil_ns", "disambiguation"], binding_name="_tz_to_instant", binding_qualname="_tz_to_instant", binding_module=__name__)
_tz_to_instant.__doc__ = """(internal) Locates a civil ("wall-clock") reading in an IANA timezone,
producing an absolute time. The lookup behind `PlainDateTime.to_zoned`.

# Parameters

- `timezone`: an IANA identifier.
- `civil_ns`: the wall-clock reading as nanoseconds since
  1970-01-01T00:00:00, interpreted as if UTC — the encoding
  `PlainDateTime._nanoseconds` uses.
- `disambiguation`: `"compatible"`, `"earlier"` or `"later"`. Any other
  string is treated as `"compatible"`. `"reject"` never reaches here:
  callers implement it by resolving both `"earlier"` and `"later"` and
  requiring them to agree.

# Returns

The resolved absolute time as nanoseconds since the Unix epoch, or `null` if
the identifier is unknown to the host's timezone database (callers turn that
into `baml.time.UnknownTimezoneError`).

# Throws

- `baml.errors.Io` if the reading is outside the year range the host can
  represent, or the host's timezone database fails to resolve it.

# Panics

- `baml.panics.HostUnavailable` if timezone data is unavailable.

Raises:
    Io"""
_tz_to_instant_async = _define_function("baml.time._tz_to_instant", "async", ["timezone", "civil_ns", "disambiguation"], binding_name="_tz_to_instant_async", binding_qualname="_tz_to_instant_async", binding_module=__name__)
_tz_to_instant_async.__doc__ = """(internal) Locates a civil ("wall-clock") reading in an IANA timezone,
producing an absolute time. The lookup behind `PlainDateTime.to_zoned`.

# Parameters

- `timezone`: an IANA identifier.
- `civil_ns`: the wall-clock reading as nanoseconds since
  1970-01-01T00:00:00, interpreted as if UTC — the encoding
  `PlainDateTime._nanoseconds` uses.
- `disambiguation`: `"compatible"`, `"earlier"` or `"later"`. Any other
  string is treated as `"compatible"`. `"reject"` never reaches here:
  callers implement it by resolving both `"earlier"` and `"later"` and
  requiring them to agree.

# Returns

The resolved absolute time as nanoseconds since the Unix epoch, or `null` if
the identifier is unknown to the host's timezone database (callers turn that
into `baml.time.UnknownTimezoneError`).

# Throws

- `baml.errors.Io` if the reading is outside the year range the host can
  represent, or the host's timezone database fails to resolve it.

# Panics

- `baml.panics.HostUnavailable` if timezone data is unavailable.

Raises:
    Io"""


class ZonedDateTime(pydantic.BaseModel):
    """
    A timezone-aware point in time: an absolute instant plus a timezone, either
    a fixed offset (`-07:00`) or an IANA identifier (`America/Los_Angeles`).

    Equivalent to `Temporal.ZonedDateTime` (TC39). The timezone does not affect
    the absolute time; it affects how the date and time components are read and
    how the value is formatted. What is stored is the absolute time, as in
    `Instant`, rather than calendar components, so a value is never ambiguous
    across a DST transition.

    An IANA identifier is kept exactly as supplied and is never validated on
    construction. A bad one surfaces at the first call that has to resolve it:
    `timezone_offset`, `to_plain`, a component accessor, or `to_string`.

    Every component accessor below reads through `to_plain`, and so shares one
    failure set: it throws `baml.time.UnknownTimezoneError` for an IANA
    identifier the host does not know, throws `baml.errors.InvalidArgument` if
    the local reading is outside the ±9999 year range, and panics with
    `baml.panics.HostUnavailable` if the host has no timezone database at all.

    Attributes:
        field_nanoseconds: (internal) Nanoseconds since the Unix epoch — an inlined `Instant`, and
            the absolute time this value denotes.
        field_offset_ns: (internal) The fixed offset in nanoseconds, if the timezone is a fixed
            offset. Invariant: exactly one of `_offset_ns` / `_iana` is non-null.
        field_iana: (internal) The IANA identifier, if the timezone is one. Not validated on
            construction — see `parse`.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    field_offset_ns: typing.Optional[int] = pydantic.Field(default=None, alias="_offset_ns")
    field_iana: typing.Optional[str] = pydantic.Field(default=None, alias="_iana")
    now       = staticmethod(_define_function("baml.time.ZonedDateTime.now", "sync",  [], binding_name="now", binding_qualname="ZonedDateTime.now", binding_module=__name__))
    now_async = staticmethod(_define_function("baml.time.ZonedDateTime.now", "async", [], binding_name="now_async", binding_qualname="ZonedDateTime.now_async", binding_module=__name__))
    now_in       = staticmethod(_define_function("baml.time.ZonedDateTime.now_in", "sync",  ["timezone"], binding_name="now_in", binding_qualname="ZonedDateTime.now_in", binding_module=__name__))
    now_in_async = staticmethod(_define_function("baml.time.ZonedDateTime.now_in", "async", ["timezone"], binding_name="now_in_async", binding_qualname="ZonedDateTime.now_in_async", binding_module=__name__))
    from_instant       = staticmethod(_define_function("baml.time.ZonedDateTime.from_instant", "sync",  ["instant", "timezone"], binding_name="from_instant", binding_qualname="ZonedDateTime.from_instant", binding_module=__name__))
    from_instant_async = staticmethod(_define_function("baml.time.ZonedDateTime.from_instant", "async", ["instant", "timezone"], binding_name="from_instant_async", binding_qualname="ZonedDateTime.from_instant_async", binding_module=__name__))
    from_components       = staticmethod(_define_function("baml.time.ZonedDateTime.from_components", "sync",  ["timezone", "year", "month", "day"], ["hour", "minute", "second", "millisecond", "microsecond", "nanosecond", "disambiguation"], binding_name="from_components", binding_qualname="ZonedDateTime.from_components", binding_module=__name__))
    from_components_async = staticmethod(_define_function("baml.time.ZonedDateTime.from_components", "async", ["timezone", "year", "month", "day"], ["hour", "minute", "second", "millisecond", "microsecond", "nanosecond", "disambiguation"], binding_name="from_components_async", binding_qualname="ZonedDateTime.from_components_async", binding_module=__name__))
    parse       = staticmethod(_define_function("baml.time.ZonedDateTime.parse", "sync",  ["s"], binding_name="parse", binding_qualname="ZonedDateTime.parse", binding_module=__name__))
    parse_async = staticmethod(_define_function("baml.time.ZonedDateTime.parse", "async", ["s"], binding_name="parse_async", binding_qualname="ZonedDateTime.parse_async", binding_module=__name__))
    to_instant       = _define_function("baml.time.ZonedDateTime.to_instant", "sync",  ["self"], binding_name="to_instant", binding_qualname="ZonedDateTime.to_instant", binding_module=__name__)
    to_instant_async = _define_function("baml.time.ZonedDateTime.to_instant", "async", ["self"], binding_name="to_instant_async", binding_qualname="ZonedDateTime.to_instant_async", binding_module=__name__)
    max       = _define_function("baml.time.ZonedDateTime.max", "sync",  ["self", "other"], binding_name="max", binding_qualname="ZonedDateTime.max", binding_module=__name__)
    max_async = _define_function("baml.time.ZonedDateTime.max", "async", ["self", "other"], binding_name="max_async", binding_qualname="ZonedDateTime.max_async", binding_module=__name__)
    min       = _define_function("baml.time.ZonedDateTime.min", "sync",  ["self", "other"], binding_name="min", binding_qualname="ZonedDateTime.min", binding_module=__name__)
    min_async = _define_function("baml.time.ZonedDateTime.min", "async", ["self", "other"], binding_name="min_async", binding_qualname="ZonedDateTime.min_async", binding_module=__name__)
    with_timezone       = _define_function("baml.time.ZonedDateTime.with_timezone", "sync",  ["self", "timezone"], binding_name="with_timezone", binding_qualname="ZonedDateTime.with_timezone", binding_module=__name__)
    with_timezone_async = _define_function("baml.time.ZonedDateTime.with_timezone", "async", ["self", "timezone"], binding_name="with_timezone_async", binding_qualname="ZonedDateTime.with_timezone_async", binding_module=__name__)
    timezone       = _define_function("baml.time.ZonedDateTime.timezone", "sync",  ["self"], binding_name="timezone", binding_qualname="ZonedDateTime.timezone", binding_module=__name__)
    timezone_async = _define_function("baml.time.ZonedDateTime.timezone", "async", ["self"], binding_name="timezone_async", binding_qualname="ZonedDateTime.timezone_async", binding_module=__name__)
    timezone_offset       = _define_function("baml.time.ZonedDateTime.timezone_offset", "sync",  ["self"], binding_name="timezone_offset", binding_qualname="ZonedDateTime.timezone_offset", binding_module=__name__)
    timezone_offset_async = _define_function("baml.time.ZonedDateTime.timezone_offset", "async", ["self"], binding_name="timezone_offset_async", binding_qualname="ZonedDateTime.timezone_offset_async", binding_module=__name__)
    to_plain       = _define_function("baml.time.ZonedDateTime.to_plain", "sync",  ["self"], binding_name="to_plain", binding_qualname="ZonedDateTime.to_plain", binding_module=__name__)
    to_plain_async = _define_function("baml.time.ZonedDateTime.to_plain", "async", ["self"], binding_name="to_plain_async", binding_qualname="ZonedDateTime.to_plain_async", binding_module=__name__)
    year       = _define_function("baml.time.ZonedDateTime.year", "sync",  ["self"], binding_name="year", binding_qualname="ZonedDateTime.year", binding_module=__name__)
    year_async = _define_function("baml.time.ZonedDateTime.year", "async", ["self"], binding_name="year_async", binding_qualname="ZonedDateTime.year_async", binding_module=__name__)
    month       = _define_function("baml.time.ZonedDateTime.month", "sync",  ["self"], binding_name="month", binding_qualname="ZonedDateTime.month", binding_module=__name__)
    month_async = _define_function("baml.time.ZonedDateTime.month", "async", ["self"], binding_name="month_async", binding_qualname="ZonedDateTime.month_async", binding_module=__name__)
    day       = _define_function("baml.time.ZonedDateTime.day", "sync",  ["self"], binding_name="day", binding_qualname="ZonedDateTime.day", binding_module=__name__)
    day_async = _define_function("baml.time.ZonedDateTime.day", "async", ["self"], binding_name="day_async", binding_qualname="ZonedDateTime.day_async", binding_module=__name__)
    hour       = _define_function("baml.time.ZonedDateTime.hour", "sync",  ["self"], binding_name="hour", binding_qualname="ZonedDateTime.hour", binding_module=__name__)
    hour_async = _define_function("baml.time.ZonedDateTime.hour", "async", ["self"], binding_name="hour_async", binding_qualname="ZonedDateTime.hour_async", binding_module=__name__)
    minute       = _define_function("baml.time.ZonedDateTime.minute", "sync",  ["self"], binding_name="minute", binding_qualname="ZonedDateTime.minute", binding_module=__name__)
    minute_async = _define_function("baml.time.ZonedDateTime.minute", "async", ["self"], binding_name="minute_async", binding_qualname="ZonedDateTime.minute_async", binding_module=__name__)
    second       = _define_function("baml.time.ZonedDateTime.second", "sync",  ["self"], binding_name="second", binding_qualname="ZonedDateTime.second", binding_module=__name__)
    second_async = _define_function("baml.time.ZonedDateTime.second", "async", ["self"], binding_name="second_async", binding_qualname="ZonedDateTime.second_async", binding_module=__name__)
    millisecond       = _define_function("baml.time.ZonedDateTime.millisecond", "sync",  ["self"], binding_name="millisecond", binding_qualname="ZonedDateTime.millisecond", binding_module=__name__)
    millisecond_async = _define_function("baml.time.ZonedDateTime.millisecond", "async", ["self"], binding_name="millisecond_async", binding_qualname="ZonedDateTime.millisecond_async", binding_module=__name__)


_format_zoned       = _define_function("baml.time._format_zoned", "sync",  ["epoch_ns", "offset_ns", "iana"], binding_name="_format_zoned", binding_qualname="_format_zoned", binding_module=__name__)
_format_zoned.__doc__ = """(internal) Formats an absolute time as RFC 3339 at the given offset,
appending an RFC 9557 `[iana]` annotation when `iana` is non-null.

Takes the offset already resolved rather than resolving it itself, so the
timezone-database lookup stays in BAML where its failure can be routed to
either channel — `to_string` panics, `to_json` throws.

# Parameters

- `epoch_ns`: the absolute time, in nanoseconds since the Unix epoch.
- `offset_ns`: the offset to render at, in nanoseconds east of UTC. Any
  sub-minute part is truncated toward zero, since RFC 3339 offsets are
  `±hh:mm`.
- `iana`: the identifier for the bracketed annotation, or `null` for a fixed
  offset. Its presence also decides the zero-offset spelling: `Z` for a
  fixed offset, `+00:00` alongside the annotation otherwise — the way
  Temporal serializes.

# Throws

- `baml.errors.InvalidArgument` if the local reading is outside the
  supported ±9999 year range.

Raises:
    InvalidArgument"""
_format_zoned_async = _define_function("baml.time._format_zoned", "async", ["epoch_ns", "offset_ns", "iana"], binding_name="_format_zoned_async", binding_qualname="_format_zoned_async", binding_module=__name__)
_format_zoned_async.__doc__ = """(internal) Formats an absolute time as RFC 3339 at the given offset,
appending an RFC 9557 `[iana]` annotation when `iana` is non-null.

Takes the offset already resolved rather than resolving it itself, so the
timezone-database lookup stays in BAML where its failure can be routed to
either channel — `to_string` panics, `to_json` throws.

# Parameters

- `epoch_ns`: the absolute time, in nanoseconds since the Unix epoch.
- `offset_ns`: the offset to render at, in nanoseconds east of UTC. Any
  sub-minute part is truncated toward zero, since RFC 3339 offsets are
  `±hh:mm`.
- `iana`: the identifier for the bracketed annotation, or `null` for a fixed
  offset. Its presence also decides the zero-offset spelling: `Z` for a
  fixed offset, `+00:00` alongside the annotation otherwise — the way
  Temporal serializes.

# Throws

- `baml.errors.InvalidArgument` if the local reading is outside the
  supported ±9999 year range.

Raises:
    InvalidArgument"""


__all__ = [
    "Disambiguation",
    "Duration",
    "Instant",
    "PlainDate",
    "PlainDateTime",
    "PlainTime",
    "UnknownTimezoneError",
    "AmbiguousTimeError",
    "TimeZoneOffset",
    "system_timezone",
    "system_timezone_async",
    "ZonedDateTime",
]
