# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

if typing.TYPE_CHECKING:
    from ...baml import UNSET as UNSET


Disambiguation: typing.TypeAlias = typing.Union[typing.Literal["compatible"], typing.Literal["earlier"], typing.Literal["later"], typing.Literal["reject"]]


class Duration(pydantic.BaseModel):
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    @staticmethod
    def from_nanoseconds(ns: typing.Union[int, int]) -> Duration:
        """A timespan of `ns` nanoseconds."""
    @staticmethod
    async def from_nanoseconds_async(ns: typing.Union[int, int]) -> Duration:
        """A timespan of `ns` nanoseconds."""
    @staticmethod
    def from_microseconds(us: typing.Union[int, int]) -> Duration:
        """A timespan of `us` microseconds, i.e. `us * 1000` nanoseconds."""
    @staticmethod
    async def from_microseconds_async(us: typing.Union[int, int]) -> Duration:
        """A timespan of `us` microseconds, i.e. `us * 1000` nanoseconds."""
    @staticmethod
    def from_milliseconds(ms: typing.Union[int, int]) -> Duration:
        """A timespan of `ms` milliseconds, i.e. `ms * 1000000` nanoseconds."""
    @staticmethod
    async def from_milliseconds_async(ms: typing.Union[int, int]) -> Duration:
        """A timespan of `ms` milliseconds, i.e. `ms * 1000000` nanoseconds."""
    @staticmethod
    def from_seconds(s: typing.Union[int, int]) -> Duration:
        """A timespan of `s` seconds, i.e. `s * 1000000000` nanoseconds."""
    @staticmethod
    async def from_seconds_async(s: typing.Union[int, int]) -> Duration:
        """A timespan of `s` seconds, i.e. `s * 1000000000` nanoseconds."""
    @staticmethod
    def from_minutes(m: typing.Union[int, int]) -> Duration:
        """A timespan of `m` minutes, i.e. `m * 60` seconds."""
    @staticmethod
    async def from_minutes_async(m: typing.Union[int, int]) -> Duration:
        """A timespan of `m` minutes, i.e. `m * 60` seconds."""
    @staticmethod
    def from_hours(h: typing.Union[int, int]) -> Duration:
        """A timespan of `h` hours, i.e. `h * 3600` seconds.

        A fixed 3600-second hour, never a calendar hour: it does not absorb a
        DST transition. See the note on `Duration`."""
    @staticmethod
    async def from_hours_async(h: typing.Union[int, int]) -> Duration:
        """A timespan of `h` hours, i.e. `h * 3600` seconds.

        A fixed 3600-second hour, never a calendar hour: it does not absorb a
        DST transition. See the note on `Duration`."""
    def abs(self) -> Duration:
        """The magnitude of `self`, with the sign discarded."""
    async def abs_async(self) -> Duration:
        """The magnitude of `self`, with the sign discarded."""
    def to_nanoseconds(self) -> int:
        """The length of `self` in nanoseconds. Exact: this is the stored unit."""
    async def to_nanoseconds_async(self) -> int:
        """The length of `self` in nanoseconds. Exact: this is the stored unit."""
    def to_microseconds(self) -> int:
        """The length of `self` in whole microseconds."""
    async def to_microseconds_async(self) -> int:
        """The length of `self` in whole microseconds."""
    def to_milliseconds(self) -> int:
        """The length of `self` in whole milliseconds."""
    async def to_milliseconds_async(self) -> int:
        """The length of `self` in whole milliseconds."""
    def to_seconds(self) -> int:
        """The length of `self` in whole seconds."""
    async def to_seconds_async(self) -> int:
        """The length of `self` in whole seconds."""
    def to_minutes(self) -> int:
        """The length of `self` in whole minutes."""
    async def to_minutes_async(self) -> int:
        """The length of `self` in whole minutes."""
    def to_hours(self) -> int:
        """The length of `self` in whole hours, each a fixed 3600 seconds."""
    async def to_hours_async(self) -> int:
        """The length of `self` in whole hours, each a fixed 3600 seconds."""


class Instant(pydantic.BaseModel):
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    @staticmethod
    def now() -> Instant:
        """The current point in time, read from the host's wall clock. Mirrors
        `Temporal.Now.instant()`.

        Wall-clock time is not monotonic: [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol)
        adjustments and manual clock changes can make a later call return an
        earlier `Instant`. Do not build a monotonic timer out of it.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock. A missing
          clock is a property of the platform, not of the call, so there is
          nothing for a caller to handle — hence a panic rather than an error."""
    @staticmethod
    async def now_async() -> Instant:
        """The current point in time, read from the host's wall clock. Mirrors
        `Temporal.Now.instant()`.

        Wall-clock time is not monotonic: [NTP](https://en.wikipedia.org/wiki/Network_Time_Protocol)
        adjustments and manual clock changes can make a later call return an
        earlier `Instant`. Do not build a monotonic timer out of it.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock. A missing
          clock is a property of the platform, not of the call, so there is
          nothing for a caller to handle — hence a panic rather than an error."""
    @staticmethod
    def parse(s: str) -> Instant:
        """Raises:
            ParseError"""
    @staticmethod
    async def parse_async(s: str) -> Instant:
        """Raises:
            ParseError"""
    @staticmethod
    def from_timestamp_nanoseconds(ns: int) -> Instant:
        """The `Instant` `ns` nanoseconds after the UNIX epoch."""
    @staticmethod
    async def from_timestamp_nanoseconds_async(ns: int) -> Instant:
        """The `Instant` `ns` nanoseconds after the UNIX epoch."""
    @staticmethod
    def from_timestamp_microseconds(us: int) -> Instant:
        """The `Instant` `us` microseconds after the UNIX epoch."""
    @staticmethod
    async def from_timestamp_microseconds_async(us: int) -> Instant:
        """The `Instant` `us` microseconds after the UNIX epoch."""
    @staticmethod
    def from_timestamp_milliseconds(ms: int) -> Instant:
        """The `Instant` `ms` milliseconds after the UNIX epoch. This is the unit
        most JSON and JavaScript timestamps arrive in."""
    @staticmethod
    async def from_timestamp_milliseconds_async(ms: int) -> Instant:
        """The `Instant` `ms` milliseconds after the UNIX epoch. This is the unit
        most JSON and JavaScript timestamps arrive in."""
    @staticmethod
    def from_timestamp_seconds(s: int) -> Instant:
        """The `Instant` `s` seconds after the UNIX epoch. This is the unit a POSIX
        `time_t` arrives in."""
    @staticmethod
    async def from_timestamp_seconds_async(s: int) -> Instant:
        """The `Instant` `s` seconds after the UNIX epoch. This is the unit a POSIX
        `time_t` arrives in."""
    @staticmethod
    def epoch() -> Instant:
        """The UNIX epoch itself, 1970-01-01T00:00:00Z. Equivalent to
        `Instant.from_timestamp_seconds(0)`."""
    @staticmethod
    async def epoch_async() -> Instant:
        """The UNIX epoch itself, 1970-01-01T00:00:00Z. Equivalent to
        `Instant.from_timestamp_seconds(0)`."""
    def elapsed(self) -> Duration:
        """The time elapsed since `self`, i.e. `Instant.now() - self`. Negative if
        `self` is in the future.

        Reads the clock through `Instant.now()` and inherits its caveats: a
        non-monotonic clock can hand back a negative result even for a `self`
        captured earlier. The measurement also absorbs the overhead of the call
        itself, so it is not a high-precision benchmarking tool.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock.

        # Examples

        ```baml
        let start = Instant.now();
        let response = baml.http.fetch("https://example.com");
        let duration = start.elapsed();
        ```"""
    async def elapsed_async(self) -> Duration:
        """The time elapsed since `self`, i.e. `Instant.now() - self`. Negative if
        `self` is in the future.

        Reads the clock through `Instant.now()` and inherits its caveats: a
        non-monotonic clock can hand back a negative result even for a `self`
        captured earlier. The measurement also absorbs the overhead of the call
        itself, so it is not a high-precision benchmarking tool.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock.

        # Examples

        ```baml
        let start = Instant.now();
        let response = baml.http.fetch("https://example.com");
        let duration = start.elapsed();
        ```"""
    def _to_string_impl_(self) -> str:
        """(internal) RFC 3339 formatter, shared by `to_string` and `to_json` so
        the two agree byte for byte.

        # Throws

        - `baml.errors.InvalidArgument` if the year is outside the four-digit
          RFC 3339 range, or the nanosecond count is too large to convert.
          `baml.ToString.to_string` turns that into a panic, while `to_json`
          surfaces it as a `baml.json.SerializationError`.

        Raises:
            InvalidArgument"""
    async def _to_string_impl__async(self) -> str:
        """(internal) RFC 3339 formatter, shared by `to_string` and `to_json` so
        the two agree byte for byte.

        # Throws

        - `baml.errors.InvalidArgument` if the year is outside the four-digit
          RFC 3339 range, or the nanosecond count is too large to convert.
          `baml.ToString.to_string` turns that into a panic, while `to_json`
          surfaces it as a `baml.json.SerializationError`.

        Raises:
            InvalidArgument"""
    def max(self, other: Instant) -> Instant:
        """The later of `self` and `other`; `self` if they are the same instant."""
    async def max_async(self, other: Instant) -> Instant:
        """The later of `self` and `other`; `self` if they are the same instant."""
    def min(self, other: Instant) -> Instant:
        """The earlier of `self` and `other`; `self` if they are the same instant."""
    async def min_async(self, other: Instant) -> Instant:
        """The earlier of `self` and `other`; `self` if they are the same instant."""
    def abs_diff(self, other: Instant) -> Duration:
        """How far apart `self` and `other` are, regardless of which came first.

        Never negative, and commutative: swapping `self` and `other` does not
        change the result. Use `self - other` instead when the sign — i.e. the
        direction — matters."""
    async def abs_diff_async(self, other: Instant) -> Duration:
        """How far apart `self` and `other` are, regardless of which came first.

        Never negative, and commutative: swapping `self` and `other` does not
        change the result. Use `self - other` instead when the sign — i.e. the
        direction — matters."""
    def to_timestamp_nanoseconds(self) -> int:
        """The number of nanoseconds since the UNIX epoch. Exact: this is the
        stored unit."""
    async def to_timestamp_nanoseconds_async(self) -> int:
        """The number of nanoseconds since the UNIX epoch. Exact: this is the
        stored unit."""
    def to_timestamp_microseconds(self) -> int:
        """The number of whole microseconds since the UNIX epoch."""
    async def to_timestamp_microseconds_async(self) -> int:
        """The number of whole microseconds since the UNIX epoch."""
    def to_timestamp_milliseconds(self) -> int:
        """The number of whole milliseconds since the UNIX epoch."""
    async def to_timestamp_milliseconds_async(self) -> int:
        """The number of whole milliseconds since the UNIX epoch."""
    def to_timestamp_seconds(self) -> int:
        """The number of whole seconds since the UNIX epoch."""
    async def to_timestamp_seconds_async(self) -> int:
        """The number of whole seconds since the UNIX epoch."""


class PlainDate(pydantic.BaseModel):
    field_days: int = pydantic.Field(alias="_days")
    @staticmethod
    def from_components(year: int, month: int, day: int) -> PlainDate:
        """Raises:
            InvalidArgument"""
    @staticmethod
    async def from_components_async(year: int, month: int, day: int) -> PlainDate:
        """Raises:
            InvalidArgument"""
    @staticmethod
    def parse(s: str) -> PlainDate:
        """Raises:
            ParseError"""
    @staticmethod
    async def parse_async(s: str) -> PlainDate:
        """Raises:
            ParseError"""
    def _to_string_impl_(self) -> str:
        """(internal) ISO 8601 formatter, shared by `to_string` and `to_json` so
        the two agree byte for byte.

        # Throws

        - `baml.errors.InvalidArgument` if the day count puts the date outside
          the ±9999 year range. `baml.ToString.to_string` turns that into a
          panic, while `to_json` surfaces it as a
          `baml.json.SerializationError`.

        Raises:
            InvalidArgument"""
    async def _to_string_impl__async(self) -> str:
        """(internal) ISO 8601 formatter, shared by `to_string` and `to_json` so
        the two agree byte for byte.

        # Throws

        - `baml.errors.InvalidArgument` if the day count puts the date outside
          the ±9999 year range. `baml.ToString.to_string` turns that into a
          panic, while `to_json` surfaces it as a
          `baml.json.SerializationError`.

        Raises:
            InvalidArgument"""
    def to_plain_datetime(self, *, time: typing.Union[PlainTime, UNSET] = UNSET) -> PlainDateTime:
        """Combines with a time-of-day into a `PlainDateTime`. Still a wall-clock
        value — pass it to `PlainDateTime.to_zoned` to place it on the global
        timeline.

        # Parameters

        - `time`: the time-of-day to attach. Defaults to midnight
          (`00:00:00`); being defaulted it is named-only, so overriding it
          reads `d.to_plain_datetime(time = t)`."""
    async def to_plain_datetime_async(self, *, time: typing.Union[PlainTime, UNSET] = UNSET) -> PlainDateTime:
        """Combines with a time-of-day into a `PlainDateTime`. Still a wall-clock
        value — pass it to `PlainDateTime.to_zoned` to place it on the global
        timeline.

        # Parameters

        - `time`: the time-of-day to attach. Defaults to midnight
          (`00:00:00`); being defaulted it is named-only, so overriding it
          reads `d.to_plain_datetime(time = t)`."""
    def _to_plain_datetime_(self, time: int) -> PlainDateTime: ...
    async def _to_plain_datetime__async(self, time: int) -> PlainDateTime: ...
    def year(self) -> int:
        """The calendar year. Negative years follow ISO 8601's astronomical
        numbering, where year 0 is 1 BCE.

        # Throws

        - `baml.errors.InvalidArgument` if the date is outside the ±9999 year
          range.

        Raises:
            InvalidArgument"""
    async def year_async(self) -> int:
        """The calendar year. Negative years follow ISO 8601's astronomical
        numbering, where year 0 is 1 BCE.

        # Throws

        - `baml.errors.InvalidArgument` if the date is outside the ±9999 year
          range.

        Raises:
            InvalidArgument"""
    def month(self) -> int:
        """The calendar month, in `[1, 12]`. January is 1, not 0.

        # Throws

        - `baml.errors.InvalidArgument` if the date is outside the ±9999 year
          range.

        Raises:
            InvalidArgument"""
    async def month_async(self) -> int:
        """The calendar month, in `[1, 12]`. January is 1, not 0.

        # Throws

        - `baml.errors.InvalidArgument` if the date is outside the ±9999 year
          range.

        Raises:
            InvalidArgument"""
    def day(self) -> int:
        """The day of the month, in `[1, 31]`.

        # Throws

        - `baml.errors.InvalidArgument` if the date is outside the ±9999 year
          range.

        Raises:
            InvalidArgument"""
    async def day_async(self) -> int:
        """The day of the month, in `[1, 31]`.

        # Throws

        - `baml.errors.InvalidArgument` if the date is outside the ±9999 year
          range.

        Raises:
            InvalidArgument"""


class PlainDateTime(pydantic.BaseModel):
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    @staticmethod
    def from_components(year: int, month: int, day: int, *, hour: typing.Union[int, UNSET] = 0, minute: typing.Union[int, UNSET] = 0, second: typing.Union[int, UNSET] = 0, millisecond: typing.Union[int, UNSET] = 0, microsecond: typing.Union[int, UNSET] = 0, nanosecond: typing.Union[int, UNSET] = 0) -> PlainDateTime:
        """Creates a `PlainDateTime` from calendar and clock components.

        Every clock component is defaulted and therefore named-only:
        `PlainDateTime.from_components(1979, 5, 27, hour = 7)`.

        # Parameters

        - `year`: the proleptic Gregorian year, in `[-9999, 9999]`. Year 0 is
          1 BCE, following ISO 8601's astronomical numbering.
        - `month`: 1-based, in `[1, 12]`.
        - `day`: 1-based, and must exist in that month of that year.
        - `hour`: in `[0, 23]`.
        - `minute`, `second`: each in `[0, 59]`; there is no leap-second value.
        - `millisecond`, `microsecond`, `nanosecond`: each in `[0, 999]`, and
          each an independent digit group — the subsecond part is
          `millisecond * 1000000 + microsecond * 1000 + nanosecond`.

        # Throws

        - `baml.errors.InvalidArgument` if a component is out of range
          (e.g. month 13, Feb 30) or the year is outside ±9999.

        Raises:
            InvalidArgument"""
    @staticmethod
    async def from_components_async(year: int, month: int, day: int, *, hour: typing.Union[int, UNSET] = 0, minute: typing.Union[int, UNSET] = 0, second: typing.Union[int, UNSET] = 0, millisecond: typing.Union[int, UNSET] = 0, microsecond: typing.Union[int, UNSET] = 0, nanosecond: typing.Union[int, UNSET] = 0) -> PlainDateTime:
        """Creates a `PlainDateTime` from calendar and clock components.

        Every clock component is defaulted and therefore named-only:
        `PlainDateTime.from_components(1979, 5, 27, hour = 7)`.

        # Parameters

        - `year`: the proleptic Gregorian year, in `[-9999, 9999]`. Year 0 is
          1 BCE, following ISO 8601's astronomical numbering.
        - `month`: 1-based, in `[1, 12]`.
        - `day`: 1-based, and must exist in that month of that year.
        - `hour`: in `[0, 23]`.
        - `minute`, `second`: each in `[0, 59]`; there is no leap-second value.
        - `millisecond`, `microsecond`, `nanosecond`: each in `[0, 999]`, and
          each an independent digit group — the subsecond part is
          `millisecond * 1000000 + microsecond * 1000 + nanosecond`.

        # Throws

        - `baml.errors.InvalidArgument` if a component is out of range
          (e.g. month 13, Feb 30) or the year is outside ±9999.

        Raises:
            InvalidArgument"""
    @staticmethod
    def _from_components_(year: int, month: int, day: int, hour: int, minute: int, second: int, millisecond: int, microsecond: int, nanosecond: int) -> PlainDateTime:
        """Raises:
            InvalidArgument"""
    @staticmethod
    async def _from_components__async(year: int, month: int, day: int, hour: int, minute: int, second: int, millisecond: int, microsecond: int, nanosecond: int) -> PlainDateTime:
        """Raises:
            InvalidArgument"""
    @staticmethod
    def parse(s: str) -> PlainDateTime:
        """Raises:
            ParseError"""
    @staticmethod
    async def parse_async(s: str) -> PlainDateTime:
        """Raises:
            ParseError"""
    def _to_string_impl_(self) -> str:
        """(internal) ISO 8601 formatter, shared by `to_string` and `to_json` so
        the two agree byte for byte.

        # Throws

        - `baml.errors.InvalidArgument` if the year is outside ±9999.
          `baml.ToString.to_string` turns that into a panic, while `to_json`
          surfaces it as a `baml.json.SerializationError`.

        Raises:
            InvalidArgument"""
    async def _to_string_impl__async(self) -> str:
        """(internal) ISO 8601 formatter, shared by `to_string` and `to_json` so
        the two agree byte for byte.

        # Throws

        - `baml.errors.InvalidArgument` if the year is outside ±9999.
          `baml.ToString.to_string` turns that into a panic, while `to_json`
          surfaces it as a `baml.json.SerializationError`.

        Raises:
            InvalidArgument"""
    def to_zoned(self, timezone: typing.Union[TimeZoneOffset, str], *, disambiguation: typing.Union[Disambiguation, UNSET] = "compatible") -> ZonedDateTime:
        """Locates this wall-clock reading in a timezone, producing an absolute
        time. The counterpart of `ZonedDateTime.to_plain`.

        With a `TimeZoneOffset` the conversion is exact arithmetic: a fixed
        offset has no transitions, every civil reading maps to exactly one
        instant, and none of the failures below can arise. With an IANA
        identifier it is a lookup in the host's timezone database, and that
        mapping is not total — a spring-forward transition leaves a *gap* of
        readings that never happened, and a fall-back transition leaves an
        *overlap* of readings that happened twice. `disambiguation` decides what
        to do at both.

        # Parameters

        - `timezone`: a `TimeZoneOffset` for a fixed offset, or an IANA
          identifier such as `"America/Los_Angeles"`.
        - `disambiguation`: how to resolve a DST gap or overlap; see
          `Disambiguation`. Defaults to `"compatible"` and, being defaulted, is
          named-only: `dt.to_zoned(tz, disambiguation = "earlier")`. Ignored for
          a `TimeZoneOffset`, which can never be ambiguous.

        # Returns

        A `ZonedDateTime` carrying the resolved absolute time and the timezone
        as given — an IANA identifier stays an identifier, so the value keeps
        tracking that zone's future transitions rather than freezing today's
        offset.

        # Throws

        - `baml.time.UnknownTimezoneError` if `timezone` is a string the host's
          timezone database does not know.
        - `baml.time.AmbiguousTimeError` if `disambiguation` is `"reject"` and
          the reading falls in a gap or an overlap.
        - `baml.errors.Io` if the host's timezone database fails to resolve the
          reading, including when the civil value is outside the year range the
          host can represent.

        # Panics

        - `baml.panics.HostUnavailable` if the host has no timezone database at
          all. An unknown identifier is an error because the caller chose the
          identifier; a missing database is a property of the platform.

        Raises:
            UnknownTimezoneError, AmbiguousTimeError, Io"""
    async def to_zoned_async(self, timezone: typing.Union[TimeZoneOffset, str], *, disambiguation: typing.Union[Disambiguation, UNSET] = "compatible") -> ZonedDateTime:
        """Locates this wall-clock reading in a timezone, producing an absolute
        time. The counterpart of `ZonedDateTime.to_plain`.

        With a `TimeZoneOffset` the conversion is exact arithmetic: a fixed
        offset has no transitions, every civil reading maps to exactly one
        instant, and none of the failures below can arise. With an IANA
        identifier it is a lookup in the host's timezone database, and that
        mapping is not total — a spring-forward transition leaves a *gap* of
        readings that never happened, and a fall-back transition leaves an
        *overlap* of readings that happened twice. `disambiguation` decides what
        to do at both.

        # Parameters

        - `timezone`: a `TimeZoneOffset` for a fixed offset, or an IANA
          identifier such as `"America/Los_Angeles"`.
        - `disambiguation`: how to resolve a DST gap or overlap; see
          `Disambiguation`. Defaults to `"compatible"` and, being defaulted, is
          named-only: `dt.to_zoned(tz, disambiguation = "earlier")`. Ignored for
          a `TimeZoneOffset`, which can never be ambiguous.

        # Returns

        A `ZonedDateTime` carrying the resolved absolute time and the timezone
        as given — an IANA identifier stays an identifier, so the value keeps
        tracking that zone's future transitions rather than freezing today's
        offset.

        # Throws

        - `baml.time.UnknownTimezoneError` if `timezone` is a string the host's
          timezone database does not know.
        - `baml.time.AmbiguousTimeError` if `disambiguation` is `"reject"` and
          the reading falls in a gap or an overlap.
        - `baml.errors.Io` if the host's timezone database fails to resolve the
          reading, including when the civil value is outside the year range the
          host can represent.

        # Panics

        - `baml.panics.HostUnavailable` if the host has no timezone database at
          all. An unknown identifier is an error because the caller chose the
          identifier; a missing database is a property of the platform.

        Raises:
            UnknownTimezoneError, AmbiguousTimeError, Io"""
    def max(self, other: PlainDateTime) -> PlainDateTime:
        """The later of `self` and `other` on the clock face; `self` if they read
        the same.

        A civil comparison: both readings are compared as if in the same
        timezone. Two readings taken in different zones are not ordered by this
        — convert to `Instant` or `ZonedDateTime` first if absolute order is
        what you mean."""
    async def max_async(self, other: PlainDateTime) -> PlainDateTime:
        """The later of `self` and `other` on the clock face; `self` if they read
        the same.

        A civil comparison: both readings are compared as if in the same
        timezone. Two readings taken in different zones are not ordered by this
        — convert to `Instant` or `ZonedDateTime` first if absolute order is
        what you mean."""
    def min(self, other: PlainDateTime) -> PlainDateTime:
        """The earlier of `self` and `other` on the clock face; `self` if they read
        the same. A civil comparison, with the same caveat as `max`."""
    async def min_async(self, other: PlainDateTime) -> PlainDateTime:
        """The earlier of `self` and `other` on the clock face; `self` if they read
        the same. A civil comparison, with the same caveat as `max`."""
    def to_plain_date(self) -> PlainDate:
        """Raises:
            InvalidArgument"""
    async def to_plain_date_async(self) -> PlainDate:
        """Raises:
            InvalidArgument"""
    def to_plain_time(self) -> PlainTime: ...
    async def to_plain_time_async(self) -> PlainTime: ...
    def year(self) -> int:
        """The calendar year. Negative years follow ISO 8601's astronomical
        numbering, where year 0 is 1 BCE.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    async def year_async(self) -> int:
        """The calendar year. Negative years follow ISO 8601's astronomical
        numbering, where year 0 is 1 BCE.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    def month(self) -> int:
        """The calendar month, in `[1, 12]`. January is 1, not 0.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    async def month_async(self) -> int:
        """The calendar month, in `[1, 12]`. January is 1, not 0.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    def day(self) -> int:
        """The day of the month, in `[1, 31]`.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    async def day_async(self) -> int:
        """The day of the month, in `[1, 31]`.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    def hour(self) -> int:
        """The hour of the day, in `[0, 23]`. A 24-hour clock.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    async def hour_async(self) -> int:
        """The hour of the day, in `[0, 23]`. A 24-hour clock.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    def minute(self) -> int:
        """The minute of the hour, in `[0, 59]`.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    async def minute_async(self) -> int:
        """The minute of the hour, in `[0, 59]`.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    def second(self) -> int:
        """The second of the minute, in `[0, 59]`.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    async def second_async(self) -> int:
        """The second of the minute, in `[0, 59]`.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    def millisecond(self) -> int:
        """The millisecond of the second, in `[0, 999]`.

        The finer components `from_components` accepts — microsecond and
        nanosecond — have no accessor of their own; `to_string` renders them.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""
    async def millisecond_async(self) -> int:
        """The millisecond of the second, in `[0, 999]`.

        The finer components `from_components` accepts — microsecond and
        nanosecond — have no accessor of their own; `to_string` renders them.

        # Throws

        - `baml.errors.InvalidArgument` if the reading is outside ±9999.

        Raises:
            InvalidArgument"""


class PlainTime(pydantic.BaseModel):
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    @staticmethod
    def from_components(hour: int, *, minute: typing.Union[int, UNSET] = 0, second: typing.Union[int, UNSET] = 0, millisecond: typing.Union[int, UNSET] = 0, microsecond: typing.Union[int, UNSET] = 0, nanosecond: typing.Union[int, UNSET] = 0) -> PlainTime:
        """Creates a `PlainTime` from clock components.

        Every component but `hour` is defaulted and therefore named-only:
        `PlainTime.from_components(7, minute = 32)`.

        # Parameters

        - `hour`: in `[0, 23]`.
        - `minute`: in `[0, 59]`.
        - `second`: in `[0, 59]`; there is no leap-second value.
        - `millisecond`, `microsecond`, `nanosecond`: each in `[0, 999]`, and
          each an independent digit group — the subsecond part is
          `millisecond * 1000000 + microsecond * 1000 + nanosecond`, not three
          spellings of the same field.

        # Throws

        - `baml.errors.InvalidArgument` if a component is out of range
          (e.g. hour 24, minute 60).

        Raises:
            InvalidArgument"""
    @staticmethod
    async def from_components_async(hour: int, *, minute: typing.Union[int, UNSET] = 0, second: typing.Union[int, UNSET] = 0, millisecond: typing.Union[int, UNSET] = 0, microsecond: typing.Union[int, UNSET] = 0, nanosecond: typing.Union[int, UNSET] = 0) -> PlainTime:
        """Creates a `PlainTime` from clock components.

        Every component but `hour` is defaulted and therefore named-only:
        `PlainTime.from_components(7, minute = 32)`.

        # Parameters

        - `hour`: in `[0, 23]`.
        - `minute`: in `[0, 59]`.
        - `second`: in `[0, 59]`; there is no leap-second value.
        - `millisecond`, `microsecond`, `nanosecond`: each in `[0, 999]`, and
          each an independent digit group — the subsecond part is
          `millisecond * 1000000 + microsecond * 1000 + nanosecond`, not three
          spellings of the same field.

        # Throws

        - `baml.errors.InvalidArgument` if a component is out of range
          (e.g. hour 24, minute 60).

        Raises:
            InvalidArgument"""
    @staticmethod
    def _from_components_(hour: int, minute: int, second: int, millisecond: int, microsecond: int, nanosecond: int) -> PlainTime:
        """Raises:
            InvalidArgument"""
    @staticmethod
    async def _from_components__async(hour: int, minute: int, second: int, millisecond: int, microsecond: int, nanosecond: int) -> PlainTime:
        """Raises:
            InvalidArgument"""
    @staticmethod
    def parse(s: str) -> PlainTime:
        """Raises:
            ParseError"""
    @staticmethod
    async def parse_async(s: str) -> PlainTime:
        """Raises:
            ParseError"""
    def _to_string_impl_(self) -> str:
        """(internal) ISO 8601 time-of-day formatter behind `to_string`.

        Infallible: it reduces the nanosecond count into `[0, 24h)` before
        formatting, so even a `PlainTime` assembled field-by-field outside the
        class invariant renders rather than failing."""
    async def _to_string_impl__async(self) -> str:
        """(internal) ISO 8601 time-of-day formatter behind `to_string`.

        Infallible: it reduces the nanosecond count into `[0, 24h)` before
        formatting, so even a `PlainTime` assembled field-by-field outside the
        class invariant renders rather than failing."""
    def to_plain_datetime(self, date: PlainDate) -> PlainDateTime:
        """Combines with a date into a `PlainDateTime`, the mirror image of
        `PlainDate.to_plain_datetime`. Still a wall-clock value — pass it to
        `PlainDateTime.to_zoned` to place it on the global timeline.

        # Examples

        ```baml
        let time = baml.time.PlainTime.parse("12:34:56");
        let date = baml.time.PlainDate.parse("2025-01-01");
        let datetime = time.to_plain_datetime(date);
        assert.equal(datetime, baml.time.PlainDateTime.parse("2025-01-01T12:34:56"));
        ```"""
    async def to_plain_datetime_async(self, date: PlainDate) -> PlainDateTime:
        """Combines with a date into a `PlainDateTime`, the mirror image of
        `PlainDate.to_plain_datetime`. Still a wall-clock value — pass it to
        `PlainDateTime.to_zoned` to place it on the global timeline.

        # Examples

        ```baml
        let time = baml.time.PlainTime.parse("12:34:56");
        let date = baml.time.PlainDate.parse("2025-01-01");
        let datetime = time.to_plain_datetime(date);
        assert.equal(datetime, baml.time.PlainDateTime.parse("2025-01-01T12:34:56"));
        ```"""
    def hour(self) -> int:
        """The hour of the day, in `[0, 23]`. A 24-hour clock, so there is no am/pm
        distinction to lose."""
    async def hour_async(self) -> int:
        """The hour of the day, in `[0, 23]`. A 24-hour clock, so there is no am/pm
        distinction to lose."""
    def minute(self) -> int:
        """The minute of the hour, in `[0, 59]`."""
    async def minute_async(self) -> int:
        """The minute of the hour, in `[0, 59]`."""
    def second(self) -> int:
        """The second of the minute, in `[0, 59]`."""
    async def second_async(self) -> int:
        """The second of the minute, in `[0, 59]`."""
    def millisecond(self) -> int:
        """The millisecond of the second, in `[0, 999]`.

        The finer components `from_components` accepts — microsecond and
        nanosecond — have no accessor of their own; `to_string` renders them."""
    async def millisecond_async(self) -> int:
        """The millisecond of the second, in `[0, 999]`.

        The finer components `from_components` accepts — microsecond and
        nanosecond — have no accessor of their own; `to_string` renders them."""


def _wrap_into_day(total_ns: int) -> int:
    """(internal) Reduces `total_ns` to nanoseconds-since-midnight in `[0, 24h)`,
    re-establishing `PlainTime._nanoseconds`'s invariant after arithmetic.

    Written `((n % day) + day) % day` rather than `n % day` because `%` keeps
    the sign of its left operand: a negative `total_ns` would otherwise stay
    negative.

    # Returns

    The wrapped count, always in `[0, 24h)` and therefore always an `int`."""
async def _wrap_into_day_async(total_ns: int) -> int:
    """(internal) Reduces `total_ns` to nanoseconds-since-midnight in `[0, 24h)`,
    re-establishing `PlainTime._nanoseconds`'s invariant after arithmetic.

    Written `((n % day) + day) % day` rather than `n % day` because `%` keeps
    the sign of its left operand: a negative `total_ns` would otherwise stay
    negative.

    # Returns

    The wrapped count, always in `[0, 24h)` and therefore always an `int`."""


class UnknownTimezoneError(pydantic.BaseModel):
    timezone: str


class AmbiguousTimeError(pydantic.BaseModel):
    message: str


class TimeZoneOffset(pydantic.BaseModel):
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    @staticmethod
    def utc() -> TimeZoneOffset:
        """The UTC (zero) offset."""
    @staticmethod
    async def utc_async() -> TimeZoneOffset:
        """The UTC (zero) offset."""
    @staticmethod
    def new(hours: int, minutes: int) -> TimeZoneOffset:
        """Creates a `TimeZoneOffset` from hours and minutes east of UTC.

        # Parameters

        - `hours`: whole hours east of UTC; negative west of it.
        - `minutes`: the sub-hour part, which must carry the same sign as
          `hours` — the pair is one signed quantity split in two, not an hour
          count plus an unsigned remainder. So `new(-9, -30)` is `-09:30`, while
          `new(-9, 30)` is rejected rather than silently read as `-08:30`.
          `new(-7, 0)` and `new(5, 30)` are the ordinary cases.

        # Throws

        - `baml.errors.InvalidArgument` if the signs differ, or the result
          exceeds ±24 hours.

        # Panics

        - `baml.panics.IntegerOverflow` if `hours` or `minutes` is so large that
          converting it to nanoseconds overflows `int`. The range check happens
          after that conversion, so it never sees these.

        Raises:
            InvalidArgument"""
    @staticmethod
    async def new_async(hours: int, minutes: int) -> TimeZoneOffset:
        """Creates a `TimeZoneOffset` from hours and minutes east of UTC.

        # Parameters

        - `hours`: whole hours east of UTC; negative west of it.
        - `minutes`: the sub-hour part, which must carry the same sign as
          `hours` — the pair is one signed quantity split in two, not an hour
          count plus an unsigned remainder. So `new(-9, -30)` is `-09:30`, while
          `new(-9, 30)` is rejected rather than silently read as `-08:30`.
          `new(-7, 0)` and `new(5, 30)` are the ordinary cases.

        # Throws

        - `baml.errors.InvalidArgument` if the signs differ, or the result
          exceeds ±24 hours.

        # Panics

        - `baml.panics.IntegerOverflow` if `hours` or `minutes` is so large that
          converting it to nanoseconds overflows `int`. The range check happens
          after that conversion, so it never sees these.

        Raises:
            InvalidArgument"""
    @staticmethod
    def from_timezone(timezone: str, at: Instant) -> TimeZoneOffset:
        """Resolves an IANA timezone identifier (e.g. `"America/Los_Angeles"`) to
        its concrete offset at the absolute time `at`, daylight saving included.

        Resolution uses the host's timezone database. The answer is a snapshot
        of the offset that zone had at `at`, and must not be reused for a
        different moment.

        # Parameters

        - `timezone`: an IANA identifier.
        - `at`: the absolute time to resolve at. An `Instant` rather than a
          civil reading, so the query is never itself ambiguous.

        # Throws

        - `baml.time.UnknownTimezoneError` if the timezone is invalid.

        # Panics

        - `baml.panics.HostUnavailable` if timezone data is unavailable.

        Raises:
            UnknownTimezoneError"""
    @staticmethod
    async def from_timezone_async(timezone: str, at: Instant) -> TimeZoneOffset:
        """Resolves an IANA timezone identifier (e.g. `"America/Los_Angeles"`) to
        its concrete offset at the absolute time `at`, daylight saving included.

        Resolution uses the host's timezone database. The answer is a snapshot
        of the offset that zone had at `at`, and must not be reused for a
        different moment.

        # Parameters

        - `timezone`: an IANA identifier.
        - `at`: the absolute time to resolve at. An `Instant` rather than a
          civil reading, so the query is never itself ambiguous.

        # Throws

        - `baml.time.UnknownTimezoneError` if the timezone is invalid.

        # Panics

        - `baml.panics.HostUnavailable` if timezone data is unavailable.

        Raises:
            UnknownTimezoneError"""
    @staticmethod
    def local() -> TimeZoneOffset:
        """The system timezone's offset as of right now.

        Even in one location this varies over time with daylight saving, so the
        result is a snapshot rather than a stand-in for the system timezone
        itself. Keep `system_timezone()`'s identifier where the value has to
        stay correct across a transition.

        # Throws

        - `baml.time.UnknownTimezoneError` if the host names a system timezone
          its own timezone database then fails to resolve.
        - `baml.errors.Io` if the host has a timezone database but cannot tell
          which zone it is configured for.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock, or no
          timezone database at all.

        Raises:
            UnknownTimezoneError, Io"""
    @staticmethod
    async def local_async() -> TimeZoneOffset:
        """The system timezone's offset as of right now.

        Even in one location this varies over time with daylight saving, so the
        result is a snapshot rather than a stand-in for the system timezone
        itself. Keep `system_timezone()`'s identifier where the value has to
        stay correct across a transition.

        # Throws

        - `baml.time.UnknownTimezoneError` if the host names a system timezone
          its own timezone database then fails to resolve.
        - `baml.errors.Io` if the host has a timezone database but cannot tell
          which zone it is configured for.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock, or no
          timezone database at all.

        Raises:
            UnknownTimezoneError, Io"""
    @staticmethod
    def from_duration(duration: Duration) -> TimeZoneOffset:
        """Raises:
            InvalidArgument"""
    @staticmethod
    async def from_duration_async(duration: Duration) -> TimeZoneOffset:
        """Raises:
            InvalidArgument"""
    def to_duration(self) -> Duration:
        """The offset as a `Duration` east of UTC; negative west of it. Exact, and
        the inverse of `from_duration`."""
    async def to_duration_async(self) -> Duration:
        """The offset as a `Duration` east of UTC; negative west of it. Exact, and
        the inverse of `from_duration`."""
    def hours(self) -> int:
        """The hour component of the offset, truncated toward zero. Negative for an
        offset west of UTC."""
    async def hours_async(self) -> int:
        """The hour component of the offset, truncated toward zero. Negative for an
        offset west of UTC."""
    def minutes(self) -> int:
        """The minute component of the offset within its hour, truncated toward
        zero.

        Signed like `hours`, and for the same reason: the two are one signed
        quantity split in two, so `-09:30` reads back as `hours() == -9` and
        `minutes() == -30`. Neither reports any sub-minute part of the offset."""
    async def minutes_async(self) -> int:
        """The minute component of the offset within its hour, truncated toward
        zero.

        Signed like `hours`, and for the same reason: the two are one signed
        quantity split in two, so `-09:30` reads back as `hours() == -9` and
        `minutes() == -30`. Neither reports any sub-minute part of the offset."""


def system_timezone() -> str:
    """The system's IANA timezone identifier, for example
    `"America/Los_Angeles"`. Mirrors `Temporal.Now.timeZoneId()`.

    An IO function, so hosts can swap the system-state source out.

    # Throws

    - `baml.errors.Io` if the host has a timezone database but cannot tell which
      zone it is configured for — an unset or unrecognized system setting, which
      a caller can reasonably fall back from (say, to UTC).

    # Panics

    - `baml.panics.HostUnavailable` if the host provides no timezone database at
      all. Nothing the caller could have done differently, so it takes the panic
      channel rather than the error one.

    Raises:
        Io"""
async def system_timezone_async() -> str:
    """The system's IANA timezone identifier, for example
    `"America/Los_Angeles"`. Mirrors `Temporal.Now.timeZoneId()`.

    An IO function, so hosts can swap the system-state source out.

    # Throws

    - `baml.errors.Io` if the host has a timezone database but cannot tell which
      zone it is configured for — an unset or unrecognized system setting, which
      a caller can reasonably fall back from (say, to UTC).

    # Panics

    - `baml.panics.HostUnavailable` if the host provides no timezone database at
      all. Nothing the caller could have done differently, so it takes the panic
      channel rather than the error one.

    Raises:
        Io"""


def _tz_offset_at(timezone: str, at_ns: int) -> typing.Optional[int]: ...
async def _tz_offset_at_async(timezone: str, at_ns: int) -> typing.Optional[int]: ...


def _tz_to_instant(timezone: str, civil_ns: int, disambiguation: str) -> typing.Optional[int]:
    """(internal) Locates a civil ("wall-clock") reading in an IANA timezone,
    producing an absolute time. The lookup behind `PlainDateTime.to_zoned`.

    # Parameters

    - `timezone`: an IANA identifier.
    - `civil_ns`: the wall-clock reading as nanoseconds since
      1970-01-01T00:00:00, interpreted as if UTC — the encoding
      `PlainDateTime._nanoseconds` uses.
    - `disambiguation`: `"compatible"`, `"earlier"` or `"later"`. Any other
      string is treated as `"compatible"`. `"reject"` never reaches here:
      callers implement it by resolving both `"earlier"` and `"later"` and
      requiring them to agree.

    # Returns

    The resolved absolute time as nanoseconds since the Unix epoch, or `null` if
    the identifier is unknown to the host's timezone database (callers turn that
    into `baml.time.UnknownTimezoneError`).

    # Throws

    - `baml.errors.Io` if the reading is outside the year range the host can
      represent, or the host's timezone database fails to resolve it.

    # Panics

    - `baml.panics.HostUnavailable` if timezone data is unavailable.

    Raises:
        Io"""
async def _tz_to_instant_async(timezone: str, civil_ns: int, disambiguation: str) -> typing.Optional[int]:
    """(internal) Locates a civil ("wall-clock") reading in an IANA timezone,
    producing an absolute time. The lookup behind `PlainDateTime.to_zoned`.

    # Parameters

    - `timezone`: an IANA identifier.
    - `civil_ns`: the wall-clock reading as nanoseconds since
      1970-01-01T00:00:00, interpreted as if UTC — the encoding
      `PlainDateTime._nanoseconds` uses.
    - `disambiguation`: `"compatible"`, `"earlier"` or `"later"`. Any other
      string is treated as `"compatible"`. `"reject"` never reaches here:
      callers implement it by resolving both `"earlier"` and `"later"` and
      requiring them to agree.

    # Returns

    The resolved absolute time as nanoseconds since the Unix epoch, or `null` if
    the identifier is unknown to the host's timezone database (callers turn that
    into `baml.time.UnknownTimezoneError`).

    # Throws

    - `baml.errors.Io` if the reading is outside the year range the host can
      represent, or the host's timezone database fails to resolve it.

    # Panics

    - `baml.panics.HostUnavailable` if timezone data is unavailable.

    Raises:
        Io"""


class ZonedDateTime(pydantic.BaseModel):
    field_nanoseconds: int = pydantic.Field(alias="_nanoseconds")
    field_offset_ns: typing.Optional[int] = pydantic.Field(default=None, alias="_offset_ns")
    field_iana: typing.Optional[str] = pydantic.Field(default=None, alias="_iana")
    @staticmethod
    def now() -> ZonedDateTime:
        """The current time in the system timezone, kept as an IANA identifier
        (e.g. `"America/Los_Angeles"`) rather than as today's offset. Mirrors
        `Temporal.Now.zonedDateTimeISO()`.

        # Throws

        - `baml.errors.Io` if the host has a timezone database but cannot tell
          which zone it is configured for.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock, or no
          timezone database at all.

        Raises:
            Io"""
    @staticmethod
    async def now_async() -> ZonedDateTime:
        """The current time in the system timezone, kept as an IANA identifier
        (e.g. `"America/Los_Angeles"`) rather than as today's offset. Mirrors
        `Temporal.Now.zonedDateTimeISO()`.

        # Throws

        - `baml.errors.Io` if the host has a timezone database but cannot tell
          which zone it is configured for.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock, or no
          timezone database at all.

        Raises:
            Io"""
    @staticmethod
    def now_in(timezone: typing.Union[TimeZoneOffset, str]) -> ZonedDateTime:
        """The current time in `timezone`.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock."""
    @staticmethod
    async def now_in_async(timezone: typing.Union[TimeZoneOffset, str]) -> ZonedDateTime:
        """The current time in `timezone`.

        # Panics

        - `baml.panics.HostUnavailable` if the host provides no clock."""
    @staticmethod
    def from_instant(instant: Instant, timezone: typing.Union[TimeZoneOffset, str]) -> ZonedDateTime:
        """Pairs an absolute time with a timezone, without moving it: the result
        denotes the same moment `instant` does, and only its date and time
        components and its rendering differ.

        Total, and never ambiguous — a gap or an overlap is a property of a
        civil reading, and this starts from an absolute time.

        # Examples

        ```baml
        ZonedDateTime.from_instant(Instant.now(), "America/Los_Angeles")
        ```"""
    @staticmethod
    async def from_instant_async(instant: Instant, timezone: typing.Union[TimeZoneOffset, str]) -> ZonedDateTime:
        """Pairs an absolute time with a timezone, without moving it: the result
        denotes the same moment `instant` does, and only its date and time
        components and its rendering differ.

        Total, and never ambiguous — a gap or an overlap is a property of a
        civil reading, and this starts from an absolute time.

        # Examples

        ```baml
        ZonedDateTime.from_instant(Instant.now(), "America/Los_Angeles")
        ```"""
    @staticmethod
    def from_components(timezone: typing.Union[TimeZoneOffset, str], year: int, month: int, day: int, *, hour: typing.Union[int, UNSET] = 0, minute: typing.Union[int, UNSET] = 0, second: typing.Union[int, UNSET] = 0, millisecond: typing.Union[int, UNSET] = 0, microsecond: typing.Union[int, UNSET] = 0, nanosecond: typing.Union[int, UNSET] = 0, disambiguation: typing.Union[Disambiguation, UNSET] = "compatible") -> ZonedDateTime:
        """Creates a `ZonedDateTime` from calendar and clock components read in
        `timezone` — i.e. from a wall-clock reading someone in that zone would
        give you.

        Equivalent to building a `PlainDateTime` from the same components and
        calling `to_zoned` on it, and it inherits that method's DST handling.

        Every clock component and `disambiguation` are defaulted and therefore
        named-only: `ZonedDateTime.from_components(tz, 1979, 5, 27, hour = 7)`.

        # Parameters

        - `timezone`: a `TimeZoneOffset` for a fixed offset, or an IANA
          identifier. Leads rather than trails the components because the
          components are meaningless without it.
        - `year`: the proleptic Gregorian year, in `[-9999, 9999]`.
        - `month`: 1-based, in `[1, 12]`.
        - `day`: 1-based, and must exist in that month of that year.
        - `hour`: in `[0, 23]`.
        - `minute`, `second`: each in `[0, 59]`.
        - `millisecond`, `microsecond`, `nanosecond`: each in `[0, 999]`, and
          each an independent digit group.
        - `disambiguation`: how to resolve a DST gap or overlap; see
          `Disambiguation`. Ignored for a `TimeZoneOffset`.

        # Throws

        - `baml.errors.InvalidArgument` if a component is out of range.
        - `baml.time.UnknownTimezoneError` if `timezone` is a string the host's
          timezone database does not know.
        - `baml.time.AmbiguousTimeError` if `disambiguation` is `"reject"` and
          the reading falls in a DST gap or overlap.
        - `baml.errors.Io` if the host's timezone database fails to resolve the
          reading.

        # Panics

        - `baml.panics.HostUnavailable` if the host has no timezone database at
          all.

        Raises:
            InvalidArgument, UnknownTimezoneError, AmbiguousTimeError, Io"""
    @staticmethod
    async def from_components_async(timezone: typing.Union[TimeZoneOffset, str], year: int, month: int, day: int, *, hour: typing.Union[int, UNSET] = 0, minute: typing.Union[int, UNSET] = 0, second: typing.Union[int, UNSET] = 0, millisecond: typing.Union[int, UNSET] = 0, microsecond: typing.Union[int, UNSET] = 0, nanosecond: typing.Union[int, UNSET] = 0, disambiguation: typing.Union[Disambiguation, UNSET] = "compatible") -> ZonedDateTime:
        """Creates a `ZonedDateTime` from calendar and clock components read in
        `timezone` — i.e. from a wall-clock reading someone in that zone would
        give you.

        Equivalent to building a `PlainDateTime` from the same components and
        calling `to_zoned` on it, and it inherits that method's DST handling.

        Every clock component and `disambiguation` are defaulted and therefore
        named-only: `ZonedDateTime.from_components(tz, 1979, 5, 27, hour = 7)`.

        # Parameters

        - `timezone`: a `TimeZoneOffset` for a fixed offset, or an IANA
          identifier. Leads rather than trails the components because the
          components are meaningless without it.
        - `year`: the proleptic Gregorian year, in `[-9999, 9999]`.
        - `month`: 1-based, in `[1, 12]`.
        - `day`: 1-based, and must exist in that month of that year.
        - `hour`: in `[0, 23]`.
        - `minute`, `second`: each in `[0, 59]`.
        - `millisecond`, `microsecond`, `nanosecond`: each in `[0, 999]`, and
          each an independent digit group.
        - `disambiguation`: how to resolve a DST gap or overlap; see
          `Disambiguation`. Ignored for a `TimeZoneOffset`.

        # Throws

        - `baml.errors.InvalidArgument` if a component is out of range.
        - `baml.time.UnknownTimezoneError` if `timezone` is a string the host's
          timezone database does not know.
        - `baml.time.AmbiguousTimeError` if `disambiguation` is `"reject"` and
          the reading falls in a DST gap or overlap.
        - `baml.errors.Io` if the host's timezone database fails to resolve the
          reading.

        # Panics

        - `baml.panics.HostUnavailable` if the host has no timezone database at
          all.

        Raises:
            InvalidArgument, UnknownTimezoneError, AmbiguousTimeError, Io"""
    @staticmethod
    def parse(s: str) -> ZonedDateTime:
        """Raises:
            ParseError"""
    @staticmethod
    async def parse_async(s: str) -> ZonedDateTime:
        """Raises:
            ParseError"""
    def to_instant(self) -> Instant:
        """The absolute time, dropping the timezone. The inverse of `from_instant`,
        and infallible for the same reason: the absolute time is what is stored,
        so no timezone database is consulted.

        Contrast `to_plain`, which keeps the components and drops the moment."""
    async def to_instant_async(self) -> Instant:
        """The absolute time, dropping the timezone. The inverse of `from_instant`,
        and infallible for the same reason: the absolute time is what is stored,
        so no timezone database is consulted.

        Contrast `to_plain`, which keeps the components and drops the moment."""
    def max(self, other: ZonedDateTime) -> ZonedDateTime:
        """The later of `self` and `other`; `self` if they name the same moment.

        An absolute-time comparison, so it is meaningful across timezones: the
        two values need not share one, and the timezone of the winner comes
        along unchanged. No timezone database is consulted."""
    async def max_async(self, other: ZonedDateTime) -> ZonedDateTime:
        """The later of `self` and `other`; `self` if they name the same moment.

        An absolute-time comparison, so it is meaningful across timezones: the
        two values need not share one, and the timezone of the winner comes
        along unchanged. No timezone database is consulted."""
    def min(self, other: ZonedDateTime) -> ZonedDateTime:
        """The earlier of `self` and `other`; `self` if they name the same moment.
        An absolute-time comparison, with the same properties as `max`."""
    async def min_async(self, other: ZonedDateTime) -> ZonedDateTime:
        """The earlier of `self` and `other`; `self` if they name the same moment.
        An absolute-time comparison, with the same properties as `max`."""
    def with_timezone(self, timezone: typing.Union[TimeZoneOffset, str]) -> ZonedDateTime:
        """The same moment, presented in a different timezone: the date and time
        components change, the instant does not.

        A re-labelling, not a shift — `with_timezone` never moves the value
        along the timeline, so it cannot land in a DST gap and takes no
        `Disambiguation`. To keep the *components* and change the moment, go
        through `to_plain` and `PlainDateTime.to_zoned` instead."""
    async def with_timezone_async(self, timezone: typing.Union[TimeZoneOffset, str]) -> ZonedDateTime:
        """The same moment, presented in a different timezone: the date and time
        components change, the instant does not.

        A re-labelling, not a shift — `with_timezone` never moves the value
        along the timeline, so it cannot land in a DST gap and takes no
        `Disambiguation`. To keep the *components* and change the moment, go
        through `to_plain` and `PlainDateTime.to_zoned` instead."""
    def timezone(self) -> typing.Union[TimeZoneOffset, str]:
        """The timezone, in whichever form it was supplied: a `TimeZoneOffset` if
        fixed, or the IANA identifier as a `string`. Use `timezone_offset` for
        the concrete offset either way."""
    async def timezone_async(self) -> typing.Union[TimeZoneOffset, str]:
        """The timezone, in whichever form it was supplied: a `TimeZoneOffset` if
        fixed, or the IANA identifier as a `string`. Use `timezone_offset` for
        the concrete offset either way."""
    def timezone_offset(self) -> TimeZoneOffset:
        """The concrete `TimeZoneOffset` in effect at this moment.

        A fixed offset is returned as-is. An IANA identifier is resolved against
        the host's timezone database at `self`'s absolute time, so the answer is
        DST-aware and specific to this moment — the same value's offset six
        months later may differ.

        # Throws

        - `baml.time.UnknownTimezoneError` if the timezone is an unknown IANA
          identifier.

        # Panics

        - `baml.panics.HostUnavailable` if timezone data is unavailable.

        Raises:
            UnknownTimezoneError"""
    async def timezone_offset_async(self) -> TimeZoneOffset:
        """The concrete `TimeZoneOffset` in effect at this moment.

        A fixed offset is returned as-is. An IANA identifier is resolved against
        the host's timezone database at `self`'s absolute time, so the answer is
        DST-aware and specific to this moment — the same value's offset six
        months later may differ.

        # Throws

        - `baml.time.UnknownTimezoneError` if the timezone is an unknown IANA
          identifier.

        # Panics

        - `baml.panics.HostUnavailable` if timezone data is unavailable.

        Raises:
            UnknownTimezoneError"""
    def to_plain(self) -> PlainDateTime:
        """Drops the timezone, keeping the wall-clock reading a local observer
        would give. The counterpart of `PlainDateTime.to_zoned`, and the
        opposite trade from `to_instant`, which keeps the moment and drops the
        components.

        Resolving the reading needs the offset in effect at this moment, so this
        consults the host's timezone database whenever the timezone is an IANA
        identifier.

        Lossy: converting back with `to_zoned` recovers `self` only when the
        reading is unambiguous in that zone. During a fall-back overlap the same
        reading names two moments, and only one comes back.

        # Throws

        - `baml.time.UnknownTimezoneError` if the timezone is an IANA identifier
          the host does not know.

        # Panics

        - `baml.panics.HostUnavailable` if the timezone is an IANA identifier
          and the host has no timezone database.

        Raises:
            UnknownTimezoneError"""
    async def to_plain_async(self) -> PlainDateTime:
        """Drops the timezone, keeping the wall-clock reading a local observer
        would give. The counterpart of `PlainDateTime.to_zoned`, and the
        opposite trade from `to_instant`, which keeps the moment and drops the
        components.

        Resolving the reading needs the offset in effect at this moment, so this
        consults the host's timezone database whenever the timezone is an IANA
        identifier.

        Lossy: converting back with `to_zoned` recovers `self` only when the
        reading is unambiguous in that zone. During a fall-back overlap the same
        reading names two moments, and only one comes back.

        # Throws

        - `baml.time.UnknownTimezoneError` if the timezone is an IANA identifier
          the host does not know.

        # Panics

        - `baml.panics.HostUnavailable` if the timezone is an IANA identifier
          and the host has no timezone database.

        Raises:
            UnknownTimezoneError"""
    def year(self) -> int:
        """The calendar year as read in this timezone.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    async def year_async(self) -> int:
        """The calendar year as read in this timezone.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    def month(self) -> int:
        """The calendar month, in `[1, 12]`, as read in this timezone.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    async def month_async(self) -> int:
        """The calendar month, in `[1, 12]`, as read in this timezone.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    def day(self) -> int:
        """The day of the month, in `[1, 31]`, as read in this timezone.

        This is the *local* day: the same moment can fall on different dates in
        two timezones.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    async def day_async(self) -> int:
        """The day of the month, in `[1, 31]`, as read in this timezone.

        This is the *local* day: the same moment can fall on different dates in
        two timezones.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    def hour(self) -> int:
        """The hour of the day, in `[0, 23]`, as read in this timezone.

        Across a DST transition this is not a continuous function of the
        absolute time: an hour is skipped in spring and repeated in autumn.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    async def hour_async(self) -> int:
        """The hour of the day, in `[0, 23]`, as read in this timezone.

        Across a DST transition this is not a continuous function of the
        absolute time: an hour is skipped in spring and repeated in autumn.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    def minute(self) -> int:
        """The minute of the hour, in `[0, 59]`, as read in this timezone.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    async def minute_async(self) -> int:
        """The minute of the hour, in `[0, 59]`, as read in this timezone.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    def second(self) -> int:
        """The second of the minute, in `[0, 59]`, as read in this timezone.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    async def second_async(self) -> int:
        """The second of the minute, in `[0, 59]`, as read in this timezone.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    def millisecond(self) -> int:
        """The millisecond of the second, in `[0, 999]`, as read in this timezone.

        The finer components have no accessor of their own; `to_string` renders
        them.

        Raises:
            InvalidArgument, UnknownTimezoneError"""
    async def millisecond_async(self) -> int:
        """The millisecond of the second, in `[0, 999]`, as read in this timezone.

        The finer components have no accessor of their own; `to_string` renders
        them.

        Raises:
            InvalidArgument, UnknownTimezoneError"""


def _format_zoned(epoch_ns: int, offset_ns: int, iana: typing.Optional[str]) -> str:
    """(internal) Formats an absolute time as RFC 3339 at the given offset,
    appending an RFC 9557 `[iana]` annotation when `iana` is non-null.

    Takes the offset already resolved rather than resolving it itself, so the
    timezone-database lookup stays in BAML where its failure can be routed to
    either channel — `to_string` panics, `to_json` throws.

    # Parameters

    - `epoch_ns`: the absolute time, in nanoseconds since the Unix epoch.
    - `offset_ns`: the offset to render at, in nanoseconds east of UTC. Any
      sub-minute part is truncated toward zero, since RFC 3339 offsets are
      `±hh:mm`.
    - `iana`: the identifier for the bracketed annotation, or `null` for a fixed
      offset. Its presence also decides the zero-offset spelling: `Z` for a
      fixed offset, `+00:00` alongside the annotation otherwise — the way
      Temporal serializes.

    # Throws

    - `baml.errors.InvalidArgument` if the local reading is outside the
      supported ±9999 year range.

    Raises:
        InvalidArgument"""
async def _format_zoned_async(epoch_ns: int, offset_ns: int, iana: typing.Optional[str]) -> str:
    """(internal) Formats an absolute time as RFC 3339 at the given offset,
    appending an RFC 9557 `[iana]` annotation when `iana` is non-null.

    Takes the offset already resolved rather than resolving it itself, so the
    timezone-database lookup stays in BAML where its failure can be routed to
    either channel — `to_string` panics, `to_json` throws.

    # Parameters

    - `epoch_ns`: the absolute time, in nanoseconds since the Unix epoch.
    - `offset_ns`: the offset to render at, in nanoseconds east of UTC. Any
      sub-minute part is truncated toward zero, since RFC 3339 offsets are
      `±hh:mm`.
    - `iana`: the identifier for the bracketed annotation, or `null` for a fixed
      offset. Its presence also decides the zero-offset spelling: `Z` for a
      fixed offset, `+00:00` alongside the annotation otherwise — the way
      Temporal serializes.

    # Throws

    - `baml.errors.InvalidArgument` if the local reading is outside the
      supported ±9999 year range.

    Raises:
        InvalidArgument"""


__all__ = [
    "Disambiguation",
    "Duration",
    "Instant",
    "PlainDate",
    "PlainDateTime",
    "PlainTime",
    "UnknownTimezoneError",
    "AmbiguousTimeError",
    "TimeZoneOffset",
    "system_timezone",
    "system_timezone_async",
    "ZonedDateTime",
]
