# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

if typing.TYPE_CHECKING:
    from ... import baml
    from ...baml import UNSET as UNSET

from baml_bridge import BamlPyHandle as _BamlPyHandle


class TcpStream(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    @staticmethod
    def connect(addr: str, *, timeout: typing.Union[baml.time.Duration, None, UNSET] = None) -> TcpStream:
        """Opens a TCP connection to `addr` (e.g. `"127.0.0.1:8080"`) and returns the stream.

        `timeout` bounds how long to wait for the connection to be established;
        `null` (the default) waits indefinitely (subject to the OS default). On
        expiry this throws `baml.errors.Timeout`.

        Raises:
            Io, Timeout"""
    @staticmethod
    async def connect_async(addr: str, *, timeout: typing.Union[baml.time.Duration, None, UNSET] = None) -> TcpStream:
        """Opens a TCP connection to `addr` (e.g. `"127.0.0.1:8080"`) and returns the stream.

        `timeout` bounds how long to wait for the connection to be established;
        `null` (the default) waits indefinitely (subject to the OS default). On
        expiry this throws `baml.errors.Timeout`.

        Raises:
            Io, Timeout"""
    @staticmethod
    def _connect_(addr: str, timeout_nanos: int) -> TcpStream:
        """(internal)

        Raises:
            Io, Timeout"""
    @staticmethod
    async def _connect__async(addr: str, timeout_nanos: int) -> TcpStream:
        """(internal)

        Raises:
            Io, Timeout"""
    def close(self) -> None:
        """Closes the connection.

        Raises:
            Io"""
    async def close_async(self) -> None:
        """Closes the connection.

        Raises:
            Io"""


class TcpListener(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    @staticmethod
    def bind(addr: str) -> TcpListener:
        """Binds to `addr` (e.g. `"127.0.0.1:8080"`) and returns a listener ready to
        accept incoming connections.

        Raises:
            Io"""
    @staticmethod
    async def bind_async(addr: str) -> TcpListener:
        """Binds to `addr` (e.g. `"127.0.0.1:8080"`) and returns a listener ready to
        accept incoming connections.

        Raises:
            Io"""
    def accept(self) -> TcpStream:
        """Waits for the next incoming connection and returns it as a `TcpStream`.

        Raises:
            Io"""
    async def accept_async(self) -> TcpStream:
        """Waits for the next incoming connection and returns it as a `TcpStream`.

        Raises:
            Io"""
    def close(self) -> None:
        """Raises:
            Io"""
    async def close_async(self) -> None:
        """Raises:
            Io"""


class UdpSocket(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    @staticmethod
    def bind(addr: str) -> UdpSocket:
        """Binds to `addr` (e.g. `"0.0.0.0:0"` for an OS-assigned ephemeral port) and
        returns the socket.

        Raises:
            Io"""
    @staticmethod
    async def bind_async(addr: str) -> UdpSocket:
        """Binds to `addr` (e.g. `"0.0.0.0:0"` for an OS-assigned ephemeral port) and
        returns the socket.

        Raises:
            Io"""
    def send_to(self, data: bytes, addr: str, *, timeout: typing.Union[baml.time.Duration, None, UNSET] = None) -> int:
        """Sends `data` as a single datagram to `addr`. Returns the number of bytes sent.

        `timeout` bounds the send; `null` (the default) blocks indefinitely. On
        expiry this throws `baml.errors.Timeout`. Mirrors `UdpSocket::set_write_timeout`.

        Raises:
            Io, Timeout"""
    async def send_to_async(self, data: bytes, addr: str, *, timeout: typing.Union[baml.time.Duration, None, UNSET] = None) -> int:
        """Sends `data` as a single datagram to `addr`. Returns the number of bytes sent.

        `timeout` bounds the send; `null` (the default) blocks indefinitely. On
        expiry this throws `baml.errors.Timeout`. Mirrors `UdpSocket::set_write_timeout`.

        Raises:
            Io, Timeout"""
    def _send_to_(self, data: bytes, addr: str, timeout_nanos: int) -> int:
        """(internal)

        Raises:
            Io, Timeout"""
    async def _send_to__async(self, data: bytes, addr: str, timeout_nanos: int) -> int:
        """(internal)

        Raises:
            Io, Timeout"""
    def recv_from(self, *, timeout: typing.Union[baml.time.Duration, None, UNSET] = None) -> Datagram:
        """Receives a single datagram, returning its payload bytes together with the
        address of the sender.

        `timeout` bounds the wait for a datagram; `null` (the default) blocks
        indefinitely. On expiry this throws `baml.errors.Timeout` and the socket
        remains usable. Mirrors `UdpSocket::set_read_timeout`.

        Raises:
            Io, Timeout"""
    async def recv_from_async(self, *, timeout: typing.Union[baml.time.Duration, None, UNSET] = None) -> Datagram:
        """Receives a single datagram, returning its payload bytes together with the
        address of the sender.

        `timeout` bounds the wait for a datagram; `null` (the default) blocks
        indefinitely. On expiry this throws `baml.errors.Timeout` and the socket
        remains usable. Mirrors `UdpSocket::set_read_timeout`.

        Raises:
            Io, Timeout"""
    def _recv_from_(self, timeout_nanos: int) -> Datagram:
        """(internal)

        Raises:
            Io, Timeout"""
    async def _recv_from__async(self, timeout_nanos: int) -> Datagram:
        """(internal)

        Raises:
            Io, Timeout"""
    def close(self) -> None:
        """Closes the socket.

        Raises:
            Io"""
    async def close_async(self) -> None:
        """Closes the socket.

        Raises:
            Io"""


class Datagram(pydantic.BaseModel):
    data: bytes
    addr: str


__all__ = [
    "TcpStream",
    "TcpListener",
    "UdpSocket",
    "Datagram",
]
