# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic


T = typing.TypeVar("T")


json: typing.TypeAlias = typing.Any



class ParseError(pydantic.BaseModel):
    message: str


class DecodeError(pydantic.BaseModel):
    message: str
    path: str


class SerializationError(pydantic.BaseModel):
    message: str
    path: str
    reason: str


def parse(s: str) -> json:
    """Parses one JSON document into an untyped `json` value.

    The whole string must be that document; trailing content is a syntax error,
    not a stopping point. To land in a declared type instead, use
    `from_string<T>` (structural) or `deserialize<T>` (override-honoring).

    # Throws

    - `baml.json.ParseError` if `s` is not valid JSON.

    Raises:
        ParseError"""
async def parse_async(s: str) -> json:
    """Parses one JSON document into an untyped `json` value.

    The whole string must be that document; trailing content is a syntax error,
    not a stopping point. To land in a declared type instead, use
    `from_string<T>` (structural) or `deserialize<T>` (override-honoring).

    # Throws

    - `baml.json.ParseError` if `s` is not valid JSON.

    Raises:
        ParseError"""


def stringify(j: json) -> str:
    """Serializes a `json` value to compact JSON text.

    Never fails: every `json` arm has a JSON form. The one lossy case is a
    non-finite `float` — JSON has no NaN or infinity, so those become `null`.
    For a value that is not already a `json`, use `to_string`."""
async def stringify_async(j: json) -> str:
    """Serializes a `json` value to compact JSON text.

    Never fails: every `json` arm has a JSON form. The one lossy case is a
    non-finite `float` — JSON has no NaN or infinity, so those become `null`.
    For a value that is not already a `json`, use `to_string`."""


def stringify_pretty(j: json) -> str:
    """Serializes a `json` value to indented JSON text.

    The same value mapping as `stringify`, non-finite floats included; only the
    layout differs."""
async def stringify_pretty_async(j: json) -> str:
    """Serializes a `json` value to indented JSON text.

    The same value mapping as `stringify`, non-finite floats included; only the
    layout differs."""


def to_string(value: typing.Any) -> str:
    """Serializes any BAML value to its canonical JSON text.

    `stringify` composed with `to_json`: dispatch is on the value's runtime
    type, and `baml.ToJson` overrides apply at every depth. Reach for this when
    you want JSON text, and for `from<T>` when you want a `json` value to keep
    working with. Not to be confused with `string.from`, which renders BAML's
    own display form rather than JSON.

    # Throws

    - `baml.json.SerializationError` if any value in the graph has no JSON form
      — a `uint8array` without explicit encoding, a function, a future. See
      `from<T>` for the full rendering rules.

    Raises:
        SerializationError"""
async def to_string_async(value: typing.Any) -> str:
    """Serializes any BAML value to its canonical JSON text.

    `stringify` composed with `to_json`: dispatch is on the value's runtime
    type, and `baml.ToJson` overrides apply at every depth. Reach for this when
    you want JSON text, and for `from<T>` when you want a `json` value to keep
    working with. Not to be confused with `string.from`, which renders BAML's
    own display form rather than JSON.

    # Throws

    - `baml.json.SerializationError` if any value in the graph has no JSON form
      — a `uint8array` without explicit encoding, a function, a future. See
      `from<T>` for the full rendering rules.

    Raises:
        SerializationError"""


def to_json(value: typing.Any) -> json:
    """Raises:
        SerializationError"""
async def to_json_async(value: typing.Any) -> json:
    """Raises:
        SerializationError"""


def from_(value: T, *, _types: dict[str, typing.Any] | None = None) -> json:
    """Serializes a value to its `json` representation, honoring `baml.ToJson`
    overrides on classes at every depth.

    The json analog of `string.from`. Primitives, lists, and maps render to
    their natural json shape; a class instance becomes `{"field": value}`, an
    enum its variant name, media the tagged form. A `bigint` renders as an
    arbitrary-precision JSON number, and a non-finite `float` renders as `null`.

    A value whose runtime class `implements baml.ToJson` routes through that
    override instead, and an override owns its whole subtree — the walk stops
    descending once it dispatches one. Resolution is on the value's *runtime*
    class, so an override declared in any package is honored, not just one
    visible to this one.

    `T` selects nothing. It is the call site's static type and no more; every
    dispatch decision is made on the value in hand.

    This is the caller-facing serializer, and what `v.to_json()` desugars to.
    `to_json` is the same walk behind an `unknown` parameter.

    # Throws

    - `baml.json.SerializationError` if any value in the graph has no JSON
      form: a `uint8array` (encode it explicitly with `to_base64()` or
      `to_hex()`), a function, a future, or any other opaque runtime object.
      `reason` names which.

    Raises:
        SerializationError"""
async def from__async(value: T, *, _types: dict[str, typing.Any] | None = None) -> json:
    """Serializes a value to its `json` representation, honoring `baml.ToJson`
    overrides on classes at every depth.

    The json analog of `string.from`. Primitives, lists, and maps render to
    their natural json shape; a class instance becomes `{"field": value}`, an
    enum its variant name, media the tagged form. A `bigint` renders as an
    arbitrary-precision JSON number, and a non-finite `float` renders as `null`.

    A value whose runtime class `implements baml.ToJson` routes through that
    override instead, and an override owns its whole subtree — the walk stops
    descending once it dispatches one. Resolution is on the value's *runtime*
    class, so an override declared in any package is honored, not just one
    visible to this one.

    `T` selects nothing. It is the call site's static type and no more; every
    dispatch decision is made on the value in hand.

    This is the caller-facing serializer, and what `v.to_json()` desugars to.
    `to_json` is the same walk behind an `unknown` parameter.

    # Throws

    - `baml.json.SerializationError` if any value in the graph has no JSON
      form: a `uint8array` (encode it explicitly with `to_base64()` or
      `to_hex()`), a function, a future, or any other opaque runtime object.
      `reason` names which.

    Raises:
        SerializationError"""


def from_string(s: str, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        ParseError, DecodeError"""
async def from_string_async(s: str, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        ParseError, DecodeError"""


def from_json(j: json, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        DecodeError"""
async def from_json_async(j: json, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        DecodeError"""


def to(j: json, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        DecodeError"""
async def to_async(j: json, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        DecodeError"""


def field(j: json, key: str) -> json: ...
async def field_async(j: json, key: str) -> json: ...


class PathError(pydantic.BaseModel):
    message: str
    selector: str


def _path_field(current: json, key: str, selector: str) -> json:
    """(internal) One `.field` step of a `path` walk. Use `path`.

    Raises:
        PathError"""
async def _path_field_async(current: json, key: str, selector: str) -> json:
    """(internal) One `.field` step of a `path` walk. Use `path`.

    Raises:
        PathError"""


def _path_index(current: json, idx: int, selector: str) -> json:
    """(internal) One `[i]` step of a `path` walk. Use `path`.

    Raises:
        PathError"""
async def _path_index_async(current: json, idx: int, selector: str) -> json:
    """(internal) One `[i]` step of a `path` walk. Use `path`.

    Raises:
        PathError"""


def path(j: json, selector: str, *, _types: dict[str, typing.Any]) -> T:
    """Navigates a jq-style selector into a `json` value and coerces the leaf to
    `T`.

    Selectors start with `.` or `[`. Dot and quoted-bracket steps address
    object fields; integer bracket steps address arrays. A dot step runs to the
    next `.` or `[`, so a field name containing either must use the bracket
    form: `["a.b"]`. Bracket keys accept single or double quotes, and take `\\`
    as a literal escape for one following character. Indices are non-negative
    and absolute — there is no jq-style negative indexing, and `[-1]` reports
    out of bounds. A bare `.` selects nothing, so `"."` is the identity
    selector.

    The leaf is coerced with `to<T>`, so `baml.FromJson` overrides apply and
    `T` may be a whole class, not only a scalar. Every way this can fail —
    malformed selector, missing field, wrong shape, out-of-range index, leaf
    that will not decode — collapses into one `PathError`, which is what makes
    `path_or` a clean total wrapper.

    # Throws

    - `baml.json.PathError` if the selector is malformed, if a step does not
      resolve, or if the selected leaf does not decode to `T`.

    # Examples

    ```baml
    let doc = baml.json.parse("{\\"users\\": [{\\"name\\": \\"Ada\\", \\"age\\": 36}]}");
    assert.equal(baml.json.path<string>(doc, ".users[0].name"), "Ada");
    assert.equal(baml.json.path<int>(doc, "[\\"users\\"][0][\\"age\\"]"), 36);
    ```

    Raises:
        PathError"""
async def path_async(j: json, selector: str, *, _types: dict[str, typing.Any]) -> T:
    """Navigates a jq-style selector into a `json` value and coerces the leaf to
    `T`.

    Selectors start with `.` or `[`. Dot and quoted-bracket steps address
    object fields; integer bracket steps address arrays. A dot step runs to the
    next `.` or `[`, so a field name containing either must use the bracket
    form: `["a.b"]`. Bracket keys accept single or double quotes, and take `\\`
    as a literal escape for one following character. Indices are non-negative
    and absolute — there is no jq-style negative indexing, and `[-1]` reports
    out of bounds. A bare `.` selects nothing, so `"."` is the identity
    selector.

    The leaf is coerced with `to<T>`, so `baml.FromJson` overrides apply and
    `T` may be a whole class, not only a scalar. Every way this can fail —
    malformed selector, missing field, wrong shape, out-of-range index, leaf
    that will not decode — collapses into one `PathError`, which is what makes
    `path_or` a clean total wrapper.

    # Throws

    - `baml.json.PathError` if the selector is malformed, if a step does not
      resolve, or if the selected leaf does not decode to `T`.

    # Examples

    ```baml
    let doc = baml.json.parse("{\\"users\\": [{\\"name\\": \\"Ada\\", \\"age\\": 36}]}");
    assert.equal(baml.json.path<string>(doc, ".users[0].name"), "Ada");
    assert.equal(baml.json.path<int>(doc, "[\\"users\\"][0][\\"age\\"]"), 36);
    ```

    Raises:
        PathError"""


def path_or(j: json, selector: str, default: T, *, _types: dict[str, typing.Any] | None = None) -> T:
    """Returns `default` when `path` cannot resolve or coerce the selected value.

    Swallows every `PathError`, a misspelled selector included. That makes it
    the wrong tool while you are still getting a selector right: a typo is
    indistinguishable from a genuinely absent field."""
async def path_or_async(j: json, selector: str, default: T, *, _types: dict[str, typing.Any] | None = None) -> T:
    """Returns `default` when `path` cannot resolve or coerce the selected value.

    Swallows every `PathError`, a misspelled selector included. That makes it
    the wrong tool while you are still getting a selector right: a typo is
    indistinguishable from a genuinely absent field."""


def schema(t: typing.Any) -> json:
    """Lowers a BAML type to ordinary, provider-neutral JSON Schema.

    The type-level counterpart to the value conversions above: they move a
    *value* between BAML and `json`, while this describes the *shape* a value
    of `t` would take.

    Optional fields are omitted from `required`, maps use schema-valued
    `additionalProperties`, and unions use `anyOf`. Enums lower to a string
    `enum` of their variant names, `uint8array` to `string`, and `unknown` to
    the empty schema `{}`. A nullable type becomes a `["T", "null"]` type list
    where it can, and `anyOf` otherwise.

    This pass *does* respect `@alias` and `@skip`, where the value conversions
    do not — a schema is read by something outside BAML, so it must describe
    the wire names. That is also why an enum variant lowers under its alias.

    The root type is emitted inline, and every class and named alias beneath it
    goes into `$defs` to be reached by `$ref`. That is what lets a recursive
    graph terminate: a recursive root is emitted both inline and into `$defs`,
    so the `$ref` back to itself resolves.

    # Throws

    - `baml.errors.Unsupported` for a type with no JSON Schema form, and for a
      class, enum, or alias the reflection context cannot resolve.

    Raises:
        Unsupported"""
async def schema_async(t: typing.Any) -> json:
    """Lowers a BAML type to ordinary, provider-neutral JSON Schema.

    The type-level counterpart to the value conversions above: they move a
    *value* between BAML and `json`, while this describes the *shape* a value
    of `t` would take.

    Optional fields are omitted from `required`, maps use schema-valued
    `additionalProperties`, and unions use `anyOf`. Enums lower to a string
    `enum` of their variant names, `uint8array` to `string`, and `unknown` to
    the empty schema `{}`. A nullable type becomes a `["T", "null"]` type list
    where it can, and `anyOf` otherwise.

    This pass *does* respect `@alias` and `@skip`, where the value conversions
    do not — a schema is read by something outside BAML, so it must describe
    the wire names. That is also why an enum variant lowers under its alias.

    The root type is emitted inline, and every class and named alias beneath it
    goes into `$defs` to be reached by `$ref`. That is what lets a recursive
    graph terminate: a recursive root is emitted both inline and into `$defs`,
    so the `$ref` back to itself resolves.

    # Throws

    - `baml.errors.Unsupported` for a type with no JSON Schema form, and for a
      class, enum, or alias the reflection context cannot resolve.

    Raises:
        Unsupported"""


def serialize(v: T, *, _types: dict[str, typing.Any] | None = None) -> str:
    """Serializes `v` to JSON text, honoring `baml.ToJson` overrides on classes
    (via `to_json`). Equivalent to `to_string(v)`.

    For a host that wants to print a target's return value as JSON while still
    respecting class-level `to_json` overrides. From BAML, call `to_string`
    directly; nothing here adds behaviour.

    # Throws

    - `baml.json.SerializationError` if any value in the graph has no JSON
      form; see `from<T>`.

    Raises:
        SerializationError"""
async def serialize_async(v: T, *, _types: dict[str, typing.Any] | None = None) -> str:
    """Serializes `v` to JSON text, honoring `baml.ToJson` overrides on classes
    (via `to_json`). Equivalent to `to_string(v)`.

    For a host that wants to print a target's return value as JSON while still
    respecting class-level `to_json` overrides. From BAML, call `to_string`
    directly; nothing here adds behaviour.

    # Throws

    - `baml.json.SerializationError` if any value in the graph has no JSON
      form; see `from<T>`.

    Raises:
        SerializationError"""


def deserialize(s: str, *, _types: dict[str, typing.Any]) -> T:
    """Parses JSON text into a value of type `T`, honoring `baml.FromJson`
    overrides on classes (via `from_json<T>`). Equivalent to
    `from_json<T>(parse(s))`.

    For a host that wants to coerce a JSON-shaped input (such as `--json-args`)
    into a typed BAML value while respecting class-level `from_json` overrides.
    `from_string<T>` is the structural path, which bypasses overrides.

    # Throws

    - `baml.json.ParseError` if `s` is not valid JSON.
    - `baml.json.DecodeError` if the parsed document does not fit `T`.

    Raises:
        ParseError, DecodeError"""
async def deserialize_async(s: str, *, _types: dict[str, typing.Any]) -> T:
    """Parses JSON text into a value of type `T`, honoring `baml.FromJson`
    overrides on classes (via `from_json<T>`). Equivalent to
    `from_json<T>(parse(s))`.

    For a host that wants to coerce a JSON-shaped input (such as `--json-args`)
    into a typed BAML value while respecting class-level `from_json` overrides.
    `from_string<T>` is the structural path, which bypasses overrides.

    # Throws

    - `baml.json.ParseError` if `s` is not valid JSON.
    - `baml.json.DecodeError` if the parsed document does not fit `T`.

    Raises:
        ParseError, DecodeError"""


__all__ = [
    "json",
    "ParseError",
    "DecodeError",
    "SerializationError",
    "parse",
    "parse_async",
    "stringify",
    "stringify_async",
    "stringify_pretty",
    "stringify_pretty_async",
    "to_string",
    "to_string_async",
    "to_json",
    "to_json_async",
    "from_",
    "from__async",
    "from_string",
    "from_string_async",
    "from_json",
    "from_json_async",
    "to",
    "to_async",
    "field",
    "field_async",
    "PathError",
    "path",
    "path_async",
    "path_or",
    "path_or_async",
    "schema",
    "schema_async",
    "serialize",
    "serialize_async",
    "deserialize",
    "deserialize_async",
]
