# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import enum
import typing
import typing_extensions
import pydantic

if typing.TYPE_CHECKING:
    from ... import baml
    from ...baml import UNSET as UNSET

from baml_bridge import BamlPyHandle as _BamlPyHandle


T = typing.TypeVar("T")


Value: typing.TypeAlias = typing.Union[bool, int, int, float, str, None]


class ErrorKind(str, enum.Enum):
    Options = "Options"
    Quote = "Quote"
    FieldCount = "FieldCount"
    Encoding = "Encoding"
    Header = "Header"
    Decode = "Decode"
    Encode = "Encode"
    NotFound = "NotFound"
    TooManyRows = "TooManyRows"
    Closed = "Closed"


class Error(pydantic.BaseModel):
    kind: ErrorKind
    message: str
    line: typing.Optional[int] = None
    record: typing.Optional[int] = None
    field: typing.Optional[int] = None
    column: typing.Optional[str] = None
    expected: typing.Optional[int] = None
    found: typing.Optional[int] = None


class Position(pydantic.BaseModel):
    byte: int
    line: int
    record: int


class ReaderOptions(pydantic.BaseModel):
    delimiter: typing.Optional[str] = None
    quote: typing.Optional[str] = None
    quoting: typing.Optional[bool] = None
    escape: typing.Optional[str] = None
    has_header: typing.Optional[bool] = None
    headers: typing.Optional[typing.List[str]] = None
    comment: typing.Optional[str] = None
    trim: typing.Union[typing.Literal["none"], typing.Literal["headers"], typing.Literal["fields"], typing.Literal["all"], None] = None
    skip_lines: typing.Optional[int] = None
    skip_blank_records: typing.Optional[bool] = None
    ragged: typing.Union[typing.Literal["strict"], typing.Literal["pad"], typing.Literal["truncate"], None] = None
    null_values: typing.Optional[typing.List[str]] = None
    encoding: typing.Union[typing.Literal["utf8"], typing.Literal["utf8-lossy"], None] = None
    bom: typing.Union[typing.Literal["strip"], typing.Literal["keep"], None] = None
    on_error: typing.Union[typing.Literal["throw"], typing.Literal["skip"], None] = None
    on_skip: typing.Optional[typing.Callable[[Error], None]] = None
    max_skipped: typing.Optional[int] = None
    limit: typing.Optional[int] = None


class WriterOptions(pydantic.BaseModel):
    delimiter: typing.Optional[str] = None
    quote: typing.Optional[str] = None
    quote_style: typing.Union[typing.Literal["minimal"], typing.Literal["all"], typing.Literal["never"], None] = None
    escape: typing.Optional[str] = None
    terminator: typing.Union[typing.Literal["lf"], typing.Literal["crlf"], None] = None
    write_header: typing.Optional[bool] = None
    headers: typing.Optional[typing.List[str]] = None
    null_value: typing.Optional[str] = None
    bom: typing.Optional[bool] = None
    sanitize_formulas: typing.Optional[bool] = None


class _NeedData(pydantic.BaseModel):
    ...


class _Skip(pydantic.BaseModel):
    error: Error


class _Headers(pydantic.BaseModel):
    names: typing.Optional[typing.List[str]] = None


class Record(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    def get(self, column: str, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
        """Converts the cell under header `column` to `T`.

        # Returns

        `null` for a column name absent from the headers, a missing cell, or a
        null cell.

        # Throws

        - `Error { kind: Decode }` when a cell exists but cannot convert to `T`.
        - `Error { kind: Header }` when the name is duplicated in the header, or
          when name-based access is used with no headers at all — use `get_at`
          for positional access.
        - `Error { kind: Options }` when `T` is not cell-decodable.

        Raises:
            Error"""
    async def get_async(self, column: str, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
        """Converts the cell under header `column` to `T`.

        # Returns

        `null` for a column name absent from the headers, a missing cell, or a
        null cell.

        # Throws

        - `Error { kind: Decode }` when a cell exists but cannot convert to `T`.
        - `Error { kind: Header }` when the name is duplicated in the header, or
          when name-based access is used with no headers at all — use `get_at`
          for positional access.
        - `Error { kind: Options }` when `T` is not cell-decodable.

        Raises:
            Error"""
    def get_at(self, index: int, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
        """Converts the cell at `index` to `T`, positionally.

        Works with or without headers. An out-of-range or negative `index`
        reads as a missing cell rather than an error.

        # Returns

        `null` for a missing or null cell.

        # Throws

        - `Error { kind: Decode }` on conversion failure.
        - `Error { kind: Options }` when `T` is not cell-decodable.

        Raises:
            Error"""
    async def get_at_async(self, index: int, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
        """Converts the cell at `index` to `T`, positionally.

        Works with or without headers. An out-of-range or negative `index`
        reads as a missing cell rather than an error.

        # Returns

        `null` for a missing or null cell.

        # Throws

        - `Error { kind: Decode }` on conversion failure.
        - `Error { kind: Options }` when `T` is not cell-decodable.

        Raises:
            Error"""
    def fields(self) -> typing.List[str]: ...
    async def fields_async(self) -> typing.List[str]: ...
    def length(self) -> int: ...
    async def length_async(self) -> int: ...
    def position(self) -> Position: ...
    async def position_async(self) -> Position: ...
    def decode(self, *, _types: dict[str, typing.Any]) -> T:
        """Applies the full typed-decode rules to this one record — useful for
        routing heterogeneous rows.

        Always throws on failure, whatever the reader's `on_error` policy says.

        `T` must be a flat class. Each field is matched to a column by its
        declared name (no `@alias`), or positionally by declaration order when
        the reader has no headers. An optional field tolerates an absent
        column, a missing cell, and a null cell; a required one tolerates none
        of the three.

        # Throws

        - `Error { kind: Decode }` when a cell will not convert, or when a
          required field's cell is missing or null.
        - `Error { kind: Header }` when a required field has no matching
          column, or its column name is duplicated.
        - `Error { kind: Options }` when `T` is not a class, or a field's type
          is not cell-decodable.

        Raises:
            Error"""
    async def decode_async(self, *, _types: dict[str, typing.Any]) -> T:
        """Applies the full typed-decode rules to this one record — useful for
        routing heterogeneous rows.

        Always throws on failure, whatever the reader's `on_error` policy says.

        `T` must be a flat class. Each field is matched to a column by its
        declared name (no `@alias`), or positionally by declaration order when
        the reader has no headers. An optional field tolerates an absent
        column, a missing cell, and a null cell; a required one tolerates none
        of the three.

        # Throws

        - `Error { kind: Decode }` when a cell will not convert, or when a
          required field's cell is missing or null.
        - `Error { kind: Header }` when a required field has no matching
          column, or its column name is duplicated.
        - `Error { kind: Options }` when `T` is not a class, or a field's type
          is not cell-decodable.

        Raises:
            Error"""
    def to_map(self) -> typing.Dict[str, str]:
        """Raises:
            Error"""
    async def to_map_async(self) -> typing.Dict[str, str]:
        """Raises:
            Error"""


class Reader(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    field_file: typing.Optional[baml.fs.File] = pydantic.Field(default=None, alias="_file")
    field_on_skip: typing.Optional[typing.Callable[[Error], None]] = pydantic.Field(default=None, alias="_on_skip")
    field_owns_file: bool = pydantic.Field(alias="_owns_file")
    def headers(self) -> typing.Optional[typing.List[str]]:
        """The column names: the `headers` option when set, the file's header row
        when `has_header = true` (consumed on first call), and `null` otherwise.

        Idempotent. The header is resolved once and cached, so calling this
        before iterating costs nothing and consumes no data record. An empty
        input has no header row, and reads as the `headers` option or `null`.

        A malformed header record surfaces from whichever call reads the header
        first, and it exhausts the reader rather than resynchronizing: without
        a trustworthy header every later name-to-column mapping would be
        silently wrong. `on_error` does not apply, because there is no next
        header to resume at.

        # Throws

        - `Error { kind: Quote }` or `Error { kind: Encoding }` if the header
          record itself is malformed. Every later call rethrows the same error.
        - `baml.errors.Io` if the source cannot be read.

        Raises:
            Error, Io"""
    async def headers_async(self) -> typing.Optional[typing.List[str]]:
        """The column names: the `headers` option when set, the file's header row
        when `has_header = true` (consumed on first call), and `null` otherwise.

        Idempotent. The header is resolved once and cached, so calling this
        before iterating costs nothing and consumes no data record. An empty
        input has no header row, and reads as the `headers` option or `null`.

        A malformed header record surfaces from whichever call reads the header
        first, and it exhausts the reader rather than resynchronizing: without
        a trustworthy header every later name-to-column mapping would be
        silently wrong. `on_error` does not apply, because there is no next
        header to resume at.

        # Throws

        - `Error { kind: Quote }` or `Error { kind: Encoding }` if the header
          record itself is malformed. Every later call rethrows the same error.
        - `baml.errors.Io` if the source cannot be read.

        Raises:
            Error, Io"""
    def rows(self, *, _types: dict[str, typing.Any]) -> typing.Any:
        """A typed iterator over the remaining records, decoding each into `T`.

        Validates eagerly. It reads the header if necessary and checks that
        every non-optional field of `T` is satisfiable, so an unusable `T`
        throws `Error { kind: Header }` at the call site rather than on the
        millionth row.

        The decode rules are `Record.decode<T>`'s, under this reader's
        `on_error` policy. "Remaining" is literal: this shares the reader's one
        cursor, so records already pulled by `next()` are gone.

        # Throws

        - `Error { kind: Header }` if a required field of `T` has no column, or
          its column name is duplicated.
        - `Error { kind: Options }` if `T` is not a flat class of
          cell-decodable fields.
        - Anything `headers()` throws, since it is called first.

        Raises:
            Error, Io"""
    async def rows_async(self, *, _types: dict[str, typing.Any]) -> typing.Any:
        """A typed iterator over the remaining records, decoding each into `T`.

        Validates eagerly. It reads the header if necessary and checks that
        every non-optional field of `T` is satisfiable, so an unusable `T`
        throws `Error { kind: Header }` at the call site rather than on the
        millionth row.

        The decode rules are `Record.decode<T>`'s, under this reader's
        `on_error` policy. "Remaining" is literal: this shares the reader's one
        cursor, so records already pulled by `next()` are gone.

        # Throws

        - `Error { kind: Header }` if a required field of `T` has no column, or
          its column name is duplicated.
        - `Error { kind: Options }` if `T` is not a flat class of
          cell-decodable fields.
        - Anything `headers()` throws, since it is called first.

        Raises:
            Error, Io"""
    def skipped(self) -> typing.List[Error]: ...
    async def skipped_async(self) -> typing.List[Error]: ...
    def skipped_count(self) -> int: ...
    async def skipped_count_async(self) -> int: ...
    def position(self) -> Position: ...
    async def position_async(self) -> Position: ...
    def close(self) -> None:
        """Releases the reader. Idempotent.

        The underlying file handle is closed only when the reader owns it
        (created by `open`); a handle passed to `reader(file)` stays open,
        since its lifecycle belongs to the caller. Closing is optional, as with
        `baml.fs.File` — the GC reclaims unreferenced readers.

        # Throws

        - `baml.errors.Io` if closing an owned file handle fails. The reader is
          already marked closed by then, so a retry will not reopen it.

        Raises:
            Io"""
    async def close_async(self) -> None:
        """Releases the reader. Idempotent.

        The underlying file handle is closed only when the reader owns it
        (created by `open`); a handle passed to `reader(file)` stays open,
        since its lifecycle belongs to the caller. Closing is optional, as with
        `baml.fs.File` — the GC reclaims unreferenced readers.

        # Throws

        - `baml.errors.Io` if closing an owned file handle fails. The reader is
          already marked closed by then, so a retry will not reopen it.

        Raises:
            Io"""
    def _poll_(self) -> typing.Union[Record, _Skip, _NeedData, baml.iter.Done]:
        """Raises:
            Error"""
    async def _poll__async(self) -> typing.Union[Record, _Skip, _NeedData, baml.iter.Done]:
        """Raises:
            Error"""
    def _poll_headers_(self) -> typing.Union[_Headers, _NeedData]:
        """Raises:
            Error"""
    async def _poll_headers__async(self) -> typing.Union[_Headers, _NeedData]:
        """Raises:
            Error"""
    def _feed_(self, chunk: bytes) -> None: ...
    async def _feed__async(self, chunk: bytes) -> None: ...
    def _feed_eof_(self) -> None: ...
    async def _feed_eof__async(self) -> None: ...
    def _mark_closed_(self) -> None: ...
    async def _mark_closed__async(self) -> None: ...
    def _mark_exhausted_(self) -> None: ...
    async def _mark_exhausted__async(self) -> None: ...
    def _read_chunk_(self) -> None:
        """(internal) Pull the next chunk from the backing file, or mark EOF for
        in-memory sources.

        The reader is marked exhausted before an IO error is thrown, so
        subsequent `next()` calls return `baml.iter.Done`. A closed handle
        arrives as an IO error, because `baml.io.Read` has no separate
        closed-handle error channel.

        Raises:
            Io"""
    async def _read_chunk__async(self) -> None:
        """(internal) Pull the next chunk from the backing file, or mark EOF for
        in-memory sources.

        The reader is marked exhausted before an IO error is thrown, so
        subsequent `next()` calls return `baml.iter.Done`. A closed handle
        arrives as an IO error, because `baml.io.Read` has no separate
        closed-handle error channel.

        Raises:
            Io"""


class Rows(pydantic.BaseModel, typing.Generic[T]):
    reader: Reader


class Writer(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    field_file: typing.Optional[baml.fs.File] = pydantic.Field(default=None, alias="_file")
    field_owns_file: bool = pydantic.Field(alias="_owns_file")
    def write_record(self, record: typing.List[Value]) -> None:
        """Writes one raw record. Never triggers an automatic header.

        The escape hatch from typed writing: cell count and content are
        whatever you pass, unchecked against any header already written.

        Raises:
            Error, Io"""
    async def write_record_async(self, record: typing.List[Value]) -> None:
        """Writes one raw record. Never triggers an automatic header.

        The escape hatch from typed writing: cell count and content are
        whatever you pass, unchecked against any header already written.

        Raises:
            Error, Io"""
    def write_row(self, row: T, *, _types: dict[str, typing.Any] | None = None) -> None:
        """Writes one typed row, fields in declaration order.

        If `write_header` is enabled (the default) and no header has been
        written yet, the header derived from `T`'s field names — or from
        `WriterOptions.headers` — is emitted first. Field names go out raw, as
        `@alias` is not consulted; the same BEP-038 rule `baml.json` follows.

        # Throws

        - `Error { kind: Options }` if `T` is not a flat class, or a field's
          value is not cell-encodable.

        Raises:
            Error, Io"""
    async def write_row_async(self, row: T, *, _types: dict[str, typing.Any] | None = None) -> None:
        """Writes one typed row, fields in declaration order.

        If `write_header` is enabled (the default) and no header has been
        written yet, the header derived from `T`'s field names — or from
        `WriterOptions.headers` — is emitted first. Field names go out raw, as
        `@alias` is not consulted; the same BEP-038 rule `baml.json` follows.

        # Throws

        - `Error { kind: Options }` if `T` is not a flat class, or a field's
          value is not cell-encodable.

        Raises:
            Error, Io"""
    def write_rows(self, rows: typing.List[T], *, _types: dict[str, typing.Any] | None = None) -> None:
        """Writes many typed rows as one atomic batch.

        On a thrown error nothing from the batch is emitted or counted;
        otherwise this is `write_row<T>` in a loop, and throws exactly what it
        throws. All-or-nothing is the point — a partial batch would leave a
        file that looks complete.

        Raises:
            Error, Io"""
    async def write_rows_async(self, rows: typing.List[T], *, _types: dict[str, typing.Any] | None = None) -> None:
        """Writes many typed rows as one atomic batch.

        On a thrown error nothing from the batch is emitted or counted;
        otherwise this is `write_row<T>` in a loop, and throws exactly what it
        throws. All-or-nothing is the point — a partial batch would leave a
        file that looks complete.

        Raises:
            Error, Io"""
    def write_header(self, names: typing.List[str]) -> None:
        """Writes an explicit header record.

        Use it to name columns that do not match `T`'s fields, or to give
        `write_record` output a header, which it never emits on its own.
        Writing one satisfies `write_header: true`, so a later `write_row<T>`
        will not add a second.

        # Throws

        - `Error { kind: Header }` after data has been written — a header is
          only a header on the first line.

        Raises:
            Error, Io"""
    async def write_header_async(self, names: typing.List[str]) -> None:
        """Writes an explicit header record.

        Use it to name columns that do not match `T`'s fields, or to give
        `write_record` output a header, which it never emits on its own.
        Writing one satisfies `write_header: true`, so a later `write_row<T>`
        will not add a second.

        # Throws

        - `Error { kind: Header }` after data has been written — a header is
          only a header on the first line.

        Raises:
            Error, Io"""
    def records_written(self) -> int: ...
    async def records_written_async(self) -> int: ...
    def text(self) -> str:
        """Raises:
            Error"""
    async def text_async(self) -> str:
        """Raises:
            Error"""
    def flush(self) -> None:
        """Flushes pending output.

        Writes through `baml.fs` flush eagerly, so this is an infallible no-op
        kept for symmetry with other writer APIs."""
    async def flush_async(self) -> None:
        """Flushes pending output.

        Writes through `baml.fs` flush eagerly, so this is an infallible no-op
        kept for symmetry with other writer APIs."""
    def close(self) -> None:
        """Flushes and releases the writer. Idempotent.

        The underlying file handle is closed only when the writer owns it
        (created by `create`); a handle passed to `writer(file)` stays open,
        since its lifecycle belongs to the caller.

        Raises:
            Io"""
    async def close_async(self) -> None:
        """Flushes and releases the writer. Idempotent.

        The underlying file handle is closed only when the writer owns it
        (created by `create`); a handle passed to `writer(file)` stays open,
        since its lifecycle belongs to the caller.

        Raises:
            Io"""
    def _encode_record_(self, record: typing.List[Value]) -> str:
        """Raises:
            Error"""
    async def _encode_record__async(self, record: typing.List[Value]) -> str:
        """Raises:
            Error"""
    def _encode_header_(self, names: typing.List[str]) -> str:
        """Raises:
            Error"""
    async def _encode_header__async(self, names: typing.List[str]) -> str:
        """Raises:
            Error"""
    def _bytes_written_(self) -> int: ...
    async def _bytes_written__async(self) -> int: ...
    def _mark_closed_(self) -> None: ...
    async def _mark_closed__async(self) -> None: ...
    def _emit_(self, out: str) -> None:
        """(internal) Write encoded text to the backing file, if any. Buffer
        writers accumulate natively and receive `""` here.

        Raises:
            Io"""
    async def _emit__async(self, out: str) -> None:
        """(internal) Write encoded text to the backing file, if any. Buffer
        writers accumulate natively and receive `""` here.

        Raises:
            Io"""


def reader(source: typing.Union[str, bytes, baml.fs.File], *, options: typing.Union[ReaderOptions, None, UNSET] = None) -> Reader:
    """A streaming reader over in-memory text or bytes, or an open file handle.

    A `string` or `uint8array` source is CSV content, parsed in place. A
    `baml.fs.File` source is streamed from its current cursor to EOF, and the
    reader owns that cursor from construction until it is exhausted or closed.

    The handle is not adopted: `close()` on the reader leaves the file open,
    because you opened it and something else may still want it. Use `open` when
    you want the reader to own the file instead.

    # Throws

    - `Error { kind: Options }` if `options` is invalid. Nothing is parsed
      here — the first record is read lazily, on the first `next()`, `rows`,
      or `headers`.

    Raises:
        Error"""
async def reader_async(source: typing.Union[str, bytes, baml.fs.File], *, options: typing.Union[ReaderOptions, None, UNSET] = None) -> Reader:
    """A streaming reader over in-memory text or bytes, or an open file handle.

    A `string` or `uint8array` source is CSV content, parsed in place. A
    `baml.fs.File` source is streamed from its current cursor to EOF, and the
    reader owns that cursor from construction until it is exhausted or closed.

    The handle is not adopted: `close()` on the reader leaves the file open,
    because you opened it and something else may still want it. Use `open` when
    you want the reader to own the file instead.

    # Throws

    - `Error { kind: Options }` if `options` is invalid. Nothing is parsed
      here — the first record is read lazily, on the first `next()`, `rows`,
      or `headers`.

    Raises:
        Error"""


def open(path: str, *, options: typing.Union[ReaderOptions, None, UNSET] = None) -> Reader:
    """Opens the file at `path` through `baml.fs` and streams it.

    The reader owns the resulting handle, so `close()` closes the file.

    # Throws

    - `Error { kind: Options }` if `options` is invalid.
    - `baml.errors.Io` if `path` cannot be opened for reading.

    Raises:
        Error, Io"""
async def open_async(path: str, *, options: typing.Union[ReaderOptions, None, UNSET] = None) -> Reader:
    """Opens the file at `path` through `baml.fs` and streams it.

    The reader owns the resulting handle, so `close()` closes the file.

    # Throws

    - `Error { kind: Options }` if `options` is invalid.
    - `baml.errors.Io` if `path` cannot be opened for reading.

    Raises:
        Error, Io"""


def read(path: str, *, options: typing.Union[ReaderOptions, None, UNSET] = None, _types: dict[str, typing.Any]) -> typing.List[T]:
    """Eager typed read of a whole file, equivalent to
    `open(path).rows<T>().collect()`.

    If the file might not fit in memory, `open` it and stream instead. The
    options are identical; the streaming spelling is a verb swap away.

    # Throws

    - `Error` for anything `open` and `Reader.rows<T>` throw, and for any
      `Decode` failure not suppressed by `on_error = "skip"`.
    - `baml.errors.Io` if the file cannot be opened or read.

    Raises:
        Error, Io"""
async def read_async(path: str, *, options: typing.Union[ReaderOptions, None, UNSET] = None, _types: dict[str, typing.Any]) -> typing.List[T]:
    """Eager typed read of a whole file, equivalent to
    `open(path).rows<T>().collect()`.

    If the file might not fit in memory, `open` it and stream instead. The
    options are identical; the streaming spelling is a verb swap away.

    # Throws

    - `Error` for anything `open` and `Reader.rows<T>` throw, and for any
      `Decode` failure not suppressed by `on_error = "skip"`.
    - `baml.errors.Io` if the file cannot be opened or read.

    Raises:
        Error, Io"""


def parse(source: typing.Union[str, bytes], *, options: typing.Union[ReaderOptions, None, UNSET] = None) -> typing.List[typing.List[str]]:
    """Eager untyped parse of in-memory input: every record as a `string[]`.

    The array-of-arrays shape Node's `csv-parse` returns by default. Cells come
    back as raw text, exactly as `Record.fields` gives them — `null_values` is
    not applied, since there is no `null` in a `string[][]` to map onto. The
    header row is consumed and not returned unless `has_header: false`.

    # Throws

    - `Error` for a malformed record, unless `on_error = "skip"`. The reader is
      not returned, so its errors are unreachable afterwards; pass `on_skip` if
      you need to see them.

    Raises:
        Error"""
async def parse_async(source: typing.Union[str, bytes], *, options: typing.Union[ReaderOptions, None, UNSET] = None) -> typing.List[typing.List[str]]:
    """Eager untyped parse of in-memory input: every record as a `string[]`.

    The array-of-arrays shape Node's `csv-parse` returns by default. Cells come
    back as raw text, exactly as `Record.fields` gives them — `null_values` is
    not applied, since there is no `null` in a `string[][]` to map onto. The
    header row is consumed and not returned unless `has_header: false`.

    # Throws

    - `Error` for a malformed record, unless `on_error = "skip"`. The reader is
      not returned, so its errors are unreachable afterwards; pass `on_skip` if
      you need to see them.

    Raises:
        Error"""


def decode(source: typing.Union[str, bytes], *, options: typing.Union[ReaderOptions, None, UNSET] = None, _types: dict[str, typing.Any]) -> typing.List[T]:
    """Eager typed parse of in-memory input.

    The in-memory counterpart of `read<T>`, with `Record.decode<T>`'s rules.
    The same one-shot caveat as `parse` applies: the reader is not returned, so
    `skipped()` is unreachable and `on_skip` is the only way to observe skipped
    rows.

    # Throws

    - `Error` for anything `reader` and `Reader.rows<T>` throw, and for any
      `Decode` failure not suppressed by `on_error = "skip"`.

    Raises:
        Error"""
async def decode_async(source: typing.Union[str, bytes], *, options: typing.Union[ReaderOptions, None, UNSET] = None, _types: dict[str, typing.Any]) -> typing.List[T]:
    """Eager typed parse of in-memory input.

    The in-memory counterpart of `read<T>`, with `Record.decode<T>`'s rules.
    The same one-shot caveat as `parse` applies: the reader is not returned, so
    `skipped()` is unreachable and `on_skip` is the only way to observe skipped
    rows.

    # Throws

    - `Error` for anything `reader` and `Reader.rows<T>` throw, and for any
      `Decode` failure not suppressed by `on_error = "skip"`.

    Raises:
        Error"""


def decode_optional(source: typing.Union[str, bytes], *, options: typing.Union[ReaderOptions, None, UNSET] = None, _types: dict[str, typing.Any]) -> typing.Optional[T]:
    """Typed parse of an input with zero or one data record.

    The tolerant sibling of `decode_one<T>`: an empty input is `null` rather
    than an error. It still reads the whole input, since finding a second
    record is the only way to know there is not one.

    # Throws

    - `Error { kind: TooManyRows }` if the input holds more than one data
      record.
    - `Error` for anything `decode<T>` throws.

    Raises:
        Error"""
async def decode_optional_async(source: typing.Union[str, bytes], *, options: typing.Union[ReaderOptions, None, UNSET] = None, _types: dict[str, typing.Any]) -> typing.Optional[T]:
    """Typed parse of an input with zero or one data record.

    The tolerant sibling of `decode_one<T>`: an empty input is `null` rather
    than an error. It still reads the whole input, since finding a second
    record is the only way to know there is not one.

    # Throws

    - `Error { kind: TooManyRows }` if the input holds more than one data
      record.
    - `Error` for anything `decode<T>` throws.

    Raises:
        Error"""


def decode_one(source: typing.Union[str, bytes], *, options: typing.Union[ReaderOptions, None, UNSET] = None, _types: dict[str, typing.Any]) -> T:
    """Typed parse of an input with exactly one data record.

    Fits LLM output that was requested as exactly one row: `has_header: false`
    for a bare row (positional decode), or the default options when the model
    was asked to emit a header plus one data row.

    # Throws

    - `Error { kind: NotFound }` if the input holds no data record.
    - `Error { kind: TooManyRows }` if it holds more than one.
    - `Error` for anything `decode<T>` throws.

    Raises:
        Error"""
async def decode_one_async(source: typing.Union[str, bytes], *, options: typing.Union[ReaderOptions, None, UNSET] = None, _types: dict[str, typing.Any]) -> T:
    """Typed parse of an input with exactly one data record.

    Fits LLM output that was requested as exactly one row: `has_header: false`
    for a bare row (positional decode), or the default options when the model
    was asked to emit a header plus one data row.

    # Throws

    - `Error { kind: NotFound }` if the input holds no data record.
    - `Error { kind: TooManyRows }` if it holds more than one.
    - `Error` for anything `decode<T>` throws.

    Raises:
        Error"""


def writer(file: baml.fs.File, *, options: typing.Union[WriterOptions, None, UNSET] = None) -> Writer:
    """A streaming writer to an open file handle.

    Emits from the file's current cursor and never truncates; use `create` for
    a fresh output file. The handle is not adopted, so `close()` on the writer
    leaves the file open. Appending to an existing CSV usually also wants
    `write_header: false`, since the file already has one.

    # Throws

    - `Error { kind: Options }` if `options` is invalid.

    Raises:
        Error"""
async def writer_async(file: baml.fs.File, *, options: typing.Union[WriterOptions, None, UNSET] = None) -> Writer:
    """A streaming writer to an open file handle.

    Emits from the file's current cursor and never truncates; use `create` for
    a fresh output file. The handle is not adopted, so `close()` on the writer
    leaves the file open. Appending to an existing CSV usually also wants
    `write_header: false`, since the file already has one.

    # Throws

    - `Error { kind: Options }` if `options` is invalid.

    Raises:
        Error"""


def create(path: str, *, options: typing.Union[WriterOptions, None, UNSET] = None) -> Writer:
    """Creates or truncates the file at `path` and stream-writes to it.

    Parent directories are created as needed, as `baml.fs.write` does. The
    writer owns the resulting handle, so `close()` closes the file.

    # Throws

    - `Error { kind: Options }` if `options` is invalid.
    - `baml.errors.Io` if `path` cannot be opened for writing.

    Raises:
        Error, Io"""
async def create_async(path: str, *, options: typing.Union[WriterOptions, None, UNSET] = None) -> Writer:
    """Creates or truncates the file at `path` and stream-writes to it.

    Parent directories are created as needed, as `baml.fs.write` does. The
    writer owns the resulting handle, so `close()` closes the file.

    # Throws

    - `Error { kind: Options }` if `options` is invalid.
    - `baml.errors.Io` if `path` cannot be opened for writing.

    Raises:
        Error, Io"""


def buffer(*, options: typing.Union[WriterOptions, None, UNSET] = None) -> Writer:
    """An in-memory writer; retrieve the accumulated CSV with `text()`.

    The only writer whose output stays reachable — file-backed writers hand
    their bytes to `baml.fs` and keep nothing. Use it to build CSV
    incrementally when `stringify<T>` cannot see all the rows at once.

    # Throws

    - `Error { kind: Options }` if `options` is invalid.

    Raises:
        Error"""
async def buffer_async(*, options: typing.Union[WriterOptions, None, UNSET] = None) -> Writer:
    """An in-memory writer; retrieve the accumulated CSV with `text()`.

    The only writer whose output stays reachable — file-backed writers hand
    their bytes to `baml.fs` and keep nothing. Use it to build CSV
    incrementally when `stringify<T>` cannot see all the rows at once.

    # Throws

    - `Error { kind: Options }` if `options` is invalid.

    Raises:
        Error"""


def write(path: str, rows: typing.List[T], *, options: typing.Union[WriterOptions, None, UNSET] = None, _types: dict[str, typing.Any] | None = None) -> int:
    """One-shot typed file write, creating or truncating like `baml.fs.write`.

    The rows go out as one atomic batch, so a value that will not encode leaves
    the (already truncated) file empty rather than half written.

    # Returns

    Total bytes encoded, header and BOM included.

    # Throws

    - `Error` for anything `create` and `Writer.write_rows<T>` throw.
    - `baml.errors.Io` if the file cannot be opened, written, or closed.

    Raises:
        Error, Io"""
async def write_async(path: str, rows: typing.List[T], *, options: typing.Union[WriterOptions, None, UNSET] = None, _types: dict[str, typing.Any] | None = None) -> int:
    """One-shot typed file write, creating or truncating like `baml.fs.write`.

    The rows go out as one atomic batch, so a value that will not encode leaves
    the (already truncated) file empty rather than half written.

    # Returns

    Total bytes encoded, header and BOM included.

    # Throws

    - `Error` for anything `create` and `Writer.write_rows<T>` throw.
    - `baml.errors.Io` if the file cannot be opened, written, or closed.

    Raises:
        Error, Io"""


def stringify(rows: typing.List[T], *, options: typing.Union[WriterOptions, None, UNSET] = None, _types: dict[str, typing.Any] | None = None) -> str:
    """Serializes rows of `T` to CSV text.

    A header comes first, unless `WriterOptions.write_header` is `false`. The
    names come off the first row's class, or off `WriterOptions.headers`, so an
    empty `rows` produces `""` with no header — with no row there is nothing to
    name the columns after.

    # Throws

    - `Error` for anything `buffer` and `Writer.write_rows<T>` throw.

    Raises:
        Error"""
async def stringify_async(rows: typing.List[T], *, options: typing.Union[WriterOptions, None, UNSET] = None, _types: dict[str, typing.Any] | None = None) -> str:
    """Serializes rows of `T` to CSV text.

    A header comes first, unless `WriterOptions.write_header` is `false`. The
    names come off the first row's class, or off `WriterOptions.headers`, so an
    empty `rows` produces `""` with no header — with no row there is nothing to
    name the columns after.

    # Throws

    - `Error` for anything `buffer` and `Writer.write_rows<T>` throw.

    Raises:
        Error"""


def stringify_records(records: typing.List[typing.List[Value]], *, options: typing.Union[WriterOptions, None, UNSET] = None) -> str:
    """Serializes raw records to CSV text.

    No header is ever emitted: raw records carry no field names to derive one
    from. Write the header row yourself as the first entry of `records` if you
    want one. Rows are written one at a time, so a failure part-way leaves the
    earlier rows encoded but discards the text along with the error.

    # Throws

    - `Error` for anything `buffer` and `Writer.write_record` throw.

    Raises:
        Error"""
async def stringify_records_async(records: typing.List[typing.List[Value]], *, options: typing.Union[WriterOptions, None, UNSET] = None) -> str:
    """Serializes raw records to CSV text.

    No header is ever emitted: raw records carry no field names to derive one
    from. Write the header row yourself as the first entry of `records` if you
    want one. Rows are written one at a time, so a failure part-way leaves the
    earlier rows encoded but discards the text along with the error.

    # Throws

    - `Error` for anything `buffer` and `Writer.write_record` throw.

    Raises:
        Error"""


def to_markdown(rows: typing.List[T], *, max_rows: typing.Union[int, UNSET] = 100, _types: dict[str, typing.Any] | None = None) -> str:
    """Renders rows of `T` as a GitHub-style Markdown table for prompt context.

    Headers come from `T`'s field names. `|` is escaped and embedded newlines
    become spaces; non-finite floats render as `NaN` / `inf`, since prompt text
    is not meant to round-trip. Past `max_rows`, output is truncated with a
    final `… (N more rows)` line whose count covers all of `rows`, so the model
    is told what it is not seeing.

    Never fails, where the CSV writers are strict, and for the same reason: a
    prompt that renders "<unrepresentable>" in one cell is more useful than no
    prompt. Where CSV would reject a nested value, this falls back to its JSON
    form. A `T` that is not a class renders as a single `value` column."""
async def to_markdown_async(rows: typing.List[T], *, max_rows: typing.Union[int, UNSET] = 100, _types: dict[str, typing.Any] | None = None) -> str:
    """Renders rows of `T` as a GitHub-style Markdown table for prompt context.

    Headers come from `T`'s field names. `|` is escaped and embedded newlines
    become spaces; non-finite floats render as `NaN` / `inf`, since prompt text
    is not meant to round-trip. Past `max_rows`, output is truncated with a
    final `… (N more rows)` line whose count covers all of `rows`, so the model
    is told what it is not seeing.

    Never fails, where the CSV writers are strict, and for the same reason: a
    prompt that renders "<unrepresentable>" in one cell is more useful than no
    prompt. Where CSV would reject a nested value, this falls back to its JSON
    form. A `T` that is not a class renders as a single `value` column."""


def to_markdown_records(records: typing.List[typing.List[str]], *, headers: typing.Union[typing.List[str], None, UNSET] = None, max_rows: typing.Union[int, UNSET] = 100) -> str:
    """Renders untyped records as a GitHub-style Markdown table.

    The `parse`-shaped counterpart of `to_markdown<T>`. Without `headers` the
    columns are named `col1`, `col2`, ... out to the width of the widest
    rendered record; supply the header row explicitly to do better. Escaping
    and `… (N more rows)` truncation are as in `to_markdown<T>`."""
async def to_markdown_records_async(records: typing.List[typing.List[str]], *, headers: typing.Union[typing.List[str], None, UNSET] = None, max_rows: typing.Union[int, UNSET] = 100) -> str:
    """Renders untyped records as a GitHub-style Markdown table.

    The `parse`-shaped counterpart of `to_markdown<T>`. Without `headers` the
    columns are named `col1`, `col2`, ... out to the width of the widest
    rendered record; supply the header row explicitly to do better. Escaping
    and `… (N more rows)` truncation are as in `to_markdown<T>`."""


def _reader(source: typing.Union[str, bytes, baml.fs.File], options: typing.Optional[ReaderOptions], owns_file: bool) -> Reader:
    """Raises:
        Error"""
async def _reader_async(source: typing.Union[str, bytes, baml.fs.File], options: typing.Optional[ReaderOptions], owns_file: bool) -> Reader:
    """Raises:
        Error"""


def _writer(file: baml.fs.File, options: typing.Optional[WriterOptions], owns_file: bool) -> Writer:
    """Raises:
        Error"""
async def _writer_async(file: baml.fs.File, options: typing.Optional[WriterOptions], owns_file: bool) -> Writer:
    """Raises:
        Error"""


def _buffer(options: typing.Optional[WriterOptions]) -> Writer:
    """Raises:
        Error"""
async def _buffer_async(options: typing.Optional[WriterOptions]) -> Writer:
    """Raises:
        Error"""


def _validate_columns(r: Reader, *, _types: dict[str, typing.Any]) -> None:
    """Raises:
        Error"""
async def _validate_columns_async(r: Reader, *, _types: dict[str, typing.Any]) -> None:
    """Raises:
        Error"""


def _try_decode(rec: Record, r: Reader, *, _types: dict[str, typing.Any]) -> typing.Union[T, _Skip]:
    """Raises:
        Error"""
async def _try_decode_async(rec: Record, r: Reader, *, _types: dict[str, typing.Any]) -> typing.Union[T, _Skip]:
    """Raises:
        Error"""


def _decode_record(rec: Record, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        Error"""
async def _decode_record_async(rec: Record, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        Error"""


def _cell_by_name(rec: Record, column: str, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
    """Raises:
        Error"""
async def _cell_by_name_async(rec: Record, column: str, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
    """Raises:
        Error"""


def _cell_by_index(rec: Record, index: int, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
    """Raises:
        Error"""
async def _cell_by_index_async(rec: Record, index: int, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
    """Raises:
        Error"""


def _encode_row(w: Writer, row: T, *, _types: dict[str, typing.Any] | None = None) -> str:
    """Raises:
        Error"""
async def _encode_row_async(w: Writer, row: T, *, _types: dict[str, typing.Any] | None = None) -> str:
    """Raises:
        Error"""


def _encode_rows(w: Writer, rows: typing.List[T], *, _types: dict[str, typing.Any] | None = None) -> str:
    """Raises:
        Error"""
async def _encode_rows_async(w: Writer, rows: typing.List[T], *, _types: dict[str, typing.Any] | None = None) -> str:
    """Raises:
        Error"""


def _to_markdown(rows: typing.List[T], max_rows: int, *, _types: dict[str, typing.Any] | None = None) -> str: ...
async def _to_markdown_async(rows: typing.List[T], max_rows: int, *, _types: dict[str, typing.Any] | None = None) -> str: ...


def _to_markdown_records(records: typing.List[typing.List[str]], headers: typing.Optional[typing.List[str]], max_rows: int) -> str: ...
async def _to_markdown_records_async(records: typing.List[typing.List[str]], headers: typing.Optional[typing.List[str]], max_rows: int) -> str: ...


def _error(kind: ErrorKind, message: str) -> Error:
    """(internal) Construct an `Error` with no positional fields — for the
    input-scoped kinds (`NotFound`, `TooManyRows`) that no single record
    caused."""
async def _error_async(kind: ErrorKind, message: str) -> Error:
    """(internal) Construct an `Error` with no positional fields — for the
    input-scoped kinds (`NotFound`, `TooManyRows`) that no single record
    caused."""


__all__ = [
    "Value",
    "ErrorKind",
    "Error",
    "Position",
    "ReaderOptions",
    "WriterOptions",
    "Record",
    "Reader",
    "Rows",
    "Writer",
    "reader",
    "reader_async",
    "open",
    "open_async",
    "read",
    "read_async",
    "parse",
    "parse_async",
    "decode",
    "decode_async",
    "decode_optional",
    "decode_optional_async",
    "decode_one",
    "decode_one_async",
    "writer",
    "writer_async",
    "create",
    "create_async",
    "buffer",
    "buffer_async",
    "write",
    "write_async",
    "stringify",
    "stringify_async",
    "stringify_records",
    "stringify_records_async",
    "to_markdown",
    "to_markdown_async",
    "to_markdown_records",
    "to_markdown_records_async",
]
