# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from baml_bridge import BamlPyHandle as _BamlPyHandle


class Aes256GcmSiv(pydantic.BaseModel):
    field_cipher: _BamlPyHandle = pydantic.Field(alias="_cipher")
    @staticmethod
    def new(key: bytes) -> Aes256GcmSiv:
        """Raises:
            InvalidArgument"""
    @staticmethod
    async def new_async(key: bytes) -> Aes256GcmSiv:
        """Raises:
            InvalidArgument"""


class Aes128GcmSiv(pydantic.BaseModel):
    field_cipher: _BamlPyHandle = pydantic.Field(alias="_cipher")
    @staticmethod
    def new(key: bytes) -> Aes128GcmSiv:
        """Raises:
            InvalidArgument"""
    @staticmethod
    async def new_async(key: bytes) -> Aes128GcmSiv:
        """Raises:
            InvalidArgument"""


class ChaCha20Poly1305(pydantic.BaseModel):
    field_cipher: _BamlPyHandle = pydantic.Field(alias="_cipher")
    @staticmethod
    def new(key: bytes) -> ChaCha20Poly1305:
        """Raises:
            InvalidArgument"""
    @staticmethod
    async def new_async(key: bytes) -> ChaCha20Poly1305:
        """Raises:
            InvalidArgument"""


class XChaCha20Poly1305(pydantic.BaseModel):
    field_cipher: _BamlPyHandle = pydantic.Field(alias="_cipher")
    @staticmethod
    def new(key: bytes) -> XChaCha20Poly1305:
        """Raises:
            InvalidArgument"""
    @staticmethod
    async def new_async(key: bytes) -> XChaCha20Poly1305:
        """Raises:
            InvalidArgument"""


class DecryptionFailure(pydantic.BaseModel):
    algorithm: str
    reason: str


class Sha256(pydantic.BaseModel):
    field_state: _BamlPyHandle = pydantic.Field(alias="_state")
    @staticmethod
    def new() -> Sha256: ...
    @staticmethod
    async def new_async() -> Sha256: ...


__all__ = [
    "Aes256GcmSiv",
    "Aes128GcmSiv",
    "ChaCha20Poly1305",
    "XChaCha20Poly1305",
    "DecryptionFailure",
    "Sha256",
]
