# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

def get_baml_source_files() -> dict[str, str]: ...

from . import ai
from . import baml
from . import reflect
from . import vendor

from .ai.stream import Done as _BamlStreamDone
from baml_bridge import BamlStream as _BamlStream

import typing
import typing_extensions
import pydantic

if typing.TYPE_CHECKING:
    from . import ai
    from .baml import UNSET as UNSET


class ChunkInput(pydantic.BaseModel):
    chunk_id: str
    symbol: str
    node_type: str
    line_start: int
    line_end: int
    content: str


class ChunkSummary(pydantic.BaseModel):
    chunk_id: str
    summary: str


class FileSummaryResult(pydantic.BaseModel):
    summaries: typing.List[ChunkSummary]


def SummarizeFileChunks(language: str, file_path: str, file_content: str, chunks: typing.List[ChunkInput], *, on_event: typing.Union[typing.Callable[[ai.events.Event], None], None, UNSET] = None) -> FileSummaryResult:
    """Raises:
        InvalidArgument, Io, ParseError, Timeout, UnknownError, CompilationError"""
async def SummarizeFileChunks_async(language: str, file_path: str, file_content: str, chunks: typing.List[ChunkInput], *, on_event: typing.Union[typing.Callable[[ai.events.Event], None], None, UNSET] = None) -> FileSummaryResult:
    """Raises:
        InvalidArgument, Io, ParseError, Timeout, UnknownError, CompilationError"""
def SummarizeFileChunks_spec(language: str, file_path: str, file_content: str, chunks: typing.List[ChunkInput]) -> ai.FunctionSpec[FileSummaryResult]:
    """Raises:
        InvalidArgument, Io, ParseError, InvalidRequest"""
async def SummarizeFileChunks_spec_async(language: str, file_path: str, file_content: str, chunks: typing.List[ChunkInput]) -> ai.FunctionSpec[FileSummaryResult]:
    """Raises:
        InvalidArgument, Io, ParseError, InvalidRequest"""
def SummarizeFileChunks_stream(language: str, file_path: str, file_content: str, chunks: typing.List[ChunkInput], *, on_event: typing.Union[typing.Callable[[ai.events.Event], None], None, UNSET] = None) -> _BamlStream[typing.Union[FileSummaryResult, _BamlStreamDone], FileSummaryResult, FileSummaryResult]:
    """Raises:
        InvalidArgument, Io, ParseError, Timeout, UnknownError, CompilationError"""
async def SummarizeFileChunks_stream_async(language: str, file_path: str, file_content: str, chunks: typing.List[ChunkInput], *, on_event: typing.Union[typing.Callable[[ai.events.Event], None], None, UNSET] = None) -> _BamlStream[typing.Union[FileSummaryResult, _BamlStreamDone], FileSummaryResult, FileSummaryResult]:
    """Raises:
        InvalidArgument, Io, ParseError, Timeout, UnknownError, CompilationError"""


def SummarizeChunkAlone(language: str, symbol: str, line_start: int, line_end: int, content: str, parent_context: str, file_context: str, *, on_event: typing.Union[typing.Callable[[ai.events.Event], None], None, UNSET] = None) -> ChunkSummary:
    """Raises:
        InvalidArgument, Io, ParseError, Timeout, UnknownError, CompilationError"""
async def SummarizeChunkAlone_async(language: str, symbol: str, line_start: int, line_end: int, content: str, parent_context: str, file_context: str, *, on_event: typing.Union[typing.Callable[[ai.events.Event], None], None, UNSET] = None) -> ChunkSummary:
    """Raises:
        InvalidArgument, Io, ParseError, Timeout, UnknownError, CompilationError"""
def SummarizeChunkAlone_spec(language: str, symbol: str, line_start: int, line_end: int, content: str, parent_context: str, file_context: str) -> ai.FunctionSpec[ChunkSummary]:
    """Raises:
        InvalidArgument, Io, ParseError, InvalidRequest"""
async def SummarizeChunkAlone_spec_async(language: str, symbol: str, line_start: int, line_end: int, content: str, parent_context: str, file_context: str) -> ai.FunctionSpec[ChunkSummary]:
    """Raises:
        InvalidArgument, Io, ParseError, InvalidRequest"""
def SummarizeChunkAlone_stream(language: str, symbol: str, line_start: int, line_end: int, content: str, parent_context: str, file_context: str, *, on_event: typing.Union[typing.Callable[[ai.events.Event], None], None, UNSET] = None) -> _BamlStream[typing.Union[ChunkSummary, _BamlStreamDone], ChunkSummary, ChunkSummary]:
    """Raises:
        InvalidArgument, Io, ParseError, Timeout, UnknownError, CompilationError"""
async def SummarizeChunkAlone_stream_async(language: str, symbol: str, line_start: int, line_end: int, content: str, parent_context: str, file_context: str, *, on_event: typing.Union[typing.Callable[[ai.events.Event], None], None, UNSET] = None) -> _BamlStream[typing.Union[ChunkSummary, _BamlStreamDone], ChunkSummary, ChunkSummary]:
    """Raises:
        InvalidArgument, Io, ParseError, Timeout, UnknownError, CompilationError"""


__all__ = [
    "ChunkInput",
    "ChunkSummary",
    "FileSummaryResult",
    "SummarizeFileChunks",
    "SummarizeFileChunks_async",
    "SummarizeFileChunks_spec",
    "SummarizeFileChunks_spec_async",
    "SummarizeFileChunks_stream",
    "SummarizeFileChunks_stream_async",
    "SummarizeChunkAlone",
    "SummarizeChunkAlone_async",
    "SummarizeChunkAlone_spec",
    "SummarizeChunkAlone_spec_async",
    "SummarizeChunkAlone_stream",
    "SummarizeChunkAlone_stream_async",
]

from . import reflect as reflect
