# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from baml_bridge import (
    BamlPyHandle as _BamlPyHandle,
    define_function as _define_function,
)


T = typing.TypeVar("T")


class Context(pydantic.BaseModel):
    """
    The temporal context of a thrown error: the error value itself, where it
    was thrown, and the error it superseded while the scope was unwinding (its
    `cause`), if any. Bound by the second parameter of a `catch (e, ctx)`
    handler.

    The chain runs newest → oldest through `cause`; `root_cause` walks to the
    original failure at the tail, and `to_string` renders the whole chain
    Python-style ("During handling of the above error, another error occurred").
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    error: typing.Any
    stack_trace: StackTrace
    cause: typing.Optional[Context] = None
    root_cause       = _define_function("baml.errors.Context.root_cause", "sync",  ["self"], binding_name="root_cause", binding_qualname="Context.root_cause", binding_module=__name__)
    root_cause_async = _define_function("baml.errors.Context.root_cause", "async", ["self"], binding_name="root_cause_async", binding_qualname="Context.root_cause_async", binding_module=__name__)
    _to_string_impl_       = _define_function("baml.errors.Context._to_string_impl", "sync",  ["self"], binding_name="_to_string_impl_", binding_qualname="Context._to_string_impl_", binding_module=__name__)
    _to_string_impl__async = _define_function("baml.errors.Context._to_string_impl", "async", ["self"], binding_name="_to_string_impl__async", binding_qualname="Context._to_string_impl__async", binding_module=__name__)


class InvalidArgument(pydantic.BaseModel):
    """An argument is out of range or otherwise invalid."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class ParseError(pydantic.BaseModel):
    """
    Thrown when text cannot be parsed into the requested type — e.g.
    `int.parse("abc")` or `float.parse("")`.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class Io(pydantic.BaseModel):
    """An I/O operation failed (file, network, etc.)."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class Timeout(pydantic.BaseModel):
    """An operation exceeded its time limit."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str
    duration_ms: typing.Optional[int] = None


class Unsupported(pydantic.BaseModel):
    """The requested operation is not supported in this context."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class AccessError(pydantic.BaseModel):
    """Access to a resource was denied."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class RenderPrompt(pydantic.BaseModel):
    """A prompt template could not be rendered."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class LlmClient(pydantic.BaseModel):
    """An LLM client request failed."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class HostCallable(pydantic.BaseModel):
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str
    class_name: str
    language: str
    traceback: typing.Optional[str] = None
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")


class GenericSdkError(pydantic.BaseModel):
    """
    A catch-all SDK-boundary failure with no more specific class. Synthesized
    host-side from `RuntimeError::Other` so a call-setup failure crosses the
    boundary as structured data rather than a stringified error.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class CompilationError(pydantic.BaseModel):
    """
    A BAML compilation failure surfaced at the call boundary. Synthesized
    host-side from `RuntimeError::Compilation`.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class TypeMismatch(pydantic.BaseModel):
    """
    A value/type mismatch at the call boundary — a caller passed an argument
    that doesn't fit the callee's (possibly inferred) type, a generic `TypeVar`
    could not be inferred and must be specified, or repeat occurrences of a
    `TypeVar` have no consistent binding. Synthesized host-side from
    `EngineError::TypeMismatch`; each host SDK surfaces it as its native
    type-error (Python `TypeError`). The stdlib itself never throws this class
    from BAML source (reflection's typed reads throw
    `reflect.errors.TypeMismatch` instead); user code remains free to.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


class StackFrame(pydantic.BaseModel):
    """A single frame in a call stack, identifying a source location."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    file: str
    line: int
    function_name: str


class StackTrace(pydantic.BaseModel):
    """A captured call stack, consisting of one or more `StackFrame` entries."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    frames: typing.List[StackFrame]
    _to_string_impl_       = _define_function("baml.errors.StackTrace._to_string_impl", "sync",  ["self"], binding_name="_to_string_impl_", binding_qualname="StackTrace._to_string_impl_", binding_module=__name__)
    _to_string_impl__async = _define_function("baml.errors.StackTrace._to_string_impl", "async", ["self"], binding_name="_to_string_impl__async", binding_qualname="StackTrace._to_string_impl__async", binding_module=__name__)


class UnknownError(pydantic.BaseModel):
    """Universal wrapper for errors that do not implement a known capability channel."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    data: typing.Any
    message: typing.List[str]
    from_       = staticmethod(_define_function("baml.errors.UnknownError.from", "sync",  ["data"], binding_name="from_", binding_qualname="UnknownError.from_", binding_module=__name__, type_params=["T"]))
    from__async = staticmethod(_define_function("baml.errors.UnknownError.from", "async", ["data"], binding_name="from__async", binding_qualname="UnknownError.from__async", binding_module=__name__, type_params=["T"]))
    with_message       = staticmethod(_define_function("baml.errors.UnknownError.with_message", "sync",  ["data", "message"], binding_name="with_message", binding_qualname="UnknownError.with_message", binding_module=__name__, type_params=["T"]))
    with_message_async = staticmethod(_define_function("baml.errors.UnknownError.with_message", "async", ["data", "message"], binding_name="with_message_async", binding_qualname="UnknownError.with_message_async", binding_module=__name__, type_params=["T"]))
    _preserve_context_       = staticmethod(_define_function("baml.errors.UnknownError._preserve_context", "sync",  ["source", "target"], binding_name="_preserve_context_", binding_qualname="UnknownError._preserve_context_", binding_module=__name__))
    _preserve_context__async = staticmethod(_define_function("baml.errors.UnknownError._preserve_context", "async", ["source", "target"], binding_name="_preserve_context__async", binding_qualname="UnknownError._preserve_context__async", binding_module=__name__))


__all__ = [
    "Context",
    "InvalidArgument",
    "ParseError",
    "Io",
    "Timeout",
    "Unsupported",
    "AccessError",
    "RenderPrompt",
    "LlmClient",
    "HostCallable",
    "GenericSdkError",
    "CompilationError",
    "TypeMismatch",
    "StackFrame",
    "StackTrace",
    "UnknownError",
]
