# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from baml_bridge import BamlPyHandle as _BamlPyHandle


T = typing.TypeVar("T")


class Context(pydantic.BaseModel):
    error: typing.Any
    stack_trace: StackTrace
    cause: typing.Optional[Context] = None
    def root_cause(self) -> Context:
        """The original error at the tail of the cause chain — walks `cause` to the
        deepest link. Returns `self` when nothing was superseded."""
    async def root_cause_async(self) -> Context:
        """The original error at the tail of the cause chain — walks `cause` to the
        deepest link. Returns `self` when nothing was superseded."""
    def _to_string_impl_(self) -> str: ...
    async def _to_string_impl__async(self) -> str: ...


class InvalidArgument(pydantic.BaseModel):
    message: str


class ParseError(pydantic.BaseModel):
    message: str


class Io(pydantic.BaseModel):
    message: str


class Timeout(pydantic.BaseModel):
    message: str
    duration_ms: typing.Optional[int] = None


class Unsupported(pydantic.BaseModel):
    message: str


class AccessError(pydantic.BaseModel):
    message: str


class RenderPrompt(pydantic.BaseModel):
    message: str


class LlmClient(pydantic.BaseModel):
    message: str


class HostCallable(pydantic.BaseModel):
    message: str
    class_name: str
    language: str
    traceback: typing.Optional[str] = None
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")


class GenericSdkError(pydantic.BaseModel):
    message: str


class CompilationError(pydantic.BaseModel):
    message: str


class TypeMismatch(pydantic.BaseModel):
    message: str


class StackFrame(pydantic.BaseModel):
    file: str
    line: int
    function_name: str


class StackTrace(pydantic.BaseModel):
    frames: typing.List[StackFrame]
    def _to_string_impl_(self) -> str: ...
    async def _to_string_impl__async(self) -> str: ...


class UnknownError(pydantic.BaseModel):
    data: typing.Any
    message: typing.List[str]
    @staticmethod
    def from_(data: typing.Any, *, _types: dict[str, typing.Any]) -> typing.Union[T, UnknownError]:
        """Preserve a known `T`, recover a wrapped `T`, pass an existing
        `UnknownError` through, or wrap an otherwise unknown value."""
    @staticmethod
    async def from__async(data: typing.Any, *, _types: dict[str, typing.Any]) -> typing.Union[T, UnknownError]:
        """Preserve a known `T`, recover a wrapped `T`, pass an existing
        `UnknownError` through, or wrap an otherwise unknown value."""
    @staticmethod
    def with_message(data: typing.Any, message: str, *, _types: dict[str, typing.Any]) -> typing.Union[T, UnknownError]:
        """As with `from`, but append a breadcrumb while the value remains
        unknown."""
    @staticmethod
    async def with_message_async(data: typing.Any, message: str, *, _types: dict[str, typing.Any]) -> typing.Union[T, UnknownError]:
        """As with `from`, but append a breadcrumb while the value remains
        unknown."""
    @staticmethod
    def _preserve_context_(source: typing.Any, target: typing.Any) -> None: ...
    @staticmethod
    async def _preserve_context__async(source: typing.Any, target: typing.Any) -> None: ...


__all__ = [
    "Context",
    "InvalidArgument",
    "ParseError",
    "Io",
    "Timeout",
    "Unsupported",
    "AccessError",
    "RenderPrompt",
    "LlmClient",
    "HostCallable",
    "GenericSdkError",
    "CompilationError",
    "TypeMismatch",
    "StackFrame",
    "StackTrace",
    "UnknownError",
]
