# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from ... import baml

from baml_bridge import define_function as _define_function


Item = typing_extensions.TypeAliasType("Item", typing.Union["Table", typing.List["Item"], bool, int, float, str, "baml.time.ZonedDateTime", "baml.time.PlainDateTime", "baml.time.PlainDate", "baml.time.PlainTime"])


class Table(pydantic.BaseModel):
    """
    A TOML [table](https://toml.io/en/latest#table): a collection of key/value
    pairs.

    A parsed document is itself a `Table`. Nested tables — `[a.b]`, inline
    `{ ... }`, and array-of-table entries — are `Table` values inside `items`.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    items: typing.Dict[str, Item]
    parse       = staticmethod(_define_function("baml.toml.Table.parse", "sync",  ["s"], binding_name="parse", binding_qualname="Table.parse", binding_module=__name__))
    parse_async = staticmethod(_define_function("baml.toml.Table.parse", "async", ["s"], binding_name="parse_async", binding_qualname="Table.parse_async", binding_module=__name__))


table_from_json       = _define_function("baml.toml.table_from_json", "sync",  ["j"], binding_name="table_from_json", binding_qualname="table_from_json", binding_module=__name__)
table_from_json.__doc__ = """Decodes a JSON object into a `Table`, skipping null values.

A `null` object value is dropped key and all — the key does not appear in
`items` — and nested objects are decoded the same way. A `null` inside an
*array* has no key to drop, so it throws: TOML arrays have no hole to put
it in.

The return type is a concrete `Table` so that arm-reachability over the
recursive `json` map pattern is analyzed without the abstract `Self` of
`Table`'s `baml.FromJson` impl.

# Throws

- `baml.json.DecodeError` if `j` is not a JSON object, or if a `null`
  appears as an array element anywhere beneath it.

Raises:
    DecodeError"""
table_from_json_async = _define_function("baml.toml.table_from_json", "async", ["j"], binding_name="table_from_json_async", binding_qualname="table_from_json_async", binding_module=__name__)
table_from_json_async.__doc__ = """Decodes a JSON object into a `Table`, skipping null values.

A `null` object value is dropped key and all — the key does not appear in
`items` — and nested objects are decoded the same way. A `null` inside an
*array* has no key to drop, so it throws: TOML arrays have no hole to put
it in.

The return type is a concrete `Table` so that arm-reachability over the
recursive `json` map pattern is analyzed without the abstract `Self` of
`Table`'s `baml.FromJson` impl.

# Throws

- `baml.json.DecodeError` if `j` is not a JSON object, or if a `null`
  appears as an array element anywhere beneath it.

Raises:
    DecodeError"""


item_to_json       = _define_function("baml.toml.item_to_json", "sync",  ["item"], binding_name="item_to_json", binding_qualname="item_to_json", binding_module=__name__)
item_to_json.__doc__ = """Converts a TOML item to a JSON value.

Lossy: TOML datetimes become JSON strings — `ZonedDateTime` as RFC 3339,
the `Plain*` types as zoneless ISO 8601. The conversion does not
round-trip, because `item_from_json` reads those strings back as strings.

# Throws

- `baml.json.SerializationError` if a datetime cannot be formatted: a year
  outside the 4-digit range the ISO 8601 / RFC 3339 forms admit, or a
  `ZonedDateTime` naming an IANA zone the host does not know.

Raises:
    SerializationError"""
item_to_json_async = _define_function("baml.toml.item_to_json", "async", ["item"], binding_name="item_to_json_async", binding_qualname="item_to_json_async", binding_module=__name__)
item_to_json_async.__doc__ = """Converts a TOML item to a JSON value.

Lossy: TOML datetimes become JSON strings — `ZonedDateTime` as RFC 3339,
the `Plain*` types as zoneless ISO 8601. The conversion does not
round-trip, because `item_from_json` reads those strings back as strings.

# Throws

- `baml.json.SerializationError` if a datetime cannot be formatted: a year
  outside the 4-digit range the ISO 8601 / RFC 3339 forms admit, or a
  `ZonedDateTime` naming an IANA zone the host does not know.

Raises:
    SerializationError"""


item_from_json       = _define_function("baml.toml.item_from_json", "sync",  ["json"], binding_name="item_from_json", binding_qualname="item_from_json", binding_module=__name__)
item_from_json.__doc__ = """Converts a JSON value to a TOML item.

`Table.from_json` is usually the better entry point, since it skips nulls
instead of erroring on them. This inverts `item_to_json` only up to the
datetime loss noted there: a JSON string stays a `string`, never a
`baml.time` value.

# Throws

- `baml.json.DecodeError` if `json` is `null` or `bigint`, or if either
  appears as an array element anywhere beneath it. Nulls in *object* values
  are skipped by the `Table.from_json` this recurses through.

Raises:
    DecodeError"""
item_from_json_async = _define_function("baml.toml.item_from_json", "async", ["json"], binding_name="item_from_json_async", binding_qualname="item_from_json_async", binding_module=__name__)
item_from_json_async.__doc__ = """Converts a JSON value to a TOML item.

`Table.from_json` is usually the better entry point, since it skips nulls
instead of erroring on them. This inverts `item_to_json` only up to the
datetime loss noted there: a JSON string stays a `string`, never a
`baml.time` value.

# Throws

- `baml.json.DecodeError` if `json` is `null` or `bigint`, or if either
  appears as an array element anywhere beneath it. Nulls in *object* values
  are skipped by the `Table.from_json` this recurses through.

Raises:
    DecodeError"""


class ParseError(pydantic.BaseModel):
    """
    TOML text that cannot be read as a `Table`.

    Covers both syntax errors and values TOML admits but BAML cannot hold,
    notably 64-bit integers outside BAML's 63-bit `int`. For a syntax error
    `message` is the parser's own diagnostic, locating the offending span; for
    an unrepresentable value it names the limit instead.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    message: str


__all__ = [
    "Item",
    "Table",
    "table_from_json",
    "table_from_json_async",
    "item_to_json",
    "item_to_json_async",
    "item_from_json",
    "item_from_json_async",
    "ParseError",
]
