# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

if typing.TYPE_CHECKING:
    from ... import reflect
    from ...baml import UNSET as UNSET

from baml_bridge import BamlPyHandle as _BamlPyHandle


T = typing.TypeVar("T")


class Field(pydantic.BaseModel):
    name: str
    type: typing.Optional[typing.Any] = None
    meta: reflect.Meta
    field_owner: typing.Optional[typing.Any] = pydantic.Field(default=None, alias="_owner")
    def metadata(self) -> reflect.Meta:
        """This field's schema metadata. Same value as the `meta` field."""
    async def metadata_async(self) -> reflect.Meta:
        """This field's schema metadata. Same value as the `meta` field."""
    def value(self, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
        """Read this field from its bound owner. An ownerless type-side descriptor
        returns `null`.

        Raises:
            TypeMismatch"""
    async def value_async(self, *, _types: dict[str, typing.Any]) -> typing.Optional[T]:
        """Read this field from its bound owner. An ownerless type-side descriptor
        returns `null`.

        Raises:
            TypeMismatch"""


def new(name: str, fields: typing.Dict[str, typing.Union[typing.Any, reflect.WithMeta[typing.Any]]], *, implementations: typing.Union[typing.List[reflect.interface.Implementation], UNSET] = []) -> Type:
    """Construct a closed runtime class. Map iteration order is definition order.

    Raises:
        CompilationError"""
async def new_async(name: str, fields: typing.Dict[str, typing.Union[typing.Any, reflect.WithMeta[typing.Any]]], *, implementations: typing.Union[typing.List[reflect.interface.Implementation], UNSET] = []) -> Type:
    """Construct a closed runtime class. Map iteration order is definition order.

    Raises:
        CompilationError"""


def _new(name: str, fields: typing.Dict[str, typing.Union[typing.Any, reflect.WithMeta[typing.Any]]], implementations: typing.List[reflect.interface.Implementation]) -> Type:
    """Raises:
        CompilationError"""
async def _new_async(name: str, fields: typing.Dict[str, typing.Union[typing.Any, reflect.WithMeta[typing.Any]]], implementations: typing.List[reflect.interface.Implementation]) -> Type:
    """Raises:
        CompilationError"""


def builder(name: str) -> Builder: ...
async def builder_async(name: str) -> Builder: ...


class Builder(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    field_roots: typing.List[typing.Any] = pydantic.Field(alias="_roots")
    field_neighbors: typing.List[Builder] = pydantic.Field(alias="_neighbors")
    field_resolved: typing.Optional[typing.Any] = pydantic.Field(default=None, alias="_resolved")
    def field(self, name: str, ty: typing.Union[typing.Any, reflect.WithMeta[typing.Any], PendingType, reflect.WithMeta[PendingType]]) -> Builder:
        """Raises:
            CompilationError"""
    async def field_async(self, name: str, ty: typing.Union[typing.Any, reflect.WithMeta[typing.Any], PendingType, reflect.WithMeta[PendingType]]) -> Builder:
        """Raises:
            CompilationError"""
    def type(self) -> PendingType: ...
    async def type_async(self) -> PendingType: ...
    def build(self, *, implementations: typing.Union[typing.List[reflect.interface.Implementation], UNSET] = []) -> Type:
        """Validate and freeze this builder's complete connected recursive group.

        Raises:
            CompilationError"""
    async def build_async(self, *, implementations: typing.Union[typing.List[reflect.interface.Implementation], UNSET] = []) -> Type:
        """Validate and freeze this builder's complete connected recursive group.

        Raises:
            CompilationError"""
    def _build_(self, implementations: typing.List[reflect.interface.Implementation]) -> Type:
        """Raises:
            CompilationError"""
    async def _build__async(self, implementations: typing.List[reflect.interface.Implementation]) -> Type:
        """Raises:
            CompilationError"""


class PendingType(pydantic.BaseModel):
    field_handle: _BamlPyHandle = pydantic.Field(alias="_handle")
    field_roots: typing.List[typing.Any] = pydantic.Field(alias="_roots")
    field_resolved: typing.Optional[typing.Any] = pydantic.Field(default=None, alias="_resolved")
    def array(self) -> PendingType: ...
    async def array_async(self) -> PendingType: ...
    def optional(self) -> PendingType: ...
    async def optional_async(self) -> PendingType: ...
    def union(self, others: typing.List[typing.Union[typing.Any, PendingType]]) -> PendingType: ...
    async def union_async(self, others: typing.List[typing.Union[typing.Any, PendingType]]) -> PendingType: ...
    def resolved(self) -> typing.Optional[typing.Any]: ...
    async def resolved_async(self) -> typing.Optional[typing.Any]: ...
    def meta(self, *, alias: typing.Union[str, None, UNSET] = None, description: typing.Union[str, None, UNSET] = None, docstring: typing.Union[str, None, UNSET] = None, other: typing.Union[typing.Dict[str, str], None, UNSET] = None) -> reflect.WithMeta[PendingType]: ...
    async def meta_async(self, *, alias: typing.Union[str, None, UNSET] = None, description: typing.Union[str, None, UNSET] = None, docstring: typing.Union[str, None, UNSET] = None, other: typing.Union[typing.Dict[str, str], None, UNSET] = None) -> reflect.WithMeta[PendingType]: ...


def get_field(value: typing.Any, name: str, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        CompilationError"""
async def get_field_async(value: typing.Any, name: str, *, _types: dict[str, typing.Any]) -> T:
    """Raises:
        CompilationError"""


class Type(pydantic.BaseModel):
    field_ty: typing.Any = pydantic.Field(alias="_ty")
    def fields(self) -> typing.List[Field]: ...
    async def fields_async(self) -> typing.List[Field]: ...
    def meta(self) -> reflect.Meta: ...
    async def meta_async(self) -> reflect.Meta: ...


__all__ = [
    "Field",
    "new",
    "new_async",
    "builder",
    "builder_async",
    "Builder",
    "PendingType",
    "get_field",
    "get_field_async",
    "Type",
]
