# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from baml_bridge import BamlPyHandle as _BamlPyHandle


T = typing.TypeVar("T")


class _ParseCache(pydantic.BaseModel, typing.Generic[T]):
    field_data: _BamlPyHandle = pydantic.Field(alias="_data")
    def _parse_final_(self, json: str) -> T:
        """(internal) Final SAP operation shared by streams and public SAP.

        Raises:
            LlmClient"""
    async def _parse_final__async(self, json: str) -> T:
        """(internal) Final SAP operation shared by streams and public SAP.

        Raises:
            LlmClient"""
    def _parse_partial_(self, json: str) -> typing.Union[T, _NoYield]:
        """(internal) Partial SAP operation used by `ai.stream.Stream`.

        Raises:
            LlmClient"""
    async def _parse_partial__async(self, json: str) -> typing.Union[T, _NoYield]:
        """(internal) Partial SAP operation used by `ai.stream.Stream`.

        Raises:
            LlmClient"""


class _NoYield(pydantic.BaseModel):
    ...


def _new_parse_cache(*, _types: dict[str, typing.Any]) -> _ParseCache[T]:
    """(internal) Builds a parse cache for `T`.

    A free function rather than a `_ParseCache` static method: a *static*
    method's class type args have no receiver to ride in on, and the call path
    derives them from the receiver's type — so a static method would be given
    operand slots the call site never fills. Instance methods on a generic
    class (`_parse_final`, `_parse_partial`) are threaded correctly."""
async def _new_parse_cache_async(*, _types: dict[str, typing.Any]) -> _ParseCache[T]:
    """(internal) Builds a parse cache for `T`.

    A free function rather than a `_ParseCache` static method: a *static*
    method's class type args have no receiver to ride in on, and the call path
    derives them from the receiver's type — so a static method would be given
    operand slots the call site never fills. Instance methods on a generic
    class (`_parse_final`, `_parse_partial`) are threaded correctly."""


def parse(text: str, *, _types: dict[str, typing.Any]) -> T:
    """Parse an LLM's raw text output into `T` with Schema-Aligned Parsing.

    # Throws
    - `baml.errors.ParseError` if parsing fails.

    Raises:
        ParseError"""
async def parse_async(text: str, *, _types: dict[str, typing.Any]) -> T:
    """Parse an LLM's raw text output into `T` with Schema-Aligned Parsing.

    # Throws
    - `baml.errors.ParseError` if parsing fails.

    Raises:
        ParseError"""


def parse_type(t: typing.Any, text: str) -> typing.Any:
    """Parse against a runtime `type` value when the schema is data rather than a
    lexical type parameter. Narrow the returned `unknown` at the call site.

    It is generally recommended to use `baml.sap.parse` instead.

    Raises:
        ParseError"""
async def parse_type_async(t: typing.Any, text: str) -> typing.Any:
    """Parse against a runtime `type` value when the schema is data rather than a
    lexical type parameter. Narrow the returned `unknown` at the call site.

    It is generally recommended to use `baml.sap.parse` instead.

    Raises:
        ParseError"""


__all__ = [
    "parse",
    "parse_async",
    "parse_type",
    "parse_type_async",
]
