# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from ... import reflect

from baml_bridge import define_function as _define_function


class Value(pydantic.BaseModel):
    """One variant of an enum: its name and its schema metadata."""
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    name: str
    meta: reflect.Meta


value       = _define_function("reflect.enum.value", "sync",  ["name"], ["alias", "description", "docstring", "other"], binding_name="value", binding_qualname="value", binding_module=__name__)
value_async = _define_function("reflect.enum.value", "async", ["name"], ["alias", "description", "docstring", "other"], binding_name="value_async", binding_qualname="value_async", binding_module=__name__)


new       = _define_function("reflect.enum.new", "sync",  ["name", "values"], binding_name="new", binding_qualname="new", binding_module=__name__)
new.__doc__ = """Raises:
    CompilationError"""
new_async = _define_function("reflect.enum.new", "async", ["name", "values"], binding_name="new_async", binding_qualname="new_async", binding_module=__name__)
new_async.__doc__ = """Raises:
    CompilationError"""


get_value       = _define_function("reflect.enum.get_value", "sync",  ["value"], binding_name="get_value", binding_qualname="get_value", binding_module=__name__)
get_value.__doc__ = """Raises:
    InvalidArgument"""
get_value_async = _define_function("reflect.enum.get_value", "async", ["value"], binding_name="get_value_async", binding_qualname="get_value_async", binding_module=__name__)
get_value_async.__doc__ = """Raises:
    InvalidArgument"""


class Type(pydantic.BaseModel):
    """
    An enum-kind view of a `type` value. Users never construct this class.

    Attributes:
        field_ty: The wrapped `type` value. Private by invariant: reflection natives are
            its only readers, and each kind method panics if the held type no longer
            classifies as this view's kind.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_ty: typing.Any = pydantic.Field(alias="_ty")
    values       = _define_function("reflect.enum.Type.values", "sync",  ["self"], binding_name="values", binding_qualname="Type.values", binding_module=__name__)
    values_async = _define_function("reflect.enum.Type.values", "async", ["self"], binding_name="values_async", binding_qualname="Type.values_async", binding_module=__name__)
    meta       = _define_function("reflect.enum.Type.meta", "sync",  ["self"], binding_name="meta", binding_qualname="Type.meta", binding_module=__name__)
    meta_async = _define_function("reflect.enum.Type.meta", "async", ["self"], binding_name="meta_async", binding_qualname="Type.meta_async", binding_module=__name__)


__all__ = [
    "Value",
    "value",
    "value_async",
    "new",
    "new_async",
    "get_value",
    "get_value_async",
    "Type",
]
