# ruff: noqa
# flake8: noqa
# pylint: skip-file
# mypy: ignore-errors
# pyright: reportPrivateUsage=false, reportUnknownArgumentType=false
# fmt: off
# isort: skip_file

# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, run one of the following:
#
#  $ uv add baml-bridge
#  $ pip install baml-bridge
#  $ conda run python -m pip install baml-bridge
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using `baml generate`

from __future__ import annotations

import typing
import typing_extensions
import pydantic

from ... import ai
from ... import baml

from baml_bridge import define_function as _define_function

from baml_bridge import BamlStream as Stream


T = typing.TypeVar("T")


class SseEvent(pydantic.BaseModel):
    """
    One decoded raw SSE event, as produced by `baml.http.SseStream.next()`:
    the batch string is a JSON array of these objects.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    event: typing.Optional[str] = None
    data: typing.Optional[str] = None
    id: typing.Optional[str] = None


decode_sse_batch       = _define_function("ai.stream.decode_sse_batch", "sync",  ["batch"], binding_name="decode_sse_batch", binding_qualname="decode_sse_batch", binding_module=__name__)
decode_sse_batch.__doc__ = """One `SseStream.next()` batch -> the raw SSE events it contains. Provider
decoders parse each event's `data` payload with their own envelope classes.

Raises:
    DecodeError, ParseError"""
decode_sse_batch_async = _define_function("ai.stream.decode_sse_batch", "async", ["batch"], binding_name="decode_sse_batch_async", binding_qualname="decode_sse_batch_async", binding_module=__name__)
decode_sse_batch_async.__doc__ = """One `SseStream.next()` batch -> the raw SSE events it contains. Provider
decoders parse each event's `data` payload with their own envelope classes.

Raises:
    DecodeError, ParseError"""


class TextDelta(pydantic.BaseModel):
    """
    One incremental piece of assistant text. The delta contract: the chunk is
    NOT the accumulated text so far, it is only the newly arrived piece.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    text: str


class TurnMeta(pydantic.BaseModel):
    """
    Turn metadata as it arrives on the wire. Providers send stop_reason and
    token counts on different events; each TurnMeta carries what its event had
    and TurnStream folds non-null fields together (last write wins).
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    stop_reason: typing.Optional[ai.content.StopReason] = None
    input_tokens: typing.Optional[int] = None
    output_tokens: typing.Optional[int] = None


class TurnDone(pydantic.BaseModel):
    """
    The provider's explicit end-of-turn marker — the decoded form of `[DONE]`,
    `response.completed`, `message_stop`, a chunk with `finishReason`, …

    A decoder for a protocol that HAS such a marker must yield TurnDone when it
    sees it AND its `from_sse` call must pass `require_terminal` (see the
    termination contract at the top of this file); the stream then reports a
    connection that closed early as a failure instead of a complete turn. For a
    protocol with no terminal marker, TurnDone is optional and a socket close
    still completes the turn.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )


class Done(pydantic.BaseModel):
    """
    The single end-of-stream marker returned by both raw turn streams and typed
    function streams. A nominal sentinel is required because null may itself be
    a valid partial value.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )


class TurnStream(pydantic.BaseModel):
    """
    The raw text-delta stream of ONE model turn. Pull-based: nothing is read
    from the wire until `next()` or `final_turn()` is called.

    `next()` yields DELTA chunks (each item is only the newly arrived text,
    never the accumulated prefix) and returns Done when the turn is over.
    `final_turn()` drains the rest of the stream and returns the completed
    turn: the accumulated text as one Text block, the folded stop_reason, and
    usage where the wire provided token counts.
    """
    model_config = pydantic.ConfigDict(
        arbitrary_types_allowed=True,
        extra="ignore",
        populate_by_name=True,
    )
    field_event_source: typing.Optional[EventSource] = pydantic.Field(default=None, alias="_event_source")
    field_sse: typing.Optional[baml.http.SseStream] = pydantic.Field(default=None, alias="_sse")
    field_decode: typing.Optional[typing.Callable[[str], typing.List[Event]]] = pydantic.Field(default=None, alias="_decode")
    field_chunks: typing.List[str] = pydantic.Field(alias="_chunks")
    field_cursor: int = pydantic.Field(alias="_cursor")
    field_pending: typing.List[Event] = pydantic.Field(alias="_pending")
    field_pcursor: int = pydantic.Field(alias="_pcursor")
    field_text: str = pydantic.Field(alias="_text")
    field_stop_reason: typing.Optional[ai.content.StopReason] = pydantic.Field(default=None, alias="_stop_reason")
    field_input_tokens: typing.Optional[int] = pydantic.Field(default=None, alias="_input_tokens")
    field_output_tokens: typing.Optional[int] = pydantic.Field(default=None, alias="_output_tokens")
    field_done: bool = pydantic.Field(alias="_done")
    field_require_terminal: typing.Optional[str] = pydantic.Field(default=None, alias="_require_terminal")
    field_saw_terminal: bool = pydantic.Field(alias="_saw_terminal")
    field_calls: typing.List[ai.events.LLMCall] = pydantic.Field(alias="_calls")
    field_wire_call: typing.Optional[ai.events.LLMCall] = pydantic.Field(default=None, alias="_wire_call")
    field_call_started: typing.Optional[baml.time.Instant] = pydantic.Field(default=None, alias="_call_started")
    field_ttft_from: typing.Optional[baml.time.Instant] = pydantic.Field(default=None, alias="_ttft_from")
    field_capture_sse: bool = pydantic.Field(alias="_capture_sse")
    from_sse       = staticmethod(_define_function("ai.stream.TurnStream.from_sse", "sync",  ["sse", "decode"], ["require_terminal"], binding_name="from_sse", binding_qualname="TurnStream.from_sse", binding_module=__name__))
    from_sse_async = staticmethod(_define_function("ai.stream.TurnStream.from_sse", "async", ["sse", "decode"], ["require_terminal"], binding_name="from_sse_async", binding_qualname="TurnStream.from_sse_async", binding_module=__name__))
    from_chunks       = staticmethod(_define_function("ai.stream.TurnStream.from_chunks", "sync",  ["chunks"], binding_name="from_chunks", binding_qualname="TurnStream.from_chunks", binding_module=__name__))
    from_chunks_async = staticmethod(_define_function("ai.stream.TurnStream.from_chunks", "async", ["chunks"], binding_name="from_chunks_async", binding_qualname="TurnStream.from_chunks_async", binding_module=__name__))
    from_event_source       = staticmethod(_define_function("ai.stream.TurnStream.from_event_source", "sync",  ["next_event"], binding_name="from_event_source", binding_qualname="TurnStream.from_event_source", binding_module=__name__))
    from_event_source_async = staticmethod(_define_function("ai.stream.TurnStream.from_event_source", "async", ["next_event"], binding_name="from_event_source_async", binding_qualname="TurnStream.from_event_source_async", binding_module=__name__))
    _stamp_first_delta_       = _define_function("ai.stream.TurnStream._stamp_first_delta", "sync",  ["self"], binding_name="_stamp_first_delta_", binding_qualname="TurnStream._stamp_first_delta_", binding_module=__name__)
    _stamp_first_delta__async = _define_function("ai.stream.TurnStream._stamp_first_delta", "async", ["self"], binding_name="_stamp_first_delta__async", binding_qualname="TurnStream._stamp_first_delta__async", binding_module=__name__)
    _capture_batch_       = _define_function("ai.stream.TurnStream._capture_batch", "sync",  ["self", "batch"], binding_name="_capture_batch_", binding_qualname="TurnStream._capture_batch_", binding_module=__name__)
    _capture_batch__async = _define_function("ai.stream.TurnStream._capture_batch", "async", ["self", "batch"], binding_name="_capture_batch__async", binding_qualname="TurnStream._capture_batch__async", binding_module=__name__)
    _finish_       = _define_function("ai.stream.TurnStream._finish", "sync",  ["self"], binding_name="_finish_", binding_qualname="TurnStream._finish_", binding_module=__name__)
    _finish__async = _define_function("ai.stream.TurnStream._finish", "async", ["self"], binding_name="_finish__async", binding_qualname="TurnStream._finish__async", binding_module=__name__)
    _check_terminal_       = _define_function("ai.stream.TurnStream._check_terminal", "sync",  ["self"], binding_name="_check_terminal_", binding_qualname="TurnStream._check_terminal_", binding_module=__name__)
    _check_terminal__async = _define_function("ai.stream.TurnStream._check_terminal", "async", ["self"], binding_name="_check_terminal__async", binding_qualname="TurnStream._check_terminal__async", binding_module=__name__)
    next       = _define_function("ai.stream.TurnStream.next", "sync",  ["self"], binding_name="next", binding_qualname="TurnStream.next", binding_module=__name__)
    next_async = _define_function("ai.stream.TurnStream.next", "async", ["self"], binding_name="next_async", binding_qualname="TurnStream.next_async", binding_module=__name__)
    final_turn       = _define_function("ai.stream.TurnStream.final_turn", "sync",  ["self"], binding_name="final_turn", binding_qualname="TurnStream.final_turn", binding_module=__name__)
    final_turn_async = _define_function("ai.stream.TurnStream.final_turn", "async", ["self"], binding_name="final_turn_async", binding_qualname="TurnStream.final_turn_async", binding_module=__name__)


from_spec       = _define_function("ai.stream.from_spec", "sync",  ["spec"], ["client", "on_event"], binding_name="from_spec", binding_qualname="from_spec", binding_module=__name__, type_params=["T"])
from_spec.__doc__ = """One-turn streaming over a spec: render the spec's prompt exactly as the
default runner's first turn would, require a streaming-capable client, and
return the typed partial stream. The compiler-private `Fn@stream` entry
calls this function; host stream helpers reach that companion through the
normal bridge.

Streaming does not run the tool loop yet: a spec with a non-empty toolbox
is rejected. The client override is typed as the capability, so passing a
non-streaming client fails at the call site; the spec's DEFAULT client is
only checked at runtime (ai.errors.StreamingUnsupported when it cannot
stream).

Raises:
    InvalidArgument, Timeout, UnknownError, CompilationError"""
from_spec_async = _define_function("ai.stream.from_spec", "async", ["spec"], ["client", "on_event"], binding_name="from_spec_async", binding_qualname="from_spec_async", binding_module=__name__, type_params=["T"])
from_spec_async.__doc__ = """One-turn streaming over a spec: render the spec's prompt exactly as the
default runner's first turn would, require a streaming-capable client, and
return the typed partial stream. The compiler-private `Fn@stream` entry
calls this function; host stream helpers reach that companion through the
normal bridge.

Streaming does not run the tool loop yet: a spec with a non-empty toolbox
is rejected. The client override is typed as the capability, so passing a
non-streaming client fails at the call site; the spec's DEFAULT client is
only checked at runtime (ai.errors.StreamingUnsupported when it cannot
stream).

Raises:
    InvalidArgument, Timeout, UnknownError, CompilationError"""


Event: typing.TypeAlias = typing.Union[TextDelta, TurnMeta, TurnDone]


EventSource: typing.TypeAlias = typing.Callable[[], typing.Union[Event, Done]]


__all__ = [
    "SseEvent",
    "decode_sse_batch",
    "decode_sse_batch_async",
    "TextDelta",
    "TurnMeta",
    "TurnDone",
    "Done",
    "TurnStream",
    "Stream",
    "from_spec",
    "from_spec_async",
    "Event",
    "EventSource",
]

class StreamingClient:
    """Erased runtime token for BAML interface `ai.stream.StreamingClient`."""
    __baml_interface_fqn__ = "ai.stream.StreamingClient"

    def __new__(cls, *args, **kwargs):
        raise TypeError("BAML interface tokens cannot be instantiated")

    @classmethod
    def __class_getitem__(cls, args):
        import types
        return types.GenericAlias(cls, args)


try:
    __all__.extend(["StreamingClient"])
except NameError:
    __all__ = ["StreamingClient"]
